### ISSUE TITLE
Playback stops in the middle of stream

### ISSUE THREAD

**Issue by Hiroshi-p** [mangui/flashls#101]
Hello mangui,
I hit a few streams that flashls does not play till the end correctly.
Here is the example: http://panopto-public-scratch.s3.amazonaws.com/21762/master.m3u8

When I put this URL into your chromeless sample page and then play, it plays back up to around 6.5 seconds and then suddenly stops. I do not see any logging message which suggests any error.
This stream works fine with iOS Safari browser and VLC player on PC.

Could you take a look what is wrong here?

**Comment by mangui** [comment]
@Hiroshi-p I rechecked http://panopto-public-scratch.s3.amazonaws.com/21762/master.m3u8 with http://www.flashls.org/latest/examples/chromeless/ and http://www.flashls.org/latest/examples/osmf/GrindPlayer.html and I do not observe any macroblocks anymore.
plz reopen the ticket if you still observe similar issue
cheers,
mangui

**Comment by Hiroshi-p** [comment]
@mangui ,
Thank you for checking.
This is same situation as #132. 
This problem does not happen any more with the latest flashls, while I may still get repro with older version of flashls (v0.3.2). It looks fixed by some change in between.
