### ISSUE TITLE
avoid redownloading of fragments

### ISSUE THREAD

**Issue by ankurss** [mangui/flashls#12]
copy pasting mangui's previous post

mark the fragments that have already been loaded, to avoid switching up in case they are reloaded. this is the only way to get rid of this.
a better alternative in the long term would be to to implement a fragment cache of configurable size, with LRU policy (in case we reach the cache size limit, the Least Recently Used items would be flushed, i.e. the oldest fragments in case of continuous playback)

**Comment by sydcanem** [comment]
Great update. Works well on videojs. Only issue I've found is when seeking, the buffer progress bar flickers. Here's a video that shows the flickering https://vimeo.com/116730774.

**Comment by mangui** [comment]
Hi @portokala123 @sydcanem would you mind rechecking your respective issues with latest flashls/dev ? while implementing altaudio support I did some fixing around seeking that might also address your issues
cheers,
Mangui

**Comment by mangui** [comment]
seek in buffer implemented
