### ISSUE TITLE
Do you think trickplay is possible

### ISSUE THREAD

**Issue by sstankov** [mangui/flashls#121]
Hi guys,

do you thinkm trick play can be done based on HLS with this plugin? (Option to mimic fast-forward and rewind operations analogue to VCRs ?

(example: http://flash.flowplayer.org/plugins/streaming/slowmotion.html here is RTMP and it is dobe by media server, but just thinking if we load here 3 second of chunks can we play it in 1 sec? )

visual feedback given during fast-forward and rewind operations that were provided by analogue systems such as VCRs.

**Comment by mangui** [comment]
Byte range is supported but with some limitation inherent to flash (whole frag is downloaded)
I frame is not supported yet.
There is no specific roadmap to get i frame supported for now

**Comment by mangui** [comment]
no plan to support trick play - I Frame
