### ISSUE TITLE
last frames missing in chromeless player

### ISSUE THREAD

**Issue by Raph8coder** [mangui/flashls#125]
Hi,

   I have some problems using chromeless player : sometimes, the player stops before the end, the last frames at the end (2 to 8) are not displayed.

I saw 2 cases when this happens :
- with default ffmpeg parameters for H264, it only happens if the video is seeked during playback
- with small or no GOPs in H264 parameters, it happens every time (I want to use small gops to limit preroll effect when seeking).

I tried several hacks in HLSNetStream._checkBuffer : 
- change the 0.1 value to 0.0001 to test buffer length
- disable  PLAYBACK_COMPLETE event and Play/Seek states changes 
without effect.

Thanks in advance

Raphael

**Comment by mangui** [comment]
@Raph8coder could you recheck this issue against latest flashls/dev and reopen if still reproducible ?
thanks
