### ISSUE TITLE
Stream switching playback

### ISSUE THREAD

**Issue by hocokbkapmahe** [mangui/flashls#126]
Hello, Mangui !

I'm testing plugin for a couple of month )
All is fine, except one issue.

When stream switching from one level to another, it's looks like plugin/player dropping some frames.
But SMP info show me "dropped frames:0" 
I can't actually explain this, so here is a video

See the 10sec, 20sec, 30sec of video
https://www.youtube.com/watch?v=XzFo3tw_M20&feature=youtu.be

Resolution/Bitrate:
0-10sec = 416x234/600Kbit
10sec-20sec = 640x360/1Mbit
20sec-30sec = 1280x720/3,5Mbit
30sec-32sec = 480x270/600Kbit

Here is actually the stream:
http://m.int10h.com/96/72/6c58b88ec48f3420141024044536/index.m3u8

The stream comes with SAR 1:1; DAR 16:9; Baseline Profile level 3.0 with aac / stereo 44KHz

I've tested this in latest chrome (38.0.2125.111 m)

P.S. In IE 10 this problem does not exist.
I believe the issue associated with PPAPI / NPAPI 
(Because when I set PPAPI in chrome to off, and NPAPI turn to on, the problem doesn't exist, and playback is really smooth, like in IE 10)

Is there problem with plugin or with SMP ?

**Comment by kwarismian** [comment]
I have submitted a Chromium bug report regarding the invalid VideoHeight measurements.  The Hardware Video Decoder apparently is rounding to the nearest multiple of 16 for the image decoding, and passes PAR/crop information back to the Flash Player, but Pepper Flash isn't using this PAR information correctly and erroneously allows the Multiple of 16 videoHeight to make it down to StageVideo.  This is why 720p renders correctly while both 360p and 1080p have an extra 8 pixels added to the VideoHeight.  If you have a chance and are so inclined, please Star the report on their Issues list and maybe someone will look at addressing it in a future Chrome release.

https://code.google.com/p/chromium/issues/detail?can=2&start=0&num=100&q=&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Cr%20Status%20Owner%20Summary%20OS%20Modified&groupby=&sort=&id=512828
