### ISSUE TITLE
flashlsOSMF does not play m3u Manifest

### ISSUE THREAD

**Issue by jlacivita** [mangui/flashls#131]
Play the following URL via flashls:

http://link.theplatform.com/s/LOdVRC/media/tP7j9kx87ylA?manifest=m3u&format=redirect

This simply returns a 302 redirect to an HLS file.

Note that it won't play in mac safari via HTML5, due to an Akamai 3rd party cookie bug, but it does play in other HLS-in-Flash solutions.

I think you just need to detect the 302 redirect, and update your main URL before parsing the rest of the variant m3us.

I'm on Mac Chrome with Flash, and I'm using the OSMF flashls plug-in.

**Comment by iwebker** [comment]
![image](https://cloud.githubusercontent.com/assets/12553867/15984632/8f29b47a-3005-11e6-9b04-b59835ca5a7a.png)
can't play video?why?

**Comment by mangui** [comment]
Because Flash Player has restrictions preventing to access content-Type

**Comment by mangui** [comment]
So it is expecting m3u or m3u8 extension
