### ISSUE TITLE
playback may stop in the middle (frequent repro when stream is accessed for the first time)

### ISSUE THREAD

**Issue by Hiroshi-p** [mangui/flashls#132]
I tried bin\release\flashlsChromeless.swf of 5f81067 with the following stream.
http://panopto-public-scratch.s3.amazonaws.com/22009/good/master.m3u8

Playback stops around 16 seconds time stamp, without any error message.
It simply says onComplete(), playback completed.
It works fine with the current flashls.org test page (i.e. binary as of Oct.24).
So, it looks regression between that point to 5f81067.

**Comment by mangui** [comment]
@Hiroshi-p i cannot repro with latest flashls/dev. I checked several times, but as it was an intermittent issue ... plz reopen the ticket if you can still repro
thanks
Mangui

**Comment by Hiroshi-p** [comment]
@mangui,
Thank you for checking this again.
I tried this scenario with Flash 18.0.0.194.
It turned out that the problem happened with older version of flashls (v0.3.2), but the current version does not get repro.
It looks fixed by some change in between.

**Comment by mangui** [comment]
great, thanks for confirming
