### ISSUE TITLE
Set AES key dynamically

### ISSUE THREAD

**Issue by petkoandris** [mangui/flashls#138]
Hi,

is it possible to set URI to AES key dynamically?
If I have in manifest:
#EXT-X-KEY:METHOD=AES-128,IV=0x******
can I add URI later after load or it has to be set directly in manifest?

Thanks

**Comment by jimmyville** [comment]
I have the same issue using VideoJS. It will play the video happily using HTTP but not when delivering the key via HTTPS. 

HTTPS version plays fine on iOS devices - so it's only the flashls fall-back I need to get working using VideoJS.
