### ISSUE TITLE
support redundant streams

### ISSUE THREAD

**Issue by ysle** [mangui/flashls#14]
HI,

it would be more then welcome to have support for redundant / alternate streams as well :  

refererence : 
https://developer.apple.com/library/ios/documentation/networkinginternet/conceptual/streamingmediaguide/UsingHTTPLiveStreaming/UsingHTTPLiveStreaming.html#//apple_ref/doc/uid/TP40008332-CH102-SW22

**Comment by ysle** [comment]
thanks a lot !!

**Comment by mangui** [comment]
closing as implemented
