### ISSUE TITLE
Adaptative bitrate on video JS

### ISSUE THREAD

**Issue by nums** [mangui/flashls#140]
Hi,

I try to add this feature with video JS but it seems that is not possilbe at this time.
Is it just an UI issue or is it more complexe than that ?

**Comment by cwbeck** [comment]
@mangui is it possible to address this via JS? Is there a way to force playback of a single representation (bitrate version) ? I would like to be able to do selectBitrate(1000) and that will disable auto switching.

Many thanks,


C.

**Comment by flavioribeiro** [comment]
The only way you can control adaptive streaming switches is by using the [JSURLLoader](https://github.com/mangui/flashls/blob/dev/src/org/mangui/hls/utils/JSURLLoader.as) and external interface [callback](https://github.com/mangui/flashls/blob/dev/src/org/mangui/chromeless/ChromelessPlayer.as#L97). You can download video chunks on the JS and take into account the time its taking plus the current bitrate. I [did](https://github.com/bemtv/clappr-p2phls-plugin/blob/master/src/adaptive_streaming.js) this sometime ago but the code is now outdated with the latest versions of flashls.

**Comment by flavioribeiro** [comment]
@cwbeck btw, if you call `playerSmoothSetLevel` it will automatically disable auto switching.

**Comment by cwbeck** [comment]
@flavioribeiro thanks for that extra information :+1: Can you call that from JS though?

**Comment by mangui** [comment]
@cwbeck my fork of videojs-swf has been enriched so that you could select level through an external API
https://github.com/mangui/video-js-swf/blob/master/src/com/videojs/providers/HLSProvider.as#L539-L564
level switch API could be accessed like this : https://github.com/dacast/video-js-swf-quality-menu/blob/master/src/js/menuhd.js#L89-L100

plz also check https://github.com/mangui/video-js-swf/pull/4
and https://github.com/dacast/video-js-swf-quality-menu that might provide what you need.

**Comment by cwbeck** [comment]
@mangui - brilliant, but I worry about future updates to the library in that fork. There is a playback bug (on video restarting with the VideoJS in your fork - I've got an engineer look at that now and I hope we can provide a fix and commit it back. Would it be possible to merge the levels work into the main repo?

**Comment by mangui** [comment]
@cwbeck I doubt the levels work could be merged on the main repo as VideoJS team uses a completely different approach to address adaptive streaming.
but if you have any issue with my videojs fork plz address it in a separate ticket, thanks
Mangui
