### ISSUE TITLE
HLS, audio is late ~ 30-40 sec on live streams - PMT changes are not detected

### ISSUE THREAD

**Issue by sstankov** [mangui/flashls#141]
How to replicate it:

1. Download some broadcast tool like Flash Media Live Encoder (http://www.adobe.com/products/flash-media-encoder.html )

FMS URL: rtmp://cast.webvideocore.net/live
Sream: 6h4t5tdq3ncwgk88o8ww

or as shown on:

![2014-11-14_1836](https://cloud.githubusercontent.com/assets/3425712/5049418/fff4888a-6c2d-11e4-904e-5f25ca8049eb.png)

Keep in mind to set for audio:
* format: mp3;
* channels: stereo;
* simple rate: 44 100 hz;
* bit rate: 96 kbps;

The stream will start on: http://dev.streamingvideoprovider.co.uk/popplayer.php?it=958863&c1=%23c8c8c8&c2=%23a6a6a6&w=720&h=405&p=0&title=Slavi%20stream!&skin=3&auto_hide=1&no_fs=0&fs_mode=2 as HLS stream (the stream will be published on http://player.webvideocore.net/735j5haxmg4k.m3u8)

Open the video player before starting the stream. Start the stream from FMLE and see how the player will start buffering, then show video, but no audio for the first 30-40 sec.  If there is an audio, click on stop (in FMLE) and wait for 30 sec, then hit Start again. The video will start automatically buffer but again will be with no sound untill 30-40 min passes;

Work around:

Start stream, wait first 30-60 sec to pass then start the player and the stream plays ok with the audio and video.

P.S.
I tested the stream to be played ok: http://player.webvideocore.net/735j5haxmg4k.m3u8 with http://osmfhls.kutu.ru/ also with VLC on PC seems to start audio on the first second.

I also tested it here: http://stanislavstankov.com/flashls-master/examples/osmf/StrobeMediaPlayback.html?src=http%3A%2F%2Fplayer.webvideocore.net%2F735j5haxmg4k.m3u8 downloaded from today respiratory.

If I can assist more, please let me know

**Comment by mangui** [comment]
should be fixed since https://github.com/mangui/flashls/commit/36ac8aecbe0d275e90119ebfb9e0063f2ccdd26f
plz reopen if still repro
