### ISSUE TITLE
Out of order ts files - playback possible?

### ISSUE THREAD

**Issue by os6sense** [mangui/flashls#143]
I've a project that I am working on where I want to "loop" a dummy video (i.e. off-air) and replace it with the live stream when the live stream becomes available. My first approach was to generate an m3u8 with a sliding window of 3 ts files, looping back to the stream0000.ts file when the end is reached (incrementing the media-sequence number as each file is removed obviously). 

This seems to cause flashls all sorts of problems presumably because the timestamps jump from (e.g.) 01:20 -> 00:00. I've attempted rencoding and resetting timestamps for each ts fragment but this actually makes the problem worse.

I'll try and put a demo URL up but I wanted to ask first if there is anything intrinsically wrong with this approach - looking through the HLS specs I can't find anything which prohibits this BUT I am wondering if this naive approach is better solved via a different technique...

**Comment by mangui** [comment]
your approach is fine, providing that #EXT-X-DISCONTINUITY is inserted before any timestamp/video discontinuity.
