### ISSUE TITLE
Flowplayer: clip start and duration properties have no effect

### ISSUE THREAD

**Issue by blacktrash** [mangui/flashls#149]
With the `start` and `duration` clip properties one can normally "truncate" (i.e. this is reflected also in the controlbar, and which positions can be seeked to - contrary to seeking onStart for instance) the clip to a desired range (`start` requires a streaming server to function properly), see: http://flash.flowplayer.org/documentation/configuration/clips.html#properties
Both parameters have no effect with flashls: http://flowplayer.blacktrash.org/test/flashls-start.html (start: 30, duration: 20).

See also: https://flowplayer.org/forum/#!/scripting_api:start-time-and-duration-are

**Comment by mangui** [comment]
closing as working as expected
