### ISSUE TITLE
M4A problems in Apple iOS with AIR

### ISSUE THREAD

**Issue by vanarebane** [mangui/flashls#150]
Hi there!

This problem does not occur when the audio is streamed in Android or PC.
It seems to only appear on Apple iOS (7.1.1). Streaming with MP3 works well in iOS. 
Only M4A has problems so far.

The streams starts to load, but there is no further reaction after that.

Here is the stream: http://media.err.ee/viker/mp4:2104941.m4a/playlist.m3u8

There is nothing I captured to the log. Perhaps someone can already foresee what the problem might be or tell me what logs are needed to track down that problem? Or is this problem with Apple not supporting (or even blocking) that format?

Thanks again!

**Comment by mangui** [comment]
closing answered question
