### ISSUE TITLE
Logging statements

### ISSUE THREAD

**Issue by NicolasSiver** [mangui/flashls#153]
I have recommendation, don't create overhead with `if` statements for logging.
Use conditional compilation with full force.

Current example:

    if (fragData.audio_found) {
        null;
        // just to stop the compiler warning
        CONFIG::LOGGING {
            Log.debug("m/M audio PTS:" + fragData.pts_min_audio + "/" + fragData.pts_max_audio);
        }
    }

Good:

    CONFIG::LOGGING {
        if (fragData.audio_found) {
                Log.debug("m/M audio PTS:" + fragData.pts_min_audio + "/" + fragData.pts_max_audio);
        }
    }

From sources, You have many places of such type.
Result: code will be cleaner, performance will be better.

**Comment by mangui** [comment]
handled in https://github.com/mangui/flashls/commit/fb35ebd4737518ca19a5394a9fea665d170a2055 and https://github.com/mangui/flashls/commit/c8fd99b2e8b9b55f059e41c42831b98c20121c3c
