### ISSUE TITLE
Stream play issue

### ISSUE THREAD

**Issue by neoy** [mangui/flashls#154]
When I play a stream for about serveral minutes,the stream stops playing without any error or unormal logs,but the player continue to load some more ts files,(Can see in the chrome network console),after a while maybe 4 or more ts files loaded the stream resumes.And after a few minutes it stops again.
I can make sure it is not filling the empty buffer,as when it stops I seek a little bit it will continue play.
And I never reproduce in the standalone flashplayer,but in chrome it happens all the time.
I've tried but didn't find the reason.
Could you help me.
Thanks.

**Comment by neoy** [comment]
I looked into logs but didn't find any unnormal.
And it reproduce in IE too,so I think there's something worng with the CDN,not the player problem.
Thank you for your help : ).

**Comment by mangui** [comment]
closing as not a flashls issue
