### ISSUE TITLE
flowplayer: playhead doesn't move when controlbar does not autoHide

### ISSUE THREAD

**Issue by blacktrash** [mangui/flashls#159]
Demo: http://flowplayer.blacktrash.org/test/flashls-autoplay.html (using v0.4.0.3).

**Comment by mangui** [comment]
I cannot get any useful info from the Flowplayer debug logs. however the displayed position is correct ?

**Comment by blacktrash** [comment]
For me[tm] the playhead is stuck at the beginning, could just now also repro in Safari. Here's a FF screenshot:
![autoplay-playhead](https://cloud.githubusercontent.com/assets/168338/5887520/06901c28-a3cd-11e4-8e22-e309b05d58f4.jpg)

**Comment by mangui** [comment]
@blacktrash I can reproduce the same, but as you can see the media position is displayed correctly on the right side of the scrub bar. and the media position returned by flashls seems correct. this issue might be a side effect of something not handled properly by flashls, but this would mean debugging Flowplayer scrub bar logic, which I am not familiar with.

**Comment by blacktrash** [comment]
@mangui - I found a (very dirty) workaround until we get to the bottom of this. In the clip configuration:
```js
clip: {
  onStart: function () {
    this.resume();
  }
}
```

**Comment by blacktrash** [comment]
This is actually not related to autoPlay, but to whether the controlbar autoHides or not: http://flowplayer.blacktrash.org/test/flashls-autoplay.html (dev 9c23170 hls_debug enabled)

If one hovers over the player here http://flowplayer.blacktrash.org/test/flashls.html longer after clicking play, the playhead does not move either. Only once the controlbar was hidden for the first time.

**Comment by blacktrash** [comment]
Similar symptoms with the audio plugin, albeit not right from the start: https://github.com/flowplayer/flash/issues/276

**Comment by blacktrash** [comment]
Looks like a regression in Flowplayer core 3.2.18 - works after downgrading to 3.2.17.

**Comment by mangui** [comment]
closing, as FlowPlayer issue
