### ISSUE TITLE
Flowplayer: support clip.fullDuration

### ISSUE THREAD

**Issue by zemen77** [mangui/flashls#160]
hi there,

no way to get clip metadatas. (ref. http://flash.flowplayer.org/documentation/api/clip.html#properties)
My need is to get clip's full duration updated during live playlist reload task.

clip.duration is being updated just onresume event.
clip.fullDuration is undefined.

Any hint?

thanks

**Comment by mangui** [comment]
Strange, clip.duration should always be up to date. Even with live playlist. Which kind of playlist are you using ?

**Comment by zemen77** [comment]
it's a standard m3u8 playlist with no #EXT-X-ENDLIST tag at the end.
Here an example:
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-ALLOW-CACHE:YES
#EXT-X-TARGETDURATION:10
#EXTINF:10.16000,
CVE_0.ts
#EXTINF:10.08000,
CVE_1.ts
....

**Comment by mangui** [comment]
I guess I would have to fire a ClipEventType.UPDATE event from flashlsFlowplayer in case duration gets updated, to force updated duration to be copied from Flash to JS,@blacktrash might confirm ?

**Comment by blacktrash** [comment]
Both `clip.duration` and `clip.fullDuration` are `undefined` for "normal" live streams (RTMP, Adobe HTTP Streaming.
By lack of an example (could be looked up in the source) I'm not sure how the behaviour with DVR live is, and whether the recorded DVR "duration" is passed as `clip.duration` to the API. I'm also not sure whether it makes sense to mimic DVR. Maybe it would make more sense for flashls to provide and propagate a `hlsLiveWindowDuration` clip property to the API.

**Comment by zemen77** [comment]
It make sense to provide clip.duration value couse flashls is an hybrid kind of stream... I mean you get new contents as regular live stream but you can seek your content as well as a VOD stream do.

Would be great to get triggered a special event on stream finish too to JS.

Thanks for your great great work :)
