### ISSUE TITLE
flowplayer + flashls plugin + android 2.x

### ISSUE THREAD

**Issue by remizovvv** [mangui/flashls#165]
Hello! I have a problem with using this combination.
Link: http://sherton.r60939.msk3.dp10.ru/oldflow/flash-latest-sw-btr-video.html
In Android 2.x flowplayer reported "301: Unable to load plugin: Unable to load plugin 'httpstreaming', url: 'flw/flashlsflowplayer-3.2.12.3.swf'

In other systems this combination works  correctly.

**Comment by mangui** [comment]
For Android/Flash support this needs to be checked with Flowplayer team

**Comment by blacktrash** [comment]
@remizovvv,
http://sherton.r60939.msk3.dp10.ru/oldflow/flash-latest-sw-btr-video.html does not load for me.
But does it happen at http://flash.flowplayer.org/plugins/streaming/flashls.html as well?

**Comment by remizovvv** [comment]
Hello! @blacktrash, I have this problem on your link, too :( "301: Unable to load plugin: Unable to load plugin 'httpstreaming', url: 'media/swf/flashlsFlowPlayer-0.3.4.swf'

**Comment by blacktrash** [comment]
@remizovvv - does the Android have Flash installed? Otherwise it will not work because the ipad plugin by default only supports iOS. You could then try:
```js
flowplayer("playerContainer", {
  // player configuration goes here
}).ipad({simulateiDevice: !flashembed.isSupported([10, 1]) && /android/i.test(navigator.userAgent)});
```
but that is not officially supported.
If the device has Flash installed, it might be an issue with Flash on the respective Android, often broken. Then your best bet is to wait until the next version of Flowplayer HTML5 (ETA: a few weeks) which will support HLS also in the Flash engine.

**Comment by remizovvv** [comment]
@blacktrash, Android (v 2.x) have Flash installed. And flowplayer can play mp3 files (with audio plugin) and mp4 (with pseudostreming plugin). But it show error with flashls plugin :(

.ipad(---); - 
sorry, but it dont help. Error 301.

I know that html5  is better than flash. But android 2.x dont support html, only flash (for example android 4.x support only html5 and dont support flash).

**Comment by blacktrash** [comment]
As I said, Android Flash implementations are often broken. So some, if not all, setups might now work.

**Comment by remizovvv** [comment]
Understandable, but strangely that it doesn't work only with flashls
