### ISSUE TITLE
onError

### ISSUE THREAD

**Issue by istarbuxs** [mangui/flashls#166]
Hi,

your plugin works great. why is onError not being triggered when the m3u8 file is not working?

thanks

**Comment by istarbuxs** [comment]
Hi! I am using flowplayer, whenever I trigger an m3u8 file with token and the token is not valid, the onError handler does not fire.

**Comment by mangui** [comment]
There is no token definition in HLS, i imagine that this token is a way to protect your playlist but i dont know how your system works. You need to be more specific and explain a little bit more about your token system. Are you using AES and protecting the key Url ? Or are you protecting fragment access ? Or playlist ? 
Then also a debug log would help
