### ISSUE TITLE
No video after PTS (DTS) > 32 bit (?)

### ISSUE THREAD

**Issue by oleg-umnik** [mangui/flashls#168]
See here: http://video.progtech.ru/example/

bad.ts is not playing using video.js SWF plugin with HLS support. good.ts file is OK. The only difference is that PTS/DTS values in bad.ts file is bigger than 4294967295. But I'm not sure if this a root cause.

Yes, both files are playing fine using VLC.

**Comment by mangui** [comment]
Will check this soon

**Comment by mangui** [comment]
Hi @oleg-umnik i was going to check your issue but your link seems broken. have you made any progress on it ?

**Comment by mangui** [comment]
plz reopen if issue still reproducible
