### ISSUE TITLE
Failover 

### ISSUE THREAD

**Issue by zWaR** [mangui/flashls#170]
Hi!

Does flashls support failover between a primary and backup stream?

Thanks!

**Comment by mangui** [comment]
Not supported for now, might come sooner or later

**Comment by hangulee** [comment]
First, thanks for your nice plugin, mangui!
As far as i know there is no standard for this in HLS spec. But i think that it can be done as follow:
If there are URLs that has same BANDWIDTH value and same RESOLUTION in meta playlist file then first appeared child URL is a primary and second appeared child URL is a backup. What do you think?

**Comment by ysle** [comment]
Hi,

seems like it's related to this one too: https://github.com/mangui/flashls/issues/14
so looks like there is a standard approach for this.

**Comment by mangui** [comment]
closing as duplicate with #14
