### ISSUE TITLE
chromeless implementation for OOP javascript

### ISSUE THREAD

**Issue by paztis** [mangui/flashls#171]
Is it possible to propose another chromeless implementation for Oriented Object Javascript ?

In Javascript, it's not clean to call root methods like onHLSReady or onPosition.
More, if 2 instances of Flashls are present in the same page, there's no way to know which one call the method. The embeded instance id may be better in parameter.

It is better to manage a js object like this:
var flashls = {
  onHLSReady: function(instanceId, message) {
    ...
  },

  onComplete: function(instanceId, message) {
  },

  ...
}

The instanceId parameter is tje id of the flashls emitter.
In flash, the only think to change is 
ExternalInterface.call("flashls.onHLSReady", ExternalInterface.objectID);
instead of 
ExternalInterface.call("onHLSReady", ExternalInterface.objectID);
and to add ExternalInterface.objectID to all methods.

**Comment by mangui** [comment]
@paztis PR welcomed

**Comment by paztis** [comment]
I'm ok to PR, but I haven't got anything to compile it.

**Comment by mangui** [comment]
Apache Flex/Air sdk is available on Linux/OS X/Win32
This should be the only dependency needed to compile flashls

**Comment by paztis** [comment]
What version of flex / flash player do you use ?
I've see flex 4.6 and player 10.1 and 11.1 in build script
In my flex installer I'm limited to flex 4.9.1 and player 10.2.

**Comment by mangui** [comment]
Adobe flex 4.6 / apache flex / air sdk ... all should work.
For the player version, please refer to build.sh, you should find it from here.

**Comment by paztis** [comment]
Hi
I've create a PR (#174).
I've keep the same chromeless implementation and add and url parameter to choose the js event mode.
If no url parameter is passed, standard event mode is kept.

**Comment by mangui** [comment]
implemented, closing
