### ISSUE TITLE
Iphone problem

### ISSUE THREAD

**Issue by campones** [mangui/flashls#173]
Hello,

While checking the nginx access, I noticed iphone receive a 404 not found such as

xxx-ip-client-xxx - - [06/Jan/2015:00:13:54 +0100] "GET /keys/tf1-16819.key HTTP/1.1" 404 168 "http://www.website/stream" "Mozilla/5.0 (iPhone; CPU iPhone OS 8_1_2 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Mobile/12B440"

while it seems to work fine for iPad which I d believe is kinda of the same. 

"GET /hls/streamname.m3u8 HTTP/1.1" 200 280 "-" "Mozilla/5.0 (iPad; CPU OS 6_0 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) Version/6.0 Mobile/10A5376e Safari/8536.25"

I dont have any specific settings to block those UA.. so I am wondering if this could be related to the custom videojs-swf or not

Also and this is off topic, but the custom swf doesn't work with last videojs.js (4.11.2 i believe) , rtmp won't work.

**Comment by mangui** [comment]
Hi, i am not clear about the relation between iphone and flashls. I understand that you are using videojs but on iphone it should not use videojs-swf / flashls ?

**Comment by campones** [comment]
Slt 

Yes indeed I m using your custom video flash, I think it s supposed to work as html5 on iOS device.  
oh so it would mean that this isn't related to the flash player 

I might be posting in the wrong forum then.
