### ISSUE TITLE
Playback freezes 

### ISSUE THREAD

**Issue by stevemayhew** [mangui/flashls#176]
Hi mangui!
Glad you carried on after the licensing issues. We are most interested in the mediaelement shiv player.

This very short sample (AES encrpyted) is freezing on the chromeless test player on latest Chrome browser (Version 39.0.2171.95 (64-bit)) with the internal Chrome flash player.
  http://flashls-test.s3.amazonaws.com/7_copy.m3u8
 
Note you'll need my fix from: https://github.com/mangui/flashls/pull/175
In order to get it to play at all.

Looks like it is having trouble with the third fragment:

 DEBUG:custom tag:#EXTINF:2,
 onFragmentPlaying(): metrics:1 sn:1 cc:0 video_width:1280 video_height:540 tags:#EXTINF:2,
(26) DEBUG:AVC: AUD, SEI, SEI, SEI, NDR slices
DEBUG:[PLAYBACK_STATE] from PLAYING to PLAYING_BUFFERING
(80) DEBUG:AVC: AUD, SEI, SEI, SEI, NDR slices
DEBUG:playing fragment(level/sn/cc):1/2/0
DEBUG:custom tag:#EXTINF:2,
onFragmentPlaying(): metrics:1 sn:2 cc:0 video_width:1280 video_height:540 tags:#EXTINF:2,
(1270) DEBUG:AVC: AUD, SEI, SEI, SEI, NDR slices

It's stuck there for quite a while, then prints:
 DEBUG:25944 tags extracted
 DEBUG:Loaded position/duration/sliding/discontinuity:4.67/0.06/0.10/false
 DEBUG:AutoBufferManager:minBufferLength:60

Video stops last position report is 4.61.

Let me know if I can help with anything else.  It does play in Safari.

**Comment by mangui** [comment]
i checked your stream, what i dont like is the following log:
"WARN:TS: late PMT found, rewinding at beginning of TS" chromeless
when this warning msg is triggered with encrypted streams, it can mean that IV is incorrect.
when IV is incorrect, the first 16 bytes of each decrypted fragment will be invalid. in return this can trigger video decoding issue ...
I checked with Adobe Scout and flash VM is stuck in parsing TS packets.

**Comment by stevemayhew** [comment]
There is no IV specified in the EXT-X-KEY.

Thanks for you response!  And for merging my pull request.
 
The stream is encrypted using the segment number as the IV as in the spec: 

>"If an EXT-X-KEY tag with a KEYFORMAT of "identity" does not have the
>  IV attribute, implementations MUST use the sequence number of the
>   media segment as the IV when encrypting or decrypting that media
>   segment.  The big-endian binary representation of the sequence number
>   SHALL be placed in a 16-octet buffer and padded (on the left) with
>  zeros."

The stream does play in OSMF HLS Plugin and in Safari on OS X.

I don't have the Adobe Scout, but if you can tell me which TS segment it thinks is bad I can decrypt and analyze it with an MPEGTS Packet analyzer.

More then happy to help you get to the bottom of this.

**Comment by mangui** [comment]
this stream is now playing with latest release
