### ISSUE TITLE
How is the pause/seek processed

### ISSUE THREAD

**Issue by balderys** [mangui/flashls#177]
Hi Mangui,
we have experienced behaviour that after continuing of playback after longer pause in DVR window the playback jump to different position after first playlist refresh. My explanation is following:

 - first segment is probably used from buffer
 - playlist is refreshed so the start of DVR window is changed
 - plugin tries to seek to original position but it is completely another position

Please correct me if I'm wrong. But if I'm correct, is tag "EXT-X-MEDIA-SEQUENCE" taken into account? If the normal seek works and plugin continues at segment with next sequence number, it will also work after pause in my opinion.

Thank you.

**Comment by mangui** [comment]
Playback will restart from buffer after long pause. However if pause duration is greater than max buffer size, flashls wilk detect this and perform a seek(-1) in the live playlist that should seek 3 frag before the end.
If pause duration is less it should work fine. Is that what u observe ?

**Comment by balderys** [comment]
Yes, it is exactly that. Would it be possible to continue from segment with next sequence number after buffer is empty if such number exists in the playlist?

**Comment by mangui** [comment]
This should already be the case, the seek only happens if next SN is not in live window anymore. if not plz send debug logs

**Comment by Obr007** [comment]
Hi,
the same behaviour is when playing (DVR) with high quality (level 1 for example) and flashls change playback to lower bitrate (level 0 for example). Video freezes, audio is playing in the background but it starts from some older time. When audio in the background reaches the time, when video freezed, video continues playback in lower quality. 

My explanation is:  

1) buffer is filled with high quality video
2) player switch to lower quality and loads new segments in lower quality
3) when playback reach new segment from buffer in low quality, this segment has different timestamp, so plugin cannot continue in playback

I dont see any errors in logs, here is Debug1 log (playing in level 1, then switched to level 0):

DEBUG:AVC: H264 Baseline level 21" CTPlayerLoader.html
"DEBUG:Loaded position/duration/sliding/discontinuity:5442.96/0.42/15.02/false" CTPlayerLoader.html
"DEBUG:AutoBufferManager:minBufferLength:6.170824337565814" CTPlayerLoader.html
"DEBUG:Loaded position/duration/sliding/discontinuity:5443.37/0.05/15.02/false" CTPlayerLoader.html
"DEBUG:AutoBufferManager:minBufferLength:6.393950462576754" CTPlayerLoader.html
"DEBUG:Loaded position/duration/sliding/discontinuity:5443.42/0.33/15.02/false" CTPlayerLoader.html
"DEBUG:AutoBufferManager:minBufferLength:6.218853943495819" CTPlayerLoader.html
"DEBUG:Loaded position/duration/sliding/discontinuity:5443.74/0.05/15.02/false" CTPlayerLoader.html
"DEBUG:AutoBufferManager:minBufferLength:6.448494397718972" CTPlayerLoader.html
"DEBUG:AVC: H264 Baseline level 21" CTPlayerLoader.html
"DEBUG:Loaded position/duration/sliding/discontinuity:5443.79/0.28/15.02/false" CTPlayerLoader.html
"DEBUG:AutoBufferManager:minBufferLength:6.697897529753504" CTPlayerLoader.html
"DEBUG:playing fragment(level/sn/cc):0/142139560/0" CTPlayerLoader.html
"DEBUG:custom tag:#EXTINF:10," CTPlayerLoader.html
"DEBUG:Loaded position/duration/sliding/discontinuity:5444.07/0.60/15.02/false" CTPlayerLoader.html
"DEBUG:AutoBufferManager:minBufferLength:6.365868130745013" CTPlayerLoader.html
"DEBUG:Loaded position/duration/sliding/discontinuity:5444.67/0.28/15.02/false" CTPlayerLoader.html
"DEBUG:AutoBufferManager:minBufferLength:6.253502114391843" CTPlayerLoader.html
"DEBUG:Loaded position/duration/sliding/discontinuity:5444.95/0.05/15.02/false" CTPlayerLoader.html
"DEBUG:AutoBufferManager:minBufferLength:6.457598784035471" CTPlayerLoader.html
"DEBUG:level 0 playlist:
#EXTM3U
#EXT-X-VERSION:2
#EXT-X-TARGETDURATION:10
#EXT-X-MEDIA-SEQUENCE:142139017
#EXT-X-PROGRAM-DATE-TIME:2015-01-16T06:36:10Z
#EXTINF:10,
http://80.188.78.184:80/atip/4bfad5f12b62e34259a4b733bbd9ed6f/1421401005941/0/1502/220-2402-5128-1188/1.k.ts
#EXTINF:10,
http://80.188.78.184:80/atip/8c089cca2ad41fac6b421fd89337c528/1421401005941/0/1502/220-2402-5128-1189/0.k.ts
#EXTINF:10,
http://80.188.78.184:80/atip/854d993e06bf3e905f689390e33d9c5c/1421401005941/0/1502/220-2402-5128-1189/1.k.ts
#EXTINF:10,
http://80.188.78.184:80/atip/d54a3c4de257a63fb08019f37fa42f84/1421401005941/0/1502/220-2402-5128-1190/0.k.ts
#EXTINF:10,
http://80.188.78.184:80/atip/2392ea8ffb574304dbe796a17f1bfc34/1421401005941/0/1502/220-2402-5128-1190/1.k.ts
#EXTINF:10,
http://80.188.78.184:80/atip/b3830ef3ccdf84272d82cdcb7328d0e4/1421401005941/0/1502/220-2402-5128-1191/0.k.ts
#EXTINF:10,
http://80.188.78.184:80/atip/72146c04915f72ae936aa0635ca2a0d7/1421401005941/0/1502/220-2402-5128-1191/1.k.ts
#"[…] CTPlayerLoader.html
"DEBUG:updateFragments: found PTS info from previous playlist,seqnum/PTS:142139559/39654330" CTPlayerLoader.html
"DEBUG:Level 0 Live Playlist parsing finished: reload in 8963 ms" CTPlayerLoader.html
"DEBUG:AVC: H264 Baseline level 21" CTPlayerLoader.html
"DEBUG:Loaded position/duration/sliding/discontinuity:5445.00/0.05/15.02/false" CTPlayerLoader.html
"DEBUG:AutoBufferManager:minBufferLength:7.405984199306209" CTPlayerLoader.html
"DEBUG:AVC: H264 Baseline level 21" CTPlayerLoader.html
"DEBUG:Loaded position/duration/sliding/discontinuity:5445.05/1.02/15.02/false" CTPlayerLoader.html
"DEBUG:AutoBufferManager:minBufferLength:6.5322959563875465" CTPlayerLoader.html
"DEBUG:Loaded position/duration/sliding/discontinuity:5446.07/0.93/15.02/false" CTPlayerLoader.html
"DEBUG:AutoBufferManager:minBufferLength:6.286460766661055" CTPlayerLoader.html
"DEBUG:resume playback" CTPlayerLoader.html
"DEBUG:[PLAYBACK_STATE] from PLAYING_BUFFERING to PLAYING" CTPlayerLoader.html
"[10:37:25] switching state to PLAYING" CTPlayerLoader.html:248
"DEBUG:AVC: H264 Baseline level 21" CTPlayerLoader.html
"DEBUG:Loaded position/duration/sliding/discontinuity:5447.00/0.05/15.02/false" CTPlayerLoader.html
"DEBUG:AutoBufferManager:minBufferLength:6.5608200580816" CTPlayerLoader.html
"DEBUG:Loaded position/duration/sliding/discontinuity:5447.04/0.97/15.02/false" CTPlayerLoader.html
"DEBUG:AutoBufferManager:minBufferLength:6.031506951765814" CTPlayerLoader.html
"DEBUG:AVC: H264 Baseline level 21" CTPlayerLoader.html
"DEBUG:Loaded position/duration/sliding/discontinuity:5448.02/0.05/15.02/false" CTPlayerLoader.html
"DEBUG:AutoBufferManager:minBufferLength:6.357000805743491" CTPlayerLoader.html
"DEBUG:Loaded position/duration/sliding/discontinuity:5448.06/0.42/15.02/false" CTPlayerLoader.html
"DEBUG:AutoBufferManager:minBufferLength:6.201021363726193" CTPlayerLoader.html
"DEBUG:Loaded position/duration/sliding/discontinuity:5448.48/0.05/15.02/false" CTPlayerLoader.html
"DEBUG:AutoBufferManager:minBufferLength:6.30652548310842" CTPlayerLoader.html
"DEBUG:Loaded position/duration/sliding/discontinuity:5448.53/0.23/15.02/false" CTPlayerLoader.html
"DEBUG:AutoBufferManager:minBufferLength:6.253909788165251" CTPlayerLoader.html
"DEBUG:Loaded position/duration/sliding/discontinuity:5448.76/0.05/15.02/false" CTPlayerLoader.html
"DEBUG:AutoBufferManager:minBufferLength:6.269803888314273" CTPlayerLoader.html
"DEBUG:loading completed" CTPlayerLoader.html
"DEBUG:Loading       duration/RTT/length/speed:5807/243/885480/1191 kb/s" CTPlayerLoader.html
"DEBUG:Loaded position/duration/sliding/discontinuity:5448.81/0.09/15.02/false" CTPlayerLoader.html
"DEBUG:AutoBufferManager:minBufferLength:6.26214950554783" CTPlayerLoader.html
"DEBUG:TS: flushing demux" CTPlayerLoader.html
"DEBUG:TS: partial AVC PES at end of segment" CTPlayerLoader.html
"DEBUG:Loaded position/duration/sliding/discontinuity:5448.90/0.05/15.02/false" CTPlayerLoader.html
"DEBUG:AutoBufferManager:minBufferLength:6.234317303734649" CTPlayerLoader.html
"DEBUG:TS: parsing complete" CTPlayerLoader.html
"DEBUG:m/M audio PTS:39663340/39673301" CTPlayerLoader.html
"DEBUG:m/M video PTS:39663218/39673178" CTPlayerLoader.html
"DEBUG:Delta audio/video m/M PTS:-122/-123" CTPlayerLoader.html
"DEBUG:Total Process duration/length/bw:5822/885480/1188 kb/s" CTPlayerLoader.html
"DEBUG:Loaded        142139560 of [142139017,142140096],level 0 m/M PTS:39663340/39673301" CTPlayerLoader.html
"DEBUG:AutoBufferManager:minBufferLength:5.9435959787043275" CTPlayerLoader.html
"DEBUG:loadnextfragment()" CTPlayerLoader.html
"DEBUG:Loading       142139561 of [142139017,142140096],level 0" CTPlayerLoader.html
"DEBUG:loading fragment:http://80.188.78.184:80/atip/3f97e7a8b66fffd9293da96e1574c093/1421401005941/0/1502/220-2402-5128-

1460/1.k.ts" CTPlayerLoader.html
"DEBUG:AVC: width/height:512/288" CTPlayerLoader.html
"DEBUG:AVC: H264 Baseline level 21" CTPlayerLoader.html
"DEBUG:Loaded position/duration/sliding/discontinuity:5438.97/0.07/24.99/false" CTPlayerLoader.html
"DEBUG:AutoBufferManager:minBufferLength:60" CTPlayerLoader.html
"DEBUG:Loaded position/duration/sliding/discontinuity:5439.04/0.79/25.02/false" CTPlayerLoader.html
"DEBUG:AutoBufferManager:minBufferLength:7.165811559620896" CTPlayerLoader.html
"DEBUG:Loaded position/duration/sliding/discontinuity:5439.83/0.05/25.02/false" CTPlayerLoader.html
"DEBUG:AutoBufferManager:minBufferLength:8.212247751307162" CTPlayerLoader.html
"DEBUG:AVC: H264 Baseline level 21" CTPlayerLoader.html
"DEBUG:Loaded position/duration/sliding/discontinuity:5439.88/0.18/25.02/false" CTPlayerLoader.html
"DEBUG:AutoBufferManager:minBufferLength:8.766317277880127" CTPlayerLoader.html
"DEBUG:Loaded position/duration/sliding/discontinuity:5440.06/0.05/25.02/false" CTPlayerLoader.html
"DEBUG:AutoBufferManager:minBufferLength:9.718113550931259" CTPlayerLoader.html
"DEBUG:Loaded position/duration/sliding/discontinuity:5440.11/0.42/25.02/false" CTPlayerLoader.html
"DEBUG:AutoBufferManager:minBufferLength:8.383700371023215" CTPlayerLoader.html
"DEBUG:Loaded position/duration/sliding/discontinuity:5440.53/0.51/25.02/false" CTPlayerLoader.html
"DEBUG:AutoBufferManager:minBufferLength:7.943821775240883" CTPlayerLoader.html
"DEBUG:AVC: H264 Baseline level 21"

**Comment by balderys** [comment]
It seems the problem is in EXT-X-PROGRAM-DATE-TIME tag which is not accurate after playlist refresh (there can be few seconds inaccuracy). Is it possible to somehow tell plugin to ignore this tag and use only segment numbers?
Additionally, live stream is working correctly.

Streams for testing:

Stream with DVR window 
http://80.188.65.18:80/cdn/uri/get/?contentType=timeshift&expiry=1424020322&id=2402&playerType=flash&quality=web&region=1&skipIpAddressCheck=true&userId=0&token=741f61185c0b9e2ad4e4e4485d1d41da6a99cd5e

Live stream
http://80.188.65.18:80/cdn/uri/get/?contentType=live&expiry=1424020322&id=2402&playerType=flash&quality=web&region=1&skipIpAddressCheck=true&userId=0&token=257ef245b6f53059eb9daaec600a5f7bd0063072

**Comment by balderys** [comment]
or fix the bad behaviour with freezing of stream ....

**Comment by mangui** [comment]
Hi @balderys 
if EXT-X-PROGRAM-DATE-TIME is found it will be used to synchronize playlists when switching level and find the correct next fragment to load.
if this value is there but not accurate accross playlists ... it might indeed introduce some glitches and pause during the level switch as flashls might dl the wrong fragment. 
if you cant fix this value, you'd better remove it and see if this is really the root cause of your issue.
if you cant remove it easily you can quickly comment those lines and recheck
https://github.com/mangui/flashls/blob/altaudio/src/org/mangui/hls/playlist/Manifest.as#L229-L247

and btw, sequence number are not guaranted to be consistent ...
