### ISSUE TITLE
[OSMF] Keeping the image from the played frame after stopping the stream

### ISSUE THREAD

**Issue by viktorot** [mangui/flashls#180]
Hello.

I wonder if there is any way to keep the image from the last played frame after stopping the stream. The image stays when the stream is paused, but the problem is that I have a live stream and would like to completely stop it (to get rid of the back buffering).

The only way I managed to get something working is by getting the PlayTrait and calling the stop function on it. But that only works in FF on Windows.

Is there any solution or a workaround?

P.S. I'm using the OSMF plugin in a custom player. I tried looking at the StrobeMediaPlayer source without any luck.

Best regards,
Viktor

**Comment by mangui** [comment]
Not sure but I would guess the video is cleared by OSMF itself, neither flashls (nor flashlsOSMF?) is doing it

**Comment by mangui** [comment]
closing as feedback provided
