### ISSUE TITLE
seeking then resuming is a noop

### ISSUE THREAD

**Issue by sylvaingi** [mangui/flashls#181]
Hi mangui,

I haven't been able to make the chromeless player start the playback from a specific offset when it is in the IDLE state. Whenever I seek then play, it starts from the beginning. And seeking then resuming does nothing.

Is there a way to achieve that?

**Comment by mangui** [comment]
hls.stream.play(null,offset) should do the trick

**Comment by mangui** [comment]
Hi @sylvaingi 
does it answer your question ?
if yes please close the ticket, thx
