### ISSUE TITLE
sync byte not found

### ISSUE THREAD

**Issue by DomrachevIvan** [mangui/flashls#183]
url
http://dev.meles.ru/t/hls10/t.m3u8
freezes on second 33, but ios player plays well.
also lib http://osmfhls.kutu.ru/ plays well too.
got debug:
Error: TS: Could not parse file: sync byte not found @ offset/len 236693/366146
	at org.mangui.hls.demux::TSDemuxer/_parseTSPacket()
	at org.mangui.hls.demux::TSDemuxer/_parseTimer()

**Comment by mangui** [comment]
@DomrachevIvan indeed I can reproduce
I am quite busy these days but definitely I will look into it.

**Comment by DomrachevIvan** [comment]
Sorry. it's looks like that problem is in nginx-hls-module that I use for hls generation.
sometimes it makes broken .ts files. but I got a solution for them:
https://github.com/rounce/nginx-hls-module/issues/15
you can close this ticket. thank you.

**Comment by mangui** [comment]
the other option would be to increase the TS start delimiter probe window, here
https://github.com/mangui/flashls/blob/dev/src/org/mangui/hls/demux/TSDemuxer.as#L78
currently it is set to 2*188. in your case it looks like there were no TS start delimiter during more than that ...
