### ISSUE TITLE
playback issues for Baseline video encoder profile

### ISSUE THREAD

**Issue by smpbo** [mangui/flashls#186]
i've met an issue which might be a bug. sometimes there is no audio or video when video encoder profile is Baseline@L3.1 -- probably caused by something during TS Demuxer -- i've tried other HLS library-based OSMF and it works. 

Here is a sample URL: 
http://223.223.182.32/chinaAuto/600/1421743950000,1421744050000.m3u8

**Comment by blacktrash** [comment]
Hm, that stream doesn't seem to be very clean, I get tons of warnings e.g. from ffplay:

```sh
$ ffplay 'http://223.223.182.32/chinaAuto/600/1421743950000,1421744050000.m3u8'
#[...]
[http @ 0x7fa7b301f800] Invalid cookie found, no value, path or domain specified
Input #0, hls,applehttp, from 'http://223.223.182.32/chinaAuto/600/1421743950000,1421744050000.m3u8':
  Duration: 00:01:44.00, start: 8888.700000, bitrate: N/A
  Program 0
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp, 56 kb/s
[NULL @ 0x7fa7b2049c00] non-existing PPS 0 referenced
[hls,applehttp @ 0x7fa7b2010a00] Invalid stream index 1
[NULL @ 0x7fa7b2049c00] non-existing PPS 0 referenced
[hls,applehttp @ 0x7fa7b2010a00] Invalid stream index 1
# [...]
[hls,applehttp @ 0x7fdb1c817a00] Failed to open segment of playlist 0
# [ and so forth ]
```

**Comment by smpbo** [comment]
Thank you for your reply.

this HLS is from FMLE. maybe it is a bit away from the standard in ffplay but it works with IOS as well as AS3 library of at.matthew.httpstreaming and org.denivip.osmf.

my concern is that is it possible that this issue could be compatibility related.

thx again.
