### ISSUE TITLE
Recover when internet is down

### ISSUE THREAD

**Issue by lzanol** [mangui/flashls#187]
Hi Mangui,

If internet goes down, HLSEvent.ERROR event got dispatched and once it happens, HLS cannot play anymore (even seeking).

Is it possible to reload/recover it?

Thanks in advance,
Leandro

**Comment by mangui** [comment]
Hi @lzanol there are some recovery mechanism available already (enabled by default)
please refer to hls_fragmentloadmaxretry, hls_keyloadmaxretry, hls_manifestloadmaxretry settings params.

if not working as expected, a debug log would help,
cheers,
Mangui

**Comment by lzanol** [comment]
Thank you for the reply!

I'll be checking it.

Best regards,
Zanol
