### ISSUE TITLE
Does plugin support clipStartTime and clipEndTime?

### ISSUE THREAD

**Issue by lerivin** [mangui/flashls#188]
On StreamingURLResource does the plugin support defining a clip start and end time. My testing so far is not working.

**Comment by kalimba** [comment]
It would be nice, but flashhls dosn't support subclipping feature of OSMF. There is an issue at [here](https://github.com/mangui/flashls/issues/9) .

**Comment by mangui** [comment]
closing as duplicate of https://github.com/mangui/flashls/issues/9
