### ISSUE TITLE
flashlsFlowPlayer does not play 302 redirect to an HLS file

### ISSUE THREAD

**Issue by carlosjpr** [mangui/flashls#189]
Hello,

Please, play the following URL via flashls:
http://167.114.116.59:1935/redirect/vod/mp4:sample.mp4?scheme=m3u8

This returns a 302 redirect to an HLS file. I can play in mac safari via HTML5 properly. But don't work with flashlsFlowPlayer.

**Comment by kalimba** [comment]
@carlosjpr, It also doesn't work at http://osmfhls.kutu.ru/

**Comment by mangui** [comment]
the redirect URL is http://167.114.116.59:1935/redirect/vod/chunklist_w875894053.m3u8
and it returns a 404 not found
