### ISSUE TITLE
PKCS#5:unpad: Invalid padding value. expected [24], found [108]

### ISSUE THREAD

**Issue by sstankov** [mangui/flashls#190]
```actionscript
Error: PKCS#5:unpad: Invalid padding value. expected [24], found [108]
	at org.mangui.hls.utils::AES/unpad()
	at org.mangui.hls.utils::AES/_decryptChunk()
	at org.mangui.hls.utils::AES/_decryptTimer()
```

file: http://cast1u.webvideocore.net/aes3ios_3pa565436f2q5md5trc06aobep7gotff3t27mknsn2l7in136t9qm2e285m8rkbgqihl546nfhfjut3dp70qo4s4j9iagjfn7g3qt88/vod/vod/517771200_200.mp4/index.m3u8

the content is:

```
#EXTM3U
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-KEY:METHOD=AES-128,URI="http://cast1u.webvideocore.net/aes3ios_3pa565436f2q5md5trc06aobep7gotff3t27mknsn2l7in136t9qm2e285m8rkbgqihl546nfhfjut3dp70qo4s4j9iagjfn7g3qt88/play.key",IV=0x00000000000000000000000000000000
#EXT-X-TARGETDURATION:4
#EXT-X-ALLOW-CACHE:YES
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-VERSION:3
#EXTINF:3.09,
hls/segment1.ts
#EXTINF:3.13,
hls/segment2.ts
#EXTINF:3.88,
hls/segment3.ts
#EXTINF:3.42,
hls/segment4.ts
#EXTINF:3.00,
hls/segment5.ts
#EXTINF:3.04,
hls/segment6.ts
#EXTINF:3.17,
hls/segment7.ts
#EXTINF:3.13,
hls/segment8.ts
#EXTINF:3.92,
hls/segment9.ts
#EXTINF:4.00,
hls/segment10.ts
#EXTINF:3.34,
hls/segment11.ts
#EXTINF:3.42,
hls/segment12.ts
#EXTINF:3.80,
hls/segment13.ts
#EXTINF:3.59,
hls/segment14.ts
#EXTINF:3.59,
hls/segment15.ts
#EXTINF:3.63,
hls/segment16.ts
#EXTINF:3.38,
hls/segment17.ts
#EXTINF:3.21,
hls/segment18.ts
#EXTINF:3.13,
hls/segment19.ts
#EXTINF:3.00,
hls/segment20.ts
#EXTINF:3.13,
hls/segment21.ts
#EXTINF:3.13,
hls/segment22.ts
#EXTINF:3.88,
hls/segment23.ts
#EXTINF:3.34,
hls/segment24.ts
#EXTINF:3.55,
hls/segment25.ts
#EXTINF:3.67,
hls/segment26.ts
#EXTINF:3.42,
hls/segment27.ts
#EXTINF:3.13,
hls/segment28.ts
#EXTINF:3.84,
hls/segment29.ts
#EXTINF:3.50,
hls/segment30.ts
#EXTINF:3.25,
hls/segment31.ts
#EXTINF:3.25,
hls/segment32.ts
#EXTINF:3.34,
hls/segment33.ts
#EXTINF:3.13,
hls/segment34.ts
#EXTINF:3.50,
hls/segment35.ts
#EXTINF:3.34,
hls/segment36.ts
#EXTINF:3.00,
hls/segment37.ts
#EXTINF:3.42,
hls/segment38.ts
#EXTINF:3.25,
hls/segment39.ts
#EXTINF:3.88,
hls/segment40.ts
#EXTINF:3.25,
hls/segment41.ts
#EXTINF:3.46,
hls/segment42.ts
#EXTINF:3.13,
hls/segment43.ts
#EXTINF:3.46,
hls/segment44.ts
#EXTINF:3.67,
hls/segment45.ts
#EXTINF:1.52,
hls/segment46.ts
#EXT-X-ENDLIST
```

**Comment by sstankov** [comment]
Sorry, my error.

**Comment by mangui** [comment]
I dont get such error on my side ? playback is working fine until the end of the video.

**Comment by sstankov** [comment]
I just updated one image, do you see it? The video start at first, but later it get this error.

**Comment by mangui** [comment]
yes I can see your image, but http://flashls.org/flashls-0.4.0.3/examples/osmf/StrobeMediaPlayback.html?src=http%3A%2F%2Fcast1u.webvideocore.net%2Faes3ios_3pa565436f2q5md5trc06aobep7gotff3t27mknsn2l7in136t9qm2e285m8rkbgqihl546nfhfjut3dp70qo4s4j9iagjfn7g3qt88%2Fvod%2Fvod%2F517771200_200.mp4%2Findex.m3u8 is working fine on my side, no decryption issue.

**Comment by sstankov** [comment]
I think it does not matter, but this happens when I try to play it n firefox,

and when I try in Flash IDE, I get:

Error: PKCS#5:unpad: Invalid padding value. expected [24], found [108]
	at org.mangui.hls.utils::AES/unpad()
	at org.mangui.hls.utils::AES/_decryptChunk()
	at org.mangui.hls.utils::AES/_decryptTimer()

**Comment by mangui** [comment]
I am using FF/MacOS, with FP debug version, and I dont get this ?

**Comment by sstankov** [comment]
I'm on win7/ff. On win7/Chrome I do not see the issue.Very strange. Thanks for support mangui I will ping you if ?I found something else.

**Comment by mangui** [comment]
btw, padding values are not usual.
for AES-128, max padding length is 16 bytes.  
https://en.wikipedia.org/wiki/Padding_%28cryptography%29#PKCS7
and the padding value read at the end of the buffer is the number of bytes that needs to be unpadded.
your values are bigger than 16 ( I can see 24 and 205 in your screenshot)

**Comment by sstankov** [comment]
Aha, this comes from the AES key I guess?

**Comment by mangui** [comment]
well, it could come from a wrong key, but most probably you would see other errors printed in the console (like demuxing errors ...) best is to try to reproduce with debug/debug2 logs enabled.

**Comment by arnaudleyder** [comment]
Hi mangui,

I have the same error as described in this issue with an AES-128 HLS stream (using Initialization Vector (IV))
![image001](https://cloud.githubusercontent.com/assets/6594069/7980628/5c6307a8-0aa9-11e5-9eed-1effce88885f.png)
Sometimes I can play the stream but with a lot of stuttering sometimes the error just pop. It happens  on Firefox and Chrome win 8.1 with latest Flash. I did use different versions of your plugin with Strobe and with the same results. The debug log does not seem to provide further information as per the root cause of this issue.

The HLS stream we use is http://195.14.130.230/hls/newdemoaes/NEWDEMOAES.m3u8. This is an experiemtal stream so it may not be working at the time of your testing. Note this is a live stream to make things simpler :/

It has the specificy of using Initialization Vector (IV) as described by the HLS spec. It goes like

    #EXTM3U
    #EXT-X-VERSION:3
    #EXT-X-TARGETDURATION:11
    #EXT-X-MEDIA-SEQUENCE:7948
    #EXT-X-KEY:METHOD=AES-128,URI="http://195.14.130.230/newdemoaeskeys/keyfile7941.key",IV=0x00000000000000000000000000001f0c
    #EXTINF:10.000,
    NEWDEMOAES_StreamC_7948.ts
    #EXT-X-KEY:METHOD=AES-128,URI="http://195.14.130.230/newdemoaeskeys/keyfile7941.key",IV=0x00000000000000000000000000001f0d
    #EXTINF:9.990,
    NEWDEMOAES_StreamC_7949.ts
    #EXT-X-KEY:METHOD=AES-128,URI="http://195.14.130.230/newdemoaeskeys/keyfile7941.key",IV=0x00000000000000000000000000001f0e
    #EXTINF:9.990,
    NEWDEMOAES_StreamC_7950.ts
    #EXT-X-KEY:METHOD=AES-128,URI="http://195.14.130.230/newdemoaeskeys/keyfile7951.key",IV=0x00000000000000000000000000001f0f

Does your plugin supports custom IV on individual segments?
Thanks

**Comment by mangui** [comment]
yes, flashls supports custom IV on individual segments. also as per the spec, if IV is not specified, SN will be used as IV.

**Comment by arnaudleyder** [comment]
ok thanks for the answer. FYI this HLS stream works fine when viewed on an iPad for example. I will try to see if I can dig further in the logs later on.

**Comment by mangui** [comment]
plz reopen if anything pending
