### ISSUE TITLE
How to determine that given URL is DVR or not?

### ISSUE THREAD

**Issue by AlexSnet** [mangui/flashls#191]

**Comment by mangui** [comment]
hls.type should return VOD or LIVE

**Comment by AlexSnet** [comment]
Yes, but on Live DVR (ex.: http://live.maestro.cdnvideo.ru/maestro/maestro_hq.sdp/playlist.m3u8?DVR ) it returns LIVE, which is a half of truth...
It has DVR for 24 hours...

**Comment by mangui** [comment]
this playlist does not have a ENDLIST tag, hence it is marked as LIVE.
it is up to the player application to eventually treat this differently.

2015-01-29 16:15 GMT+01:00 Alex Snet <notifications@github.com>:

**Comment by flavioribeiro** [comment]
Just to mention, we [check](https://github.com/clappr/clappr/blob/master/src/playbacks/hls/hls.js#L93) if the video is live and has more than 4 minutes on its playlist. If so, we enable seeking back.
