### ISSUE TITLE
How to make hls_capleveltostage to false in chromelessflashhls

### ISSUE THREAD

**Issue by bharathsn0812** [mangui/flashls#192]
I am using swfobjects.js where i am inserting flashchromelesshls on express.swf so by using onVideoSize not able to change size of video
Need to know way to make hls_capleveltostage in flashchromelesshls to false to prevent srceen resize change in first place.

**Comment by mangui** [comment]
I m not clear at all about your issue.
hls_capleveltostage is set to false by default.
or you can change JS to avoid this resize to happen ?
https://github.com/mangui/flashls/blob/master/examples/chromeless/index.html#L511-L527

**Comment by bharathsn0812** [comment]
hls_capleveltostage is set to false by default, but i found the player re-size itself and then invoke onVideoSize() function.
I wanted this re-size of player to be avoided and play still for all video links.

I don't have control on width and height of flashchromless.swf after i place inside express.swf from swfobjects.js :) , it is expected to take full width and height of <embed> tag.

**Comment by bharathsn0812** [comment]
Am sorry after quite good amount of iteration i found the Aspect ratio was not same for different quality.

**Comment by bharathsn0812** [comment]
When i make hls_capleveltostage  = true , then screen size will not change if i add links of  different dimension.
But the BLACK-BANK will be added on all four sides :( . Is there any way to prevent this?
