### ISSUE TITLE
Manual switching of bitrate streaming with osmf plugin

### ISSUE THREAD

**Issue by shivamg705** [mangui/flashls#193]
Can i manually switch bitrates of streaming with osmf plugin.

Actually i try following code for doing this.
mediaPlayer.autoDynamicStreamSwitch = false;
mediaPlayer.switchDynamicStreamIndex(bitrateAdaptive.selectedIndex);
mediaPlayer.addEventListener(DynamicStreamEvent.SWITCHING_CHANGE, onSwitchingChange); 

Here onSwitchingChange handle is called but streaming does not changed.Can you tell me something about this?.I appreciate your help,thanks in advance.

**Comment by mangui** [comment]
this should do the trick;
i m using
// Resets OSMF dynamic properties to be able to switch manually.
player.autoDynamicStreamSwitch = false;
player.maxAllowedDynamicStreamIndex = player.numDynamicStreams - 1;
// Switches the dynamic index.
player.switchDynamicStreamIndex(newCurrentDynamicIndex);

**Comment by shivamg705** [comment]
I have used your trick,it works
thanks

**Comment by JulianPena** [comment]
Hi, I'm trying to do the same but this not work for me, when I call the method : 

player.**switchDynamicStreamIndex**(newCurrentDynamicIndex)

the player just restart the stream but dont change the bitrate, can you help me please?
