### ISSUE TITLE
Late binding audio in Chromless player is not supported

### ISSUE THREAD

**Issue by bharathsn0812** [mangui/flashls#195]
Is there any hack to make this run

#EXTM3U
#EXT-X-VERSION:4
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="program_audio",LANGUAGE="lang1",NAME="English",AUTOSELECT=YES,DEFAULT=YES,URI="startrekml1500k_GatrGlHX/startrekml1.m3u8"
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1500000,CODECS="avc1.4d401e,mp4a.40.2",AUDIO="program_audio"
startrekml11500k_kaiwJCS2/startrekml1.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=750000,CODECS="avc1.4d401e,mp4a.40.2",AUDIO="program_audio"
startrekml1750k_NL302HNM/startrekml1.m3u8

**Comment by mangui** [comment]
duplicate of #6 , will start pushing code later this week

**Comment by bharathsn0812** [comment]
please check with this url
http://playertest.longtailvideo.com/adaptive/eleph-audio/playlist.m3u8

**Comment by mangui** [comment]
works fine with flashls/dev branch
