### ISSUE TITLE
Get Player Volume?

### ISSUE THREAD

**Issue by mattwa1sh** [mangui/flashls#197]
Hi guys--

How do we get the player volume? Is there a hook for this?

Thanks!
Matt

**Comment by mangui** [comment]
yes plz refer to https://github.com/mangui/flashls/blob/dev/src/org/mangui/chromeless/ChromelessPlayer.as#L351

**Comment by mattwa1sh** [comment]
Well, that sets the volume and returns void. If you try to return the volume property it returns 1 all the time. (It's actually volume not vol as I indicated in my little snippet. In any case, it doesn't work. But it's okay. I implemented on JS side.

M

**Comment by mangui** [comment]
hls.stream.soundTransform.volume should return what you want in theory
