### ISSUE TITLE
Compilation fails with an error?

### ISSUE THREAD

**Issue by oripessach** [mangui/flashls#199]
This is weird:

Compiling bin/release/flashls.swc
Loading configuration file /Users/opessach/Documents/projects/flex_sdk_4.6/frameworks/flex-config.xml
/Users/opessach/Documents/projects/flashls-0.4.0.3/src/org/mangui/hls/stream/StreamBuffer.as(420): col: 22 Error: Implicit coercion of a value of type String to an unrelated type int.

            for (var i : int in _headerTags) {

What's happening here?

**Comment by mangui** [comment]
Fixed by  #200, does not happen with AIR SDK
