### ISSUE TITLE
Can we add subtitles in flashchromeless???

### ISSUE THREAD

**Issue by bharathsn0812** [mangui/flashls#202]
Was eager to know if i can add subtitles with video

**Comment by mangui** [comment]
which subtitles format are u talking about ?
MPEG_TS subtitle : https://github.com/mangui/flashls/issues/147
CEA-608 : https://github.com/mangui/flashls/issues/11
timed metadata carried in ID3 tag : https://github.com/mangui/flashls/issues/76
currently only the latest is supported

**Comment by mangui** [comment]
closing as answered
