### ISSUE TITLE
integrate swc in custom OSMF based player

### ISSUE THREAD

**Issue by paralichko** [mangui/flashls#203]
Hi,
could You explain me, if integration of Your plugin can be build inside OSMF based player and how ?

Br
Gaby

**Comment by mangui** [comment]
flashlsOSMF provides a standard OSMF plugin; you can use it straightaway to build a custom OSMF player. it is working as is with SMP and GrindPlayer for example. refer to OSMF docs

```
import org.mangui.osmf.plugins.HLSPlugin;
import org.osmf.media.MediaFactory;
...
var factory:MediaFactory = new MediaFactory();
var _hls:HLSPlugin = new HLSPlugin();
factory.loadPlugin(new PluginInfoResource(_hls));
```

**Comment by paralichko** [comment]
Hi,
i am using 
import org.mangui.osmf.plugins.HLSPlugin;
factory.loadPlugin(new PluginInfoResource(new HLSPlugin()));


for loading Your Plugin, but the player doesn't work ( i see requests for m3u8 playlists, but never for .ts chunks. )
I successfully loaded denivip plugin ( https://github.com/denivip/osmf-hls-plugin ) with same like command ( on the same file ( MediaDisplay.as ): 

import org.denivip.osmf.plugins.HLSPluginInfo;
factory.loadPlugin(new PluginInfoResource(new HLSPluginInfo()));

and the player works OK, but I need Your plugin, because of the perfect buffering ( i am using it with strobe ).
I am beginner in flash so Your contribution will be highly appreciated.

Sincerely
Gaby

**Comment by kalimba** [comment]
Both of them are loading exactly same. There is an example at https://github.com/mangui/flashls/issues/179 .

**Comment by paralichko** [comment]
Did You successfully loaded this plugin ? In which file i should put these ? I have put this in MediaDisplay.as and the denivip plugin works, bu this doesn't. Any idea ?

**Comment by mangui** [comment]
As you said that playlist is loading, could u enable hls debug/debug2 logs to get an overview of the workflow ?

**Comment by paralichko** [comment]
How to enable this, as the plugin is loaded internally ( swc ), and not accepting configuration options from html ? It seems that the plugin doesn't load, because with the unmodified OSMF player the behaviour is the same when i try to load HLS stream.

**Comment by paralichko** [comment]
I fixd it. The problem was that i am using URLResource instead of StreamingURLResource. Now the question is, how i can define the buffers, is it possible via html with parameters when the plugin is compiled in the player ?

**Comment by mangui** [comment]
you can either modify directly using org.mangui.hls.HLSSettings or you can also retrieve them from html params, see here: https://github.com/mangui/flashls/blob/dev/src/org/mangui/osmf/plugins/HLSPlugin.as#L37-L58
syntax is described here : https://github.com/mangui/flashls#strobe-media-playback-smp-and-other-osmf-based-players

**Comment by paralichko** [comment]
Is the source code for strobeplayer, that You are using in examples available ?

**Comment by mangui** [comment]
not clear about your question, but Strobe Media Player Source Code is available here : 
https://github.com/willwh/osmf/tree/master/player/StrobeMediaPlayback

**Comment by paralichko** [comment]
In Your examples directory, there is a strobemediaplayer.swf, that is able to load Your plugin. Is this StrobeMediaPlayer customized somehow for Your plugin, because when i try to load Your plugin to another strobemediaplayer - it doesn't happen. My mission is to customize a player with my skin and Your plugin. I have sources of my player, and succeeded to load the plugin, but i don't have so good experience like with strobe. When Your plugin is loaded into my player, and there is a network cut for 1 min, my player stops, but the strobe reconnects when the network is back...

**Comment by mangui** [comment]
closing as pending issue is not clear

**Comment by rafa8626** [comment]
I'm trying to compile a player using Flex 4.6 but so far I haven't been successful. I have created my own class but so far is not doing anything. Can you assist me on this, please?

This is the line I'm using to compile it:

```
$flex_path/bin/mxmlc -define+=CONFIG::LOGGING,false -strict=false -compiler.debug=true -warnings=true ./src/flash/flash-video-hls/HlsMediaElement.as -o build/mediaelement-flash-video-hls.swf -library-path+=$flex_path/lib $libraries -use-network=true -target-player $target_version -source-path ./src/flash/flash-video-hls -headless-server -static-link-runtime-shared-libraries -include-libraries+=./src/flash/flash-video-hls/flashlsOSMF.swc
```

It doesn't come up with any errors but when I try to see my file nothing happens
