### ISSUE TITLE
Order of m3u8 manifest

### ISSUE THREAD

**Issue by lerivin** [mangui/flashls#206]
Does the bandwidth order matter?  Our current file starts with high-bandwith first. All examples I have seen on HLS start with the smaller bandwidths first. 

#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=3872000
134946197.smil/CCURstream3872000.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1136000
134946197.smil/CCURstream1136000.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=45000
134946197.smil/CCURstream45000.m3u8

**Comment by mangui** [comment]
no, bw order does not matter, variant playlists are sorted after parsing.
however if your question is about playback start level, it is possible to customize it, refer to https://github.com/mangui/flashls#configuration 
hls_startfromlevel

**Comment by lerivin** [comment]
Thanks for your answer...exactly what I was looking for.

**Comment by blacktrash** [comment]
FWIW - for html5 hls only the first entry matters: https://developer.apple.com/library/ios/technotes/tn2224/_index.html#//apple_ref/doc/uid/DTS40009745-CH1-BITRATERECOMMENDATIONS (in case you are using the same variant playlist also for generic hls).

**Comment by mangui** [comment]
flashls default behaviour is to perform a bitrate test by downloading the first fragment from lowest bitrate, to determine the start level. this is customizable off course.
Cheers,
Mangui

**Comment by blacktrash** [comment]
Of course ;-) Thanks.
