### ISSUE TITLE
Buffering / Memory Issue on Windows / IE

### ISSUE THREAD

**Issue by lerivin** [mangui/flashls#207]
In our settings we are setting our HLS to have an infinite buffer with infinite back buffer

HLSSettings.maxBufferLength = 0;
HLSSettings.maxBackBufferLength = 0;

This setting allows for us to keep the entire video in memory. And it works great on Macs but we are seeing significant memory degradations on Windows in IE and Firefox. The Flash Player is even crashing in many instances. 

Any idea why Mac vs. Windows would have such performance differences? Any settings Im missing that might allow me to continue to have the player setup with unlimited buffer?

**Comment by mangui** [comment]
no idea why there are any differences, maybe RAM size difference ?
but setting an infinite backbuffer seems like a dangerous idea...
