### ISSUE TITLE
flashhls (org.mangui.hls.HLS) wont play live stream in mac safari

### ISSUE THREAD

**Issue by lemonwhale** [mangui/flashls#208]
I am building a custom video player with your excellent hls library. Almosteverything works smooth and fine. 

However, in Mac safari, I get 
Cannot load M3U8: Error #2032: Stream Error

Seems like there is some kind of difference in permissions between browsers, since we can play it in Chrome. The crossdomain-file exists, so that should not explain it. We are also using tokens. here is the strange part: if we hit the url directly in the safari browser first, then everything works fine. 

Any ideas what to do here? Thank you in advance.

**Comment by mangui** [comment]
that is odd, you might need to check the network requests on your browser console to see what is going on.
