### ISSUE TITLE
url params decoded before its put into player

### ISSUE THREAD

**Issue by vladsd** [mangui/flashls#209]
Check out url:
http://test.viaway.com/view/32615932/-12-105-pm055?st=13982&ps=1424998682&ttp=3300

Its encodes the path= but when url is called in browser, that encoding is gone!

Please advise,

Thanks.

**Comment by mangui** [comment]
could you reproduce similar issue with chromeless player and provide a scenario with clear steps ?
I cannot assist you to investigate issue on a custom player with blur steps
thanks
Mangui

**Comment by vladsd** [comment]
Step 1. 
Go to url:
http://dvr7.viaway.com/dvr7/8b9ab6c3-b739-4e46-8d08-e45f8bd6eb6d/replay.m3u8?path=http%3a%2f%2fus.contentplay.viaway.com&

Step 2. 
Open Dev console on chrome and see configuration for link to play. It will have url somethinkg like this:
http://dvr7.viaway.com/dvr7/8b9ab6c3-b739-4e46-8d08-e45f8bd6eb6d/replay.m3u8?path=http%3a%2f%2fus.contentplay.viaway.com&st=87500&ps=1425072200&ttp=3300&ttl=60000&Policy=...

Step 3. 
Click Network tab in chrome developer tool and see what url is requested. The first replay.m3u8 requested is something like this:
http://dvr7.viaway.com/dvr7/8b9ab6c3-b739-4e46-8d08-e45f8bd6eb6d/replay.m3u8?path=http://us.contentplay.viaway.com&st=87824&ps=1425072524&ttp=3300&ttl=60000&Policy=

Note that "path" param has been decoded and now it is not a valid url param

**Comment by blacktrash** [comment]
Right now I get a 403 Forbidden error for the clip url.
Be that as it may, when I tested before, and you can even verify that now: In the console enter `$f().getClip().url` and the response is not truncated at all.

**Comment by vladsd** [comment]
well url expires in matter of 10-15 seconds:) but we found a work around. try the same version with JW Player and it works!!! Here is url to use for JW:
http://test.viaway.com/view/32615932/-12-105-pm055?st=13982&ps=1424998682&ttp=3300&usejw=1

**Comment by mangui** [comment]
flashls does not modify/process the URL, maybe Flowplayer does ?
would you mind checking with bin/debug/flashlsFlowplayer.swf instead of bin/release
. you should get some logs printed on the console, the URL provided by Flowplayer to flashls should be displayed, see here : https://github.com/mangui/flashls/blob/dev/src/org/mangui/flowplayer/HLSStreamProvider.as#L212-L215

**Comment by vladsd** [comment]
we created a workaround
