### ISSUE TITLE
Switch to a lower bitrate with different program date time is causing replay

### ISSUE THREAD

**Issue by leandromoreira** [mangui/flashls#210]
When you have multiples bitrates with different program date time (with delta of 1 second at maximum), the  `switch to a lower bitrate` is replaying / advancing the playback while the `switch to a higher bitrate`  works fine.

See a snapshot of stream's bitrate PROGRAM-DATE-TIME. (+- 1s)
```
#EXT-X-PROGRAM-DATE-TIME:2015-02-27T19:48:21.304+00:00
#EXT-X-PROGRAM-DATE-TIME:2015-02-27T19:48:21.304+00:00
#EXT-X-PROGRAM-DATE-TIME:2015-02-27T19:48:21.072+00:00
#EXT-X-PROGRAM-DATE-TIME:2015-02-27T19:48:25.862+00:00
#EXT-X-PROGRAM-DATE-TIME:2015-02-27T19:48:25.864+00:00
```
## Steps to reproduce

Try to load and watch the video "http://live.hls.globo.com/dvr/clockmangui/playlist.m3u8?h=0401736103948012345678914250639489876543210xWpmBqCEPSkXU2R0h7mc_Q&u=&a=A"

Force to stream `switch to a lower bitrate` (from 1864 to 750, both are with more or less 1s of difference) it replays (or advance) the playback, however when you `switch to a higher bitrate` (from 750 to 1864, both are with more or less 1s of difference) it works fine.

**Comment by mangui** [comment]
when program date is defined, flashls will use this info to synchronize playlists / and find which is the next fragment to load. 
this is handled here : 
https://github.com/mangui/flashls/blob/dev/src/org/mangui/hls/loader/FragmentLoader.as#L598-L603
you might try to comment these lines ... if commented flashls will rely on fragment PTS analysis to find next fragment to load.

what puzzles me in your live playlists is that each frag duration is 5s but the program date has a delta of +/- 1s amongst playlists; 
I am just wondering how your playlist could be keyframe aligned then ? 
cheers,
Mangui

**Comment by leandromoreira** [comment]
@mangui thanks, I'm using https://github.com/arut/nginx-rtmp-module to generate ` hls chunks` and send them to a datastore and rebuilding the playlist on my server. This Nginx-Rtmp allows me to generate identical chunks in different machines using https://github.com/arut/nginx-rtmp-module/wiki/Directives#hls_fragment_slicing .

When I rebuild the playlists(master and individual) I needed to generate PROGRAM-DATE-TIME, right now I'm relying on `system date time`. Since PROGRAM-DATE-TIME is not mandatory I'm gonna remove it.
