### ISSUE TITLE
AIR for IOS

### ISSUE THREAD

**Issue by wlxhhr** [mangui/flashls#212]
I use the Player.as to demo on PC with Adobe AIR for IOS. 
It works fine on PC emulator, but does not work on IPad
what's wrong did I do?

**Comment by blacktrash** [comment]
That's not really flashls related, because iOS does not support Flash. You have to offer HLS as html5 video on iOS (and most mobile devices for that matter).

**Comment by wlxhhr** [comment]
I mean Adobe AIR for IOS, actually it support IOS with flash as3

**Comment by mangui** [comment]
unfortunately Adobe AIR for IOS does not support NetStream.appendBytes() in data generation mode, see here :
http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/net/NetStream.html
this mode is a prerequisite for flashls to be able to work properly.

please note this mode works on Android devices (I have been reported that flashs even works on old Android 2.2 devices thanks to it).

**Comment by mangui** [comment]
question answered, closing
