### ISSUE TITLE
Dropped Frames as a bit rate heuristic

### ISSUE THREAD

**Issue by maherbeg** [mangui/flashls#213]
Hi,

Are dropped frames used as a heuristic for determining optimal bit rates? We're seeing our customers see dropped frames on low powered machines, but the plugin continues to step up the bit rate because bandwidth is available.

**Comment by mangui** [comment]
Hi @maherbeg, no it is not used currently

**Comment by maherbeg** [comment]
Can we request this as a feature?

**Comment by mangui** [comment]
some hints on the way OSMF is handling it :
there is a rule to monitor dropped FPS
https://github.com/willwh/osmf/blob/master/framework/OSMF/org/osmf/net/rules/DroppedFPSRule.as

it is used as below : 
https://github.com/willwh/osmf/blob/master/framework/OSMF/org/osmf/net/httpstreaming/HTTPStreamingNetLoader.as#L137

if dropped FPS rate is more than 10%, level should be blacklisted.

**Comment by mangui** [comment]
closing as implemented, feedback welcome
