### ISSUE TITLE
Dropped Frames Incorrect Reported in NetStreamInfo object

### ISSUE THREAD

**Issue by aneebq** [mangui/flashls#215]
The ```NetStreamInfo#droppedFrames``` value is accurate during normal playback. Though, when the user seeks, the number drops down to 0. In contrast, the ```NetStream``` object provided by Flash correctly accumulates the number of dropped frames even when a user seeks. 

This seems like a bug in the ```HLSNetStream``` provided by Flashls. Is this something simple to fix?

**Comment by mangui** [comment]
Hi @aneebq, HLSNetStream implements NetStream, but it is not overriding anything about NetStreamInfo.
as you might know , NetStream does not support seeking in data generation mode. this is handled by flashls, but most most probably the decoding context is reset in that case.
so at a first sight I wouldnt think it is a flashls issue, rather a limitation of NetStream in data generation mode.

**Comment by mangui** [comment]
closing, as feedback has been provided
also plz refer to #213 as it might be related
