### ISSUE TITLE
player fails to play stream while jwplayer works on same

### ISSUE THREAD

**Issue by vladsd** [mangui/flashls#216]
Here is flashhls version, downloads chunks but never plays:
http://www.viaway.com/view/30630563/direct/c6d43e34-d9ac-44c8-b489-89aaaf026992

but jwplayer or VLC plays the same fine
http://www.viaway.com/view/30630563/direct/c6d43e34-d9ac-44c8-b489-89aaaf026992?usejw=1

**Comment by mangui** [comment]
Hi @vladsd 
could you use bin/debug/flashlsFlowplayer.swf and enable debug/debug2 logs so that I could understand what is going on ?
or share an access to this stream (with crossdomain.xml setup so that i could check it locally). my email address is available through github API

Cheers,
Mangui

**Comment by vladsd** [comment]
Here is a link where you can see test player with console:
http://test.viaway.com/view/30630563/direct/c6d43e34-d9ac-44c8-b489-89aaaf026992

also github API does not return your email - write to me directly please vkroutik with google email service

**Comment by mangui** [comment]
I am confused, from the description you said that video never plays with flashls also it does play with jwplayer, but while clicking on your link i got video playing back.
moreover you didnt setup the debug logs. (it is the debug release without debug loggers enabled)

**Comment by vladsd** [comment]
I am confused too, as it plays today. I am going close it for now, and see if it comes back.
