### ISSUE TITLE
mangui/video-js-swf can be update ?

### ISSUE THREAD

**Issue by Wellming** [mangui/flashls#217]
videojs / video-js-swf version is already 4.5.3, flashls version is 0.4.0.4

mangui/video-js-swf can be update ?

**Comment by mangui** [comment]
i will wait for flashls v0.4.0.5 to update as there are some remaining issues lying around.

**Comment by Wellming** [comment]
thanks.

**Comment by waster** [comment]
agree, v0.4.0.5 is ready, can we expect to video-js-swf update soon too?

**Comment by waster** [comment]
[Here](http://77.221.142.84:8081/live/videojs-contrib-ads/example/index-flashhls.html) is the test of the stream encoded with ' ffmpeg -c:v libx264 -crf 23 -g 30 -s 640x360 -c:a libfdk_aac -b:a 64k '. I compiled your videojs plugin with the latest videojs.

**Comment by mangui** [comment]
plz check any stream related issue with the latest release of chromeless player thx

**Comment by waster** [comment]
I tried on this [test page](http://77.221.142.84:8081/live/flashls/examples/chromeless/). Stream becomes discontinuous after some time. Can it be related to the network problems, e.g. slow return peaks?

**Comment by Wellming** [comment]
Is mangui/video-js-swf with latest flashls coming ?

**Comment by mangui** [comment]
help yourself.

**Comment by waster** [comment]
Downgraded flashls to 0.3.5 on the [test](http://77.221.142.84:8081/live/flashls/examples/chromeless/) page. The problem remains. Stream is jumping also from time to time.

**Comment by mangui** [comment]
closing as it has been recently updated
