### ISSUE TITLE
onFragmentPlaying() log?

### ISSUE THREAD

**Issue by condensa42** [mangui/flashls#222]
What is the meaning of the field "metrics" and "cc"?
Unfortunately I was unable to understand the source code to find the answer yourself.
Thanks.

![screen shot ](https://cloud.githubusercontent.com/assets/8314023/6629467/3e6768fa-c906-11e4-8bc7-44c33c9b5837.png)

**Comment by mangui** [comment]
metrics is not named properly but it is playback level (index of adaptive playlist, 0 means lowest bitrate level)
cc is continuity counter (might increase in case of discontinuity tag in the playlist)

**Comment by condensa42** [comment]
Thank you so much for the quick response!

http://tools.ietf.org/html/draft-pantos-http-live-streaming-14
Do I understand correctly that sn is the same as that "EXT-X-MEDIA-SEQUENCE:sn"?
http://tools.ietf.org/html/draft-pantos-http-live-streaming-14#section-4.3.3.2

"is playback level (index of adaptive playlist" - In what section about it described? In http://tools.ietf.org/html/draft-pantos-http-live-streaming-14#section-6.2.4? Or am I mistaken and looking in the wrong place. 

"cc is continuity counter" - In what section of "draft" it is described? I correct understand that it is part of the Media Segments/MPEG TS? or not?
http://en.wikipedia.org/wiki/MPEG_transport_stream - continuity counter

Thanks.

**Comment by mangui** [comment]
sn : right
level : right ; it is the index of variant streams (variants are sorted by bitrate, 0 = lowest)
cc : wrong.it is related to http://tools.ietf.org/html/draft-pantos-http-live-streaming-14#section-4.3.2.3
cc starts at 0 and increments at each discontinuity. a better naming could be discontinuity counter...

**Comment by condensa42** [comment]
Thanks!
