### ISSUE TITLE
Dispach onError

### ISSUE THREAD

**Issue by fbmx** [mangui/flashls#223]
Hi,

the event onError seems not throw to flowplayer, the idea behind is implement a fallback method.

if i use this url : http://streambox.fr/playlists/test_001/stream00.m3u8 (bad url)
i got this 

[INFO] time 01:04:40.724 :: org.flowplayer.controller::StreamProviderController : onBegin, initializing content for clip [Clip] 'http://streambox.fr/playlists/test_001/stream00.m3u8'
stream00.m3u8:1 GET http://streambox.fr/playlists/test_001/stream00.m3u8 404 (Not Found)

but i'm not able to catch anything in onError event

**Comment by mangui** [comment]
indeed onError did not dispatch any event to Flowplayer
should be fixed now, plz recheck with latest flashls/dev

**Comment by fbmx** [comment]
Thank Guillaume, is fixed :)
