### ISSUE TITLE
Live stream stopping

### ISSUE THREAD

**Issue by jcre** [mangui/flashls#224]
Hi,

I can't go into too many details in a public issue tracker but we have a client who is using flashls inside their OSMF based player and it's been working fine. However they're now trying to stream from a different streaming server compared to what they've been using previously. The problem arises that periodically flashls seems to get stuck in a buffering then playing state but the stream just freezes and needs restarting to resume watching.

The issue doesn't happen on iOS, or another HLS OSMF plugin. However we've been using flashls for quite a while for this customer and would rather just update flashls than implement a new plugin (which has restrictive licensing).

As the streaming server gives us quite a lot of control, we've tried changing framerates, segment lengths, the amount of segments inside the manifest, etc. As I said we think we know what the problem is but I am unable to share this on github - if you're willing, I would like to email you with the affected HLS URL and what I think is happening in the hope that it's a quick fix. We don't believe that the server is violating the draft HLS spec.

Thanks

**Comment by mangui** [comment]
you can find my email with the following cmd:
curl https://api.github.com/users/mangui/events/public | grep email

**Comment by jcre** [comment]
This does seem to be resolved, thanks
