### ISSUE TITLE
how to detect internet failure

### ISSUE THREAD

**Issue by bharathsn0812** [mangui/flashls#225]
i am using chromelesshls

**Comment by mangui** [comment]
sorry but your question is vague ... flashls could eventually detect IO error while trying to load playlists/fragments. but not internet failure.
plz check by yourself Chromeless source code and web page, it shouldnt take long.

**Comment by bharathsn0812** [comment]
Sorry , i was in hurry to implement some feature.
Will try to check to detect IO failures.
