### ISSUE TITLE
In VideoJS, a replay problem.

### ISSUE THREAD

**Issue by Wellming** [mangui/flashls#226]
In VideoJs, when play HLS video ended, I want replay the video, I click the play button, the video starts playing, but the progress bar is 100%, and the play button state is in a pause state.

Play mp4 video, do not have this problem.

I debug the code and found, click the play button to replay HLS video,  VideoJS play event is not triggered.

I Use:
VideojS 4.12.4 and
https://github.com/mangui/video-js-swf/blob/master/dist/video-js.swf

**Comment by Wellming** [comment]
I found this demo http://www.flashls.org/videojs/flash_demo.html has same problem.

**Comment by mangui** [comment]
I see, I will check this when updating videoJS with upcoming flashls v0.4.0.x release
