### ISSUE TITLE
Problem with iPad plugin

### ISSUE THREAD

**Issue by amgtr** [mangui/flashls#228]
Hi, I apologize ahead of time if this post may appear awkward. This is my first post I'm a newbie at this :)

Your contact was given to me by Support from Flowplayer after i was reporting the following:

We are using this plugin flowplayer.ipad-3.2.14-dev.min.js to deliver psudo-livestream (presenting a VOD as a live stream) from a Wowza Streaming Engine 4.1.1  (ServerListenerStreamPublisher)
 
We are experiencing the following playback problems on iPad, desktop PCs and Androids.
 
When the pause button or the video frame is clicked on, the playback is paused but when clicked-on again to resume, the video does not take the viewer to actual point of the ‘live stream’  but instead resumes playing where it had been paused. Only a browser refresh brings the playback to the proper place in the livestream. This behavior is also not consistent… sometimes after a pause then you can see video ‘skipping’ to the livestream, at other times it just circles and circles and never catches up unless a browser refresh is done.
 
We are using this playback urls
http://ieuplayer.net/nxhls/deDE/ this is a player uses both HLS for PC & mobile devices 
 
Can you please advise how this can be solved
Please let me know if you need more info to troubleshoot.
 
Thank you in advance

**Comment by blacktrash** [comment]
Note that this is not a problem with the iPad plugin per se, but with the generic player, as the plugin just creates a video tag and governs it via JavaScript.
On iOS the generic controls do not seem to offer anything else than start/pause and the 30 second jump back (once it's available).
I have found nothing in the HLS specs equivalent to "start at live position". `EXT-X-ALLOWCACHE` is set to `NO` for the stream, so it's recognized as live. Not sure whether it being a "fake" live stream influences the DVR window.
