### ISSUE TITLE
Force load m3u8 after pause and play

### ISSUE THREAD

**Issue by waster** [mangui/flashls#229]
Hello,

First, thank you for the great module and opportunity to use HLS in all modes.

I have one suggestion. Can you consider to force load m3u8 playlist and corresponding ts chunks after pausing and play in a client? So viewers will see current stream live without waiting for loading a new m3u8 list while playing old chunks after unpausing. Can it be an option may be?

With regards, Andrey.

**Comment by mangui** [comment]
hi,
in your case it looks like you dont want to resume() playback (hls.stream.resume()) but rather you want to seek back to live : you should then call hls.stream.play(null,-1) instead

**Comment by waster** [comment]
Oh, I see, thank you for the hint.
