### ISSUE TITLE
Error #2030: End of file was encountered  at FragmentLoader/_fragLoadProgressHandler()

### ISSUE THREAD

**Issue by gkindel** [mangui/flashls#230]
Hi mangui,

I'm getting an EOF exception in `FragmentLoader.as`, even on the first few segments of a file that occasionally plays fine. I think my request is slower than usual because my segments are bouncing off a 304 redirect to cloud storage, but otherwise it's a normal HLS unencrypted and VOD file.

> [Fault] exception, information=Error: Error #2030: End of file was encountered. at flash.net::URLStream/readBytes() at org.mangui.hls.loader::FragmentLoader/_fragLoadProgressHandler()

            if (event.bytesLoaded > fragData.bytesLoaded) {
                var data : ByteArray = new ByteArray();
                _fragstreamloader.readBytes(data);

For my purposes, I've patched it by adding to the check: 

            if (event.bytesLoaded > fragData.bytesLoaded
                    && _fragstreamloader.bytesAvailable > 0) { // prevent EOF error race condition

 I think it's a pretty safe patch as the [documentation](http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/net/URLStream.html#bytesAvailable) specifically says the property should be checked first:

> Returns the number of bytes of data available for reading in the input buffer. Your code must call the bytesAvailable property to ensure that sufficient data is available before you try to read it with one of the read methods.

It seems intermittent, but occurs more if I build flashls into OSMF directly rather than use a plugin.  I can create a pull request if you'd like.  Just wanted to let you know.

Hope this helps!

**Comment by mangui** [comment]
yes. seems safe. you could proceed with a PR thx !
