### ISSUE TITLE
«hls.stage not set, cannot parse TS data !!!» while client player device under heavy load

### ISSUE THREAD

**Issue by maxkachalin** [mangui/flashls#232]
Hi!
We're using v0.4.0.4 with Grind Player. If client device is under heavy load (reproduce on Mac shell: stress -c 4) player after loading throws an error:

Message: Playback failed
Detail: hls.stage not set, cannot parse TS data !!!

Plugin debug version console output with hls_debug and hls_debug2:
> VM14012:1 1048 DEBUG [object MediatorMap] [object TypeFilter] mapped to [object MediatorMapping]
> VM14014:1 1088 DEBUG [object MediatorMap] [object TypeFilter] mapped to [object MediatorMapping]
> VM14015:1 1100 DEBUG [object MediatorMap] [object TypeFilter] mapped to [object MediatorMapping]
> VM14016:1 1104 DEBUG [object MediatorMap] [object TypeFilter] mapped to [object MediatorMapping]
> VM14017:1 1112 DEBUG [object MediatorMap] [object TypeFilter] mapped to [object MediatorMapping]
> VM14018:1 1117 DEBUG [object MediatorMap] [object TypeFilter] mapped to [object MediatorMapping]
> VM14019:1 1119 DEBUG [object MediatorMap] [object TypeFilter] mapped to [object MediatorMapping]
> VM14020:1 1126 DEBUG [object MediatorMap] [object TypeFilter] mapped to [object MediatorMapping]
> VM14021:1 1132 DEBUG [object MediatorMap] [object TypeFilter] mapped to [object MediatorMapping]
> VM14022:1 1144 DEBUG [object MediatorMap] [object TypeFilter] mapped to [object MediatorMapping]
> VM14023:1 1152 DEBUG [object MediatorMap] [object TypeFilter] mapped to [object MediatorMapping]
> VM14024:1 1157 DEBUG [object MediatorMap] [object TypeFilter] mapped to [object MediatorMapping]
> VM14025:1 1160 DEBUG [object MediatorMap] [object TypeFilter] mapped to [object MediatorMapping]
> VM14026:1 1168 DEBUG [object MediatorMap] [object TypeFilter] mapped to [object MediatorMapping]
> VM14027:1 1172 DEBUG [object MediatorMap] [object TypeFilter] mapped to [object MediatorMapping]
> VM14028:1 1174 DEBUG [object MediatorMap] [object TypeFilter] mapped to [object MediatorMapping]
> VM14029:1 1177 DEBUG [object MediatorMap] [object TypeFilter] mapped to [object MediatorMapping]
> VM14030:1 1185 DEBUG [object MediatorMap] [object TypeFilter] mapped to [object MediatorMapping]
> VM14031:1 1189 DEBUG [object MediatorMap] [object TypeFilter] mapped to [object MediatorMapping]
> VM14032:1 1200 DEBUG [object MediatorMap] [object TypeFilter] mapped to [object MediatorMapping]
> VM14033:1 1201 DEBUG [object MediatorMap] [object TypeFilter] mapped to [object MediatorMapping]
> VM14034:1 1211 DEBUG [object ConfigManager] Now initializing. Injecting into config object [object ContextView]
> VM14035:1 1215 INFO Context-0-74 Initialize complete
> VM14038:1 INFO:HLSSettings.logError = false
> VM14039:1 INFO:HLSSettings.lowBufferLength = 5
> VM14040:1 INFO:HLSSettings.logInfo = true
> VM14041:1 INFO:HLSSettings.logDebug2 = true
> VM14042:1 INFO:HLSSettings.maxBufferLength = 15
> VM14043:1 INFO:HLSSettings.capLevelToStage = false
> VM14044:1 INFO:HLSSettings.minBufferLength = 2
> VM14045:1 INFO:HLSSettings.logDebug = true
> VM14046:1 INFO:HLSSettings.startFromLevel = 0.7
> VM14047:1 INFO:HLSSettings.logWarn = false
> VM14048:1 INFO:HLSSettings.manifestLoadMaxRetry = -1
> VM14049:1 INFO:HLSSettings.maxLevelCappingMode = downscale
> VM14050:1 INFO:HLSSettings.fragmentLoadMaxRetry = -1
> VM14051:1 INFO:HLSSettings.seekMode = ACCURATE
> VM14052:1 INFO:HLSSettings.flushLiveURLCache = true
> VM14053:1 INFO:HLSSettings.seekFromLevel = -1
> VM14054:1 INFO:HLSNetStream:close
> VM14055:1 DEBUG:cancel any manifest load in progress
> VM14057:1 DEBUG:adaptive playlist:
> #EXTM3U
> #EXT-X-VERSION:4
> #EXT-X-STREAM-INF:PROGRAM-ID=1,DEFAULT=NO,BANDWIDTH=3072000
> 3651/source.m3u8
> #EXT-X-STREAM-INF:PROGRAM-ID=1,DEFAULT=NO,BANDWIDTH=393216
> 3651/240p.m3u8
> #EXT-X-STREAM-INF:PROGRAM-ID=1,DEFAULT=YES,BANDWIDTH=548864
> 3651/360p.m3u8
> #EXT-X-STREAM-INF:PROGRAM-ID=1,DEFAULT=NO,BANDWIDTH=98304
> 3651/160p.m3u8
> #EXT-X-STREAM-INF:PROGRAM-ID=1,DEFAULT=NO,BANDWIDTH=1011712
> 3651/480p.m3u8

> VM14058:1 DEBUG:start level :3
> VM14059:1 DEBUG:level 3 playlist:
> #EXTM3U
> #EXT-X-VERSION:4
> #EXT-X-MEDIA-SEQUENCE:0
> #EXT-X-TARGETDURATION:6
> #EXT-X-DISCONTINUITY
> #EXTINF:5.020,
> 17270/0.ts
> #EXTINF:5.000,
> 17270/1.ts
> #EXTINF:5.000,
> 17270/2.ts
> #EXTINF:5.000,
> 17270/3.ts
> #EXTINF:5.000,
> 17270/4.ts
> #EXTINF:5.000,
> 17270/5.ts
> #EXTINF:5.000,
> 17270/6.ts
> …
> VM14060:1 DEBUG:updateFragments: unknown PTS info for this level
> VM14061:1 DEBUG:Level 3 Live Playlist parsing finished: reload in 4849 ms
> VM14062:1 DEBUG:first level filled with at least 1 fragment, notify event
> VM14063:1 DEBUG:_switchup[0]=3
> VM14064:1 DEBUG:_switchup[1]=0.7916666666666666
> VM14065:1 DEBUG:_switchup[2]=1.6865671641791045
> VM14066:1 DEBUG:_switchup[3]=3
> VM14067:1 DEBUG:_switchdown[1]=0.75
> VM14068:1 DEBUG:_switchdown[2]=0.5671641791044776
> VM14069:1 DEBUG:_switchdown[3]=0.5671641791044776
> VM14070:1 DEBUG:_switchdown[4]=0.6706666666666666
> 4VM14071:1 DEBUG:start level :3
> VM14075:1 DEBUG:HLSNetStreamLoadTrait()
> VM14076:1 DEBUG:HLSMediaElement:processReadyState
> VM14077:1 DEBUG:HLSBufferTrait()
> VM14078:1 DEBUG:HLSTimeTrait()
> VM14079:1 DEBUG:HLSDisplayObjectTrait()
> VM14080:1 DEBUG:HLSPlayTrait()
> VM14081:1 INFO:HLSPlayTrait:playStateChangeStart:playing
> VM14082:1 INFO:HLSNetStream:play(-1)
> VM14083:1 INFO:HLSNetStream:seek(-1)
> VM14084:1 DEBUG:seek : requested position:-1.00,seek position:29519.01,min/max buffer position:Infinity/-Infinity
> VM14085:1 DEBUG:[SEEK_STATE] from IDLE to SEEKING
> VM14086:1 DEBUG:[PLAYBACK_STATE] from IDLE to PLAYING_BUFFERING
> VM14087:1 DEBUG:HLSBufferTrait:_stateChangedHandler:setBuffering(true)
> VM14088:1 DEBUG:HLSSeekTrait()
> VM14089:1 DEBUG:HLSDynamicStreamTrait()
> VM14090:1 DEBUG:start level :3
> VM14091:1 DEBUG:HLSDynamicStreamTrait:autoSwitchChangeStart:false
> VM14092:1 DEBUG:HLSAlternativeAudioTrait()
> VM14093:1 DEBUG:HLSAlternativeAudioTrait:numAlternativeAudioStreams:-1
> VM14097:1 DEBUG:start level :3
> VM14098:1 DEBUG:loadfirstfragment(29519.010333728613)
> VM14099:1 DEBUG:Loading       5899 of [0,5902],level 3
> VM14100:1 INFO:HLSNetStream:close
> VM14101:1 DEBUG:[PLAYBACK_STATE] from PLAYING_BUFFERING to IDLE
> VM14102:1 DEBUG:cancel any manifest load in progress
> VM14103:1 DEBUG:cancel any audio level load in progress
> VM14104:1 DEBUG:HLSBufferTrait:_stateChangedHandler:setBuffering(false)
> VM14105:1 DEBUG:[SEEK_STATE] from SEEKING to IDLE
> VM14106:1 INFO:HLSPlayTrait:playStateChangeStart:stopped
> VM14107:1 INFO:HLSNetStream:close
> VM14108:1 2723 ERROR [class MainViewBaseMediator] onMediaError:
> Message: Playback failed
> Detail: hls.stage not set, cannot parse TS data !!!
> 39VM14109:1 DEBUG:position/audio/video bufferLength:0.00/0.00/0.00

Problem is 100% reproducible.

**Comment by mangui** [comment]
stage is set in HlsDisplayObjectTrait.onStage()
you might add a new debug log there to see when this callback is triggered under heavy load.
cheers,
Mangui

**Comment by maxkachalin** [comment]
I'm sorry, but I haven't understood what I have to do. :)
I'll do additional diagnostics, just put me on the right way.

**Comment by mangui** [comment]
Hi @maxkachalin 

hls.stage is set here : 
https://github.com/mangui/flashls/blob/dev/src/org/mangui/osmf/plugins/traits/HLSDisplayObjectTrait.as#L43

this function is called when the video surface is added to stage. in your case it looks like either the video surface is not added to stage, or it is added later (after flashls tries to demux some TS fragments).
adding a debug logs in this function will help understand what is going on.

Cheers,
Mangui

**Comment by kalimba** [comment]
@mangui i have same problem on Google Chrome. While the player is not viewable are of the client browser at the begining, player doesn't play anymore. I have tested a light page.

**Comment by mangui** [comment]
@kalimba i see, i will find another way to handle demuxing timer

**Comment by alf-ytakada** [comment]
@mangui I also have same problem on my player.
I added debug log for  HLSDisplayObjectTrait.onStage .

>        private function onStage(event : Event) : void {
>            Log.debug("HLSDisplayObjectTrait:onStage");
>            _hls.stage = event.target.stage as Stage;
>            videoSurface.removeEventListener(Event.ADDED_TO_STAGE, onStage);
>            videoSurface.addEventListener(Event.ENTER_FRAME, onFrame);
>        }

and browser debug log is below.
> ---- player.media = media ----
> [Event type="mediaPlayerStateChange" bubbles=false cancelable=false eventPhase=2]
> [Event type="loadStateChange" bubbles=false cancelable=false eventPhase=2]
> INFO:HLSNetStream:close
> DEBUG:cancel any manifest load in progress
> ---- adding mediaElement---
> Level Playlist, load it
> DEBUG:level 0 playlist:
> #EXTM3U
> #EXT-X-VERSION:3
> #EXT-X-MEDIA-SEQUENCE:0
> #EXT-X-ALLOW-CACHE:YES
> #EXT-X-TARGETDURATION:11
> #EXTINF:10.005333,
> sound000.ts
> #EXT-X-ENDLIST
> 
> DEBUG:updateFragments: unknown PTS info for this level
> DEBUG:first level filled with at least 1 fragment, notify event
> DEBUG:HLSNetStreamLoadTrait()
> [Event type="bytesTotalChange" bubbles=false cancelable=false eventPhase=2]
> DEBUG:HLSMediaElement:processReadyState
> DEBUG:HLSBufferTrait()
> DEBUG:HLSTimeTrait()
> DEBUG:HLSDisplayObjectTrait()
> DEBUG:HLSPlayTrait()
> DEBUG:HLSSeekTrait()
> DEBUG:HLSAlternativeAudioTrait()
> [Event type="mediaPlayerStateChange" bubbles=false cancelable=false eventPhase=2]
> INFO:HLSPlayTrait:playStateChangeStart:playing
> INFO:HLSNetStream:play(-1)
> INFO:HLSNetStream:seek(-1)
> DEBUG:seek : requested position:-1.00,seek position:0.00,min/max buffer position:Infinity/-Infinity
> DEBUG:[SEEK_STATE] from IDLE to SEEKING
> DEBUG:[PLAYBACK_STATE] from IDLE to PLAYING_BUFFERING
> DEBUG:HLSBufferTrait:_stateChangedHandler:setBuffering(true)
> [Event type="mediaPlayerStateChange" bubbles=false cancelable=false eventPhase=2]
> [Event type="bufferingChange" bubbles=false cancelable=false eventPhase=2]
> [Event type="mediaPlayerStateChange" bubbles=false cancelable=false eventPhase=2]
> [Event type="playStateChange" bubbles=false cancelable=false eventPhase=2]
> playing
> [Event type="loadStateChange" bubbles=false cancelable=false eventPhase=2]
> DEBUG:loadfirstfragment(0)
> DEBUG:Loading       0 of [0,0],level 0
> ERROR:hls.stage not set, cannot parse TS data !!!
> ERROR:HLSError(code/url/msg)=0/http://mydomain.example.com/test/ts/sound/sound000.ts/hls.stage not set, cannot parse TS data !!!
> INFO:HLSNetStream:close
> DEBUG:[PLAYBACK_STATE] from PLAYING_BUFFERING to IDLE
> DEBUG:cancel any manifest load in progress
> DEBUG:cancel any audio level load in progress
> DEBUG:HLSBufferTrait:_stateChangedHandler:setBuffering(false)
> [Event type="bufferingChange" bubbles=false cancelable=false eventPhase=2]
> DEBUG:[SEEK_STATE] from SEEKING to IDLE
> 2WARN:HLS Error event received, dispatching MediaError 15,hls.stage not set, cannot parse TS data !!!
> [Event type="mediaPlayerStateChange" bubbles=false cancelable=false eventPhase=2]
> [Event type="playStateChange" bubbles=false cancelable=false eventPhase=2]
> stopped

There is no *'HLSDisplayObjectTrait:onStage'*.
I am looking forward to that this problem is fixed !
