### ISSUE TITLE
Question on CapleveltoStage

### ISSUE THREAD

**Issue by bharathsn0812** [mangui/flashls#233]
Hi Sir,
swf = flashlsChromeless.swf
i am using obj.playerCapLeveltoStage(true); (also tried with false)
in onhlsready() method to make video doesn't shrink or expand while playing.

But i am not able to achieve this please let me know if i am doing it wrong

**Comment by bharathsn0812** [comment]
my understanding with playerCapLeveltoStage() is it prevents video size expansion and shrink without affecting the auto quality switching functionality , please correct me if i am wrong :)
*ie it ignores adding of black-band  and stretch the video to fullest 

Thanks and Regards
BHARATH

**Comment by bharathsn0812** [comment]
I tried to override this function but still not able to achieve 
function onVideoSize(width, height) {
  appendLog("onVideoSize(), " + width + "x" + height);
  var obj = getFlashMovieObject(player_id);
  if (obj != null) {    
    var state = obj.getCapLeveltoStage(); 
    if(!state) {
      var ratio = width / height;
      if (height > 720) {
        height = 720;
        width = height * ratio;
      }
      appendLog("onVideoSize(),resize stage to " + width + "x" + height);
      obj.width = width;
      obj.height = height;
    }
  }
}

**Comment by mangui** [comment]
this setting is documented in README.md
setting this boolean prevents auto-quality switching algorithm to reach useless levels, for which dimensions are bigger than Stage dimension.

**Comment by mangui** [comment]
answer should be clear, as no feedback
