### ISSUE TITLE
Live TV play in flashlschromeless

### ISSUE THREAD

**Issue by bharathsn0812** [mangui/flashls#234]
Hi Sir,

swf = flashlschromeless.swf

I was able to play live url in previous build but not able to with the present one

Live Url link 
http://ams-lp1.9c9media.com/hls-live/livepkgr/_definst_/liveeventNoDRM/TSN3Open8.m3u8
(Link can be broken)
new live hls url can be obtained in 
http://www.vlc.eu.pn/

Please let me know if i am wrong or a method like toggleFlushLiveURLCache() or similar to be executed before playing it.

Thanks and Regards
BHARATH

**Comment by mangui** [comment]
@bharathsn0812 thx for reporting,
plz recheck with flashls/dev
cheers,
Mangui
