### ISSUE TITLE
pure acc audio can't play 

### ISSUE THREAD

**Issue by pangguoqing** [mangui/flashls#235]
1.audio src: 
http://live.xmcdn.com/192.168.3.134/live/75/32.m3u8 

2.Log in chrome:
INFO:HLSNetStream:close VM99893:1
[Tue Mar 31 2015 19:04:47 GMT+0800 ] stopping playback index.html:270
INFO:HLSNetStream:close VM99895:1
[Tue Mar 31 2015 19:04:47 GMT+0800 ] load URL http://www.flashls.org/playlists/test_001/stream.m3u8 index.html:270
[Tue Mar 31 2015 19:04:47 GMT+0800 ] onHLSReady() index.html:270
[Tue Mar 31 2015 19:04:48 GMT+0800 ] new track list index.html:270
[Tue Mar 31 2015 19:04:48 GMT+0800 ] switching level to 0 index.html:270
[Tue Mar 31 2015 19:04:48 GMT+0800 ] manifest loaded, playlist duration:510.00 index.html:270
INFO:HLSNetStream:close VM99904:1
[Tue Mar 31 2015 19:04:52 GMT+0800 ] load URL http://live.xmcdn.com/192.168.3.134/live/75/32.m3u8 index.html:270
[Tue Mar 31 2015 19:04:53 GMT+0800 ] new track list index.html:270
[Tue Mar 31 2015 19:04:53 GMT+0800 ] switching level to 0 index.html:270
[Tue Mar 31 2015 19:04:53 GMT+0800 ] manifest loaded, playlist duration:21.00 index.html:270
[Tue Mar 31 2015 19:04:57 GMT+0800 ] toggle debug logs to:true index.html:270
[Tue Mar 31 2015 19:04:58 GMT+0800 ] toggle debug2 logs to:true index.html:270
[Tue Mar 31 2015 19:04:58 GMT+0800 ] toggle cap Level to Stage to:true index.html:270
INFO:HLSNetStream:play(-1) VM99915:1
INFO:HLSNetStream:seek(-1) VM99916:1
DEBUG:seek : requested position:-1.00,seek position:0.00,min/max buffer position:Infinity/-Infinity VM99917:1
DEBUG:[SEEK_STATE] from IDLE to SEEKING VM99918:1
DEBUG:[PLAYBACK_STATE] from IDLE to PLAYING_BUFFERING VM99919:1
[Tue Mar 31 2015 19:04:59 GMT+0800 ] switching state to PLAYING_BUFFERING, bufferlen:0 index.html:270
[Tue Mar 31 2015 19:04:59 GMT+0800 ] start playback index.html:270
DEBUG:loadfirstfragment(0) VM99922:1
DEBUG:Loading       86659 of [86659,86661],level 0 VM99923:1
DEBUG:loading fragment:http://live.xmcdn.com/192.168.3.134/live/75/24/150331_000004_56a8.aac
 VM99924:1
DEBUG:position/audio/video bufferLength:0.00/0.00/0.00 VM99926:1
DEBUG:position/audio/video bufferLength:0.00/0.00/0.00 VM99928:1
DEBUG:position/audio/video bufferLength:0.00/0.00/0.00 VM99930:1
DEBUG:position/audio/video bufferLength:0.00/0.00/0.00 VM99932:1
DEBUG:level 0 playlist:
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:7
#EXT-X-MEDIA-SEQUENCE:86660
#EXTINF:7,
http://live.xmcdn.com/192.168.3.134/live/75/24/150331_000004_56a9.aac
#EXTINF:7,
http://live.xmcdn.com/192.168.3.134/live/75/24/150331_000004_56aa.aac
#EXTINF:7,
http://live.xmcdn.com/192.168.3.134/live/75/24/150331_000004_56ab.aac
 VM99933:1
DEBUG:updateFragments: unknown PTS info for this level VM99934:1
DEBUG:Level 0 Live Playlist parsing finished: reload in 6145 ms VM99935:1
DEBUG:position/audio/video bufferLength:0.00/0.00/0.00 VM99937:1
DEBUG:position/audio/video bufferLength:0.00/0.00/0.00 VM99939:1
DEBUG:position/audio/video bufferLength:0.00/0.00/0.00 VM99941:1
DEBUG:position/audio/video bufferLength:0.00/0.00/0.00 VM99943:1
DEBUG:position/audio/video bufferLength:0.00/0.00/0.00 VM99945:1
DEBUG:probe fragment type VM99946:1
DEBUG:AAC/MP3/TS match:true/false/false VM99947:1
DEBUG:position/audio/video bufferLength:0.00/0.00/0.00 VM99949:1
DEBUG:position/audio/video bufferLength:0.00/0.00/0.00 VM99951:1
DEBUG:position/audio/video bufferLength:0.00/0.00/0.00 VM99953:1
DEBUG:position/audio/video bufferLength:0.00/0.00/0.00 VM99955:1
DEBUG:position/audio/video bufferLength:0.00/0.00/0.00 VM99957:1
DEBUG:loading completed VM99958:1
DEBUG:Loading       duration/RTT/length/speed:1681/1075/22075/103 kb/s VM99959:1
DEBUG:AAC: extracting AAC tags VM99960:1
DEBUG:AAC: LC, 22050 Hz 1 channel(s) VM99961:1
[Tue Mar 31 2015 19:05:01 GMT+0800 ] new track list index.html:270
[Tue Mar 31 2015 19:05:01 GMT+0800 ]     AAC ES [0] index.html:270
DEBUG:StreamBuffer : audio track changed, flushing audio buffer:0 VM99963:1
[Tue Mar 31 2015 19:05:01 GMT+0800 ] switching audio track to 0 index.html:270
INFO:Setting audio track to 0 VM99965:1
DEBUG:AAC: all tags extracted, callback demux VM99966:1
DEBUG:152 tags extracted VM99967:1
DEBUG:AutoBufferController:minBufferLength:NaN VM99968:1
DEBUG:m/M audio PTS:NaN/NaN VM99969:1
DEBUG:Total Process duration/length/bw:1751/22075/98 kb/s VM99970:1
DEBUG:Loaded        86659 of [86660,86662],level 0 m/M PTS:NaN/NaN VM99971:1
ERROR:updateFragment:seqnum 86659 not found! VM99972:1
DEBUG:AutoBufferController:minBufferLength:NaN VM99973:1
[Tue Mar 31 2015 19:05:01 GMT+0800] onFragmentLoaded(): bandwidth:101kb/s level:0 index.html:270
DEBUG:position/audio/video bufferLength:0.00/NaN/0.00 VM99976:1
DEBUG:position/audio/video bufferLength:0.00/NaN/0.00 VM99978:1
DEBUG:position/audio/video bufferLength:0.00/NaN/0.00 VM99980:1
DEBUG:position/audio/video bufferLength:0.00/NaN/0.00 VM99982:1
DEBUG:position/audio/video bufferLength:0.00/NaN/0.00 VM99984:1
DEBUG:position/audio/video bufferLength:0.00/NaN/0.00 VM99986:1
DEBUG:position/audio/video bufferLength:0.00/NaN/0.00 VM99988:1

3.I change the code of  AACDemuxer.as
        public static function probe(data : ByteArray) : Boolean {
            var pos : uint = data.position;
            var id3 : ID3 = new ID3(data);
            var i : int = 0;
            // AAC should contain ID3 tag filled with a timestamp
            //if (id3.hasTimestamp) {
                while (data.bytesAvailable > 1 && i<32) {
                    i++;
                    // Check for ADTS header
                    var short : uint = data.readUnsignedShort();
                    if (short == SYNCWORD || short == SYNCWORD_2 || short == SYNCWORD_3) {
                        data.position = pos;
                        return true;
                    } else {
                        data.position--;
                    }
                }
                data.position = pos;
            //}
            return false;
        }

**Comment by mangui** [comment]
pure AAC needs ID3 timestamp
http://tools.ietf.org/html/draft-pantos-http-live-streaming-14#section-3

   Each Elementary Audio Stream segment MUST signal the timestamp of its
   first sample with an ID3 PRIV tag [ID3] at the beginning of the
   segment.  The ID3 PRIV owner identifier MUST be
   "com.apple.streaming.transportStreamTimestamp".  The ID3 payload MUST
   be a 33-bit MPEG-2 Program Elementary Stream timestamp expressed as a
   big-endian eight-octet number, with the upper 31 bits set to zero.
   An Elementary Audio Stream segment without such an ID3 tag can
   trigger playback errors.

**Comment by mangui** [comment]
won't fix, stream is not compliant
