### ISSUE TITLE
v0.4.0.5 flashlsFlowplayer does not work with live stream

### ISSUE THREAD

**Issue by blacktrash** [mangui/flashls#238]
http://flowplayer.blacktrash.org/test/flashls-live.html
Haven't done any real bisecting, but v0.3.5 works.

**Comment by mangui** [comment]
@blacktrash 
I just checked the logs and this playlist is not valid:
it references an audio stream in the PMT but there is no data on this PID.
flashls is expecting some audio data to start the playback but no data is coming ... so it never starts

VM50181:1 DEBUG:TS: PAT found.PMT PID:4097
2015-04-03 18:34:18.308VM50182:1 DEBUG:TS: PMT found
2015-04-03 18:34:18.310VM50183:1 DEBUG:TS: Selected video PID: 256
2015-04-03 18:34:18.311VM50184:1 DEBUG:TS: Found 1 audio tracks
2015-04-03 18:34:18.312VM50185:1 DEBUG:TS: selected AAC PID: 257
2015-04-03 18:34:18.509VM50187:1 DEBUG:AVC: width/height:1280/720

**Comment by blacktrash** [comment]
Right - flashls has become more sensitive ;-) 0.3.5 doesn't care.
I've found another sample stream where it works.

**Comment by blacktrash** [comment]
Sorry for not re-checking the stream before. Closing.

**Comment by blacktrash** [comment]
Seems I have to set `hls_maxbufferlength` to the duration of less than 1 segment than the live window in the playlist, otherwise the loading animation does not go away after pausing.
