### ISSUE TITLE
is there API documentation of chromeless solution?

### ISSUE THREAD

**Issue by Levi0701** [mangui/flashls#239]
Dear mangui

I found you have updated the JS API @ new release of Chromeless, but it seems still no 'Full Screen' method, so I can not get the related method at this moment, right?

thanks

**Comment by mangui** [comment]
i'm affraid it is not possible to invoke Flash FullScreen from JS:
http://stackoverflow.com/questions/8309086/calling-as3-fullscreen-with-javascript

**Comment by Levi0701** [comment]
Thanks mangui, I'm trying to simulate a user click event and try to fulfill this effect.
