### ISSUE TITLE
How to make the ts file

### ISSUE THREAD

**Issue by zawao** [mangui/flashls#240]
Hi mangui,

For example, if the ts file written in this way,

http://sample.com/stream.m3u8:
#EXTM3U
#EXT-X-VERSION:2
#EXT-X-ALLOW-CACHE:NO
#EXT-X-TARGETDURATION:10
#EXT-X-MEDIA-SEQUENCE:1
#EXTINF:10,
//delivery.cdn.com/output_00001.ts
#EXTINF:10,
//delivery.cdn.com/output_00002.ts

generated URL
http://sample.com//delivery.cdn.com/output_00001.ts

Is it possible to set the scheme(http or https) of m3u8?
http://delivery.cdn.com/output_00001.ts

thanks

**Comment by mangui** [comment]
off topic, please refer to HLS spec
https://tools.ietf.org/html/draft-pantos-http-live-streaming-14
