### ISSUE TITLE
Can i play m3u8 of Ustream?

### ISSUE THREAD

**Issue by grigione** [mangui/flashls#241]
I have following for example
http://iphone-streaming.ustream.tv/uhls/3064708/streams/live/iphone/playlist.m3u8
there is any mode to play it with your plugin?

**Comment by well0nez** [comment]
No, you can't.

Crossdomain is set for ustream servers only.
Btw: you could have checked it yourself:
http://www.flashls.org/latest/examples/osmf/GrindPlayer.html?src=http://iphone-streaming.ustream.tv/uhls/3064708/streams/live/iphone/playlist.m3u8

Just read the readme
