### ISSUE TITLE
live buffering 

### ISSUE THREAD

**Issue by well0nez** [mangui/flashls#247]
Hi.

Is there any special parameter to enable the seeking of already buffered data  (specially if i buffer a long time)?

I use Grindplayer with flashls, and when i'm playing a teststream there is no bar for seeking and the readme just confuses me.

thanks.

**Comment by mangui** [comment]
if you want to enable seeking in live stream with Grindplayer, you need to set your stream type to DVR
refer to http://osmfhls.kutu.ru/docs/grind/

this will enable DVR on live playlists:
https://github.com/mangui/flashls/blob/dev/src/org/mangui/osmf/plugins/HLSMediaElement.as#L150-L155

**Comment by well0nez** [comment]
thanks, i set the streamType to dvr, but it only displays 15 seconds of buffering and i'm not able to seek.
something i miss? or do the streamserver needs to have dvr enabled? because i want to seek the already buffered data!

**Comment by well0nez** [comment]
even if i pause, the buffer is not getting bigger (only 15 seconds always), and i cant seek

**Comment by mangui** [comment]
plz check with chromeless player, it should work. for the rest most probably it should be a GrindPlayer limitation.

**Comment by well0nez** [comment]
Thank, i will check it and report it then

**Comment by mangui** [comment]
well, firstly you need to check your playlist and ensure that the live sliding window is configured as per your needs

**Comment by mangui** [comment]
question answered, no additional feedback, closing
