### ISSUE TITLE
Wrong video aspect ratio, width and height

### ISSUE THREAD

**Issue by aimnadze** [mangui/flashls#248]
I have a live stream video with the resolution 704x578. Both VLC and ffmpeg show this. Bute flashls in the event onVideoSize shows 768x576. What can be causing it? Is there a workaround to set the video size manually?

**Comment by archilimnadze** [comment]
I'm using 0.4.0.4 version.

**Comment by mangui** [comment]
@archilimnadze,  I don't see how I could help with such report ... 
could you provide debug logs ?

**Comment by mangui** [comment]
no log, no help

**Comment by ghost** [comment]
Can you, please, play the following URL in chromeless example page: http://188.169.178.234:8080/CHANNEL826/bitrates.m3u8

I get the following output in browser console:

```
onFragmentPlaying(): metrics:0 sn:16859435 cc:0 video_width:704 video_height:576 tags:#EXTINF:15,
VM169:1 INFO:Video decoding:software
onVideoSize(), 1024x576
onVideoSize(),resize stage to 1024x576
```

So, my question is what makes difference between the 704x576 and the 1024x576 resolutions? I haven't seen any other players doing this way. Maybe the stream is somewhat odd or flashls misses some conditions.

Thanks in advance!

**Comment by phloxic** [comment]
@aimnadze - flash hls actually does the best thing[tm] because it obeys the display aspect ratio given:

```
$ ffprobe -v warning -select_streams V \
-show_entries stream=display_aspect_ratio,sample_aspect_ratio http://188.169.178.234:8080/CHANNEL826/BITRATE0/playlist.m3u8
[PROGRAM]
[STREAM]
sample_aspect_ratio=16:11
display_aspect_ratio=16:9
[/STREAM]
[/PROGRAM]
[STREAM]
sample_aspect_ratio=16:11
display_aspect_ratio=16:9
[/STREAM]
$ ffprobe -v warning -select_streams V \
-show_entries stream=display_aspect_ratio,sample_aspect_ratio http://188.169.178.234:8080/CHANNEL826/BITRATE1/playlist.m3u8
[PROGRAM]
[STREAM]
sample_aspect_ratio=16:11
display_aspect_ratio=16:9
[/STREAM]
[/PROGRAM]
[STREAM]
sample_aspect_ratio=16:11
display_aspect_ratio=16:9
[/STREAM]
```

Looks like a pre-treated 16:9 anamorphic PAL stream - originally 720x576 with 16:11 sample aspect ratio with the analogue overscan cropped off.
Flash on its own is ignorant of display aspect ratio and would the _wrong_ thing in this case.

**Comment by ghost** [comment]
Thanks, now I get the idea. Is there a way to somehow override this?

**Comment by phloxic** [comment]
@aimnadze - actually, by my own logic what you're describing should not happen (as long as chromless sets/leaves `scale` at `default` (https://helpx.adobe.com/flash/kb/flash-object-embed-tag-attributes.html#main_Optional_attributes), and indeed it doesn't for me at http://www.flashls.org/latest/examples/chromeless/?src=http%3A%2F%2F188.169.178.234%3A8080%2FCHANNEL826%2Fbitrates.m3u8 - and if I enable debug logging the console shows `DEBUG:AVC: width/height:704/576`.
