### ISSUE TITLE
Scheme relative uri for media files in m3u8.

### ISSUE THREAD

**Issue by un1024** [mangui/flashls#252]
I have tried to abbreviate scheme from media file URl in m3u8, but it's failed to generate media file URL in this plugin.

For example, specified in m3u8:
```
//medifile.com/media01.ts
```
I expected that the scheme(http/https) are complemented. But not... :sob: 

From RFC:

**HTTP Live Streaming draft-pantos-http-live-streaming-13**
https://tools.ietf.org/html/draft-pantos-http-live-streaming-13
<pre>
 A URI in a Playlist, whether it is a URI line or part of a tag, MAY
 be relative.  Relative URIs MUST be resolved against the URI of the
 Playlist file that contains it.
</pre>

**Uniform Resource Identifiers (URI): Generic Syntax**
http://tools.ietf.org/html/rfc2396
<pre>
5. Relative URI References
...
relativeURI   = ( net_path | abs_path | rel_path ) [ "?" query ]
...
net_path      = "//" authority [ abs_path ]
</pre>

And iOS player can play the m3u8 with this scheme relative uri.
So could you support scheme relative uri by this plugin, please?

**Comment by mangui** [comment]
@un1024 plz check with latest flashls/dev, such URI should work now

**Comment by kakawaha-yjp** [comment]
@mangui  It has worked fine for my expection! :laughing: Thank you so much!

**Comment by mangui** [comment]
great, closing
