### ISSUE TITLE
How can I reduce the latency (reducing buffer size?)

### ISSUE THREAD

**Issue by jomeier** [mangui/flashls#254]
Hi mangui,

I'm working on a live hls streaming solution where I stream from a webcam to the browser. I'm using ffmpeg for creating the hls stream, nodejs as http server. ffmpeg itself introduces a rather small latency (around 200ms). 

The delay from the output of ffmpeg to the browser window with mediaelement.js plus HLS streaming introduces a delay from around 1-2 seconds which is significant too high for my application.

I saw on your github page, that there are options for reducing the buffer size of your hls plugin. I can't find any description of how I must costumize mediaelement.js to access the hls options. 

Could you give me/us an example of how the settings for your hls plugin can be accessed by javascript or the video tag for the mediaelement.js player? I saw, that your plugin is included there since a few months.

I'm specially interested in the parameter 'hls_minbufferlength'.

Best regards,

Josef

**Comment by mangui** [comment]
Hi @jomeier 
mediaelement does not support customizing HLS option.
you could do it with OSMF based player or FlowPlayer.
low latency with live HLS is not only a matter of customizing min buffer length (described here: https://github.com/mangui/flashls#configuration) , it is mostly an issue with setting up small fragment duration. and also according to HLS spec, it is not recommended to start playback less than 3 fragments from the edge of the playlist (this is what flashls is doing)
http://tools.ietf.org/html/draft-pantos-http-live-streaming-14#section-6.3.3
https://github.com/mangui/flashls/blob/dev/src/org/mangui/hls/stream/StreamBuffer.as#L108

mangui

**Comment by jomeier** [comment]
Hi @mangui,

thanks for your answer.

I want to use hls streaming for an application in our LAN and need very low latency for videos. I already set the fragment size to 0.2 seconds. It works great (had to reduce the GOP distance in ffmpeg before).

Do you have any idea if there's a workaround in mediaelement for costumizing the HLS option? Would appreciate that a lot.

Best regards,

Josef

**Comment by mangui** [comment]
Hi @jomeier , I would first recommend you to try with another player with which you could easily tweak minbufferlength, to see if you could get any improvement with fine tuning.
you could use chromeless for example.
then for mediaelement, the idea would be to pass params through FlashVars, interpret them and pass them to flashls during player init.
see how it is done in FlowPlayer : 
https://github.com/mangui/flashls/blob/dev/src/org/mangui/flowplayer/HLSStreamProvider.as#L79-L92

flashVars are available in _model.config with FlowPlayer.
but you could retrieve them like explained here : http://www.permadi.com/tutorial/flashVars/indexAs3.html

cheers,
Mangui
