### ISSUE TITLE
failure when switching from TS with audio to TS without audio

### ISSUE THREAD

**Issue by alanra** [mangui/flashls#256]
Hi folks. We've noticed that when a playlist transitions from a set of TS segments with audio to a set without audio, the player breaks. Here's a sample clip to show the issue in the Chromeless player:

http://demo.theplatform.com/dev/m3u8/flashls/case1/master.m3u8

This points to two variants that have ~10 seconds of content with an audio track followed by ~18 of content without audio, followed by ~15 of content with audio. On iOS devices, the content plays as expected. However, on flashls, it fails.

Eventually we also want to suppose the following:

http://demo.theplatform.com/dev/m3u8/flashls/case2/master.m3u8

This is the same as above, but with a EXT-X-MEDIA track for audio: however, this currently doesn't play at all in flashls. It's fine on iOS devices. We're working on a server-side ad insertion solution where we might have different mixes of multi-audio HLS and non-multi-audio HLS, so these different combinations are important for us to support. Thanks in advance.

**Comment by mangui** [comment]
@alanra plz recheck with latest flashls/dev. I fixed an Exception happening with your playlist.
first playlist should be working (but there might be some issues with your fragment timestamp, i didn't dig into it but the reported media position seems a bit strange)

regarding your second playlist : there is a video PID in your alt audio track ... this is not supported. if you remove this video PID it should work in theory.

cheers,
Mangui

**Comment by alanra** [comment]
Thanks Mangui, I'll verify once this makes it out to http://www.flashls.org/latest/examples/chromeless/.

The second playlist is a challenge for us: it comes up when we have a main content playlist that's been encoded with alternate audio and we're doing dynamic ad insertion, but the ad to insert has not been encoded with alternate audio. In this case, for the main content alternate audio track, we just want to put in the video fragments for the ad, and then the player would just play the audio PID from that TS, and not the video. This works on iOS devices but not on flashls.

In cases where we're encoding both the content and the ad, we can control for this: but in other cases we don't control this encoding. Can you suggest any workarounds, or the level of effort in changing flashls to ignore the video PID if you've got an audio-only track?

**Comment by mangui** [comment]
this would require some changes in DemuxHelper and TSDemuxer to tell TS demuxer to ignore video PID if loading an alternate audio track. a couple of hours to develop and test

**Comment by alanra** [comment]
Well, I for one would be a fan of this change :) I can certainly give you plenty of test content if you need it.

**Comment by alanra** [comment]
I've verified the fix in the latest player. I'll open a separate topic on being able to use a TS with a video PID in an audio track. Thanks again.
