### ISSUE TITLE
No seeking for DVR

### ISSUE THREAD

**Issue by DannyZB** [mangui/flashls#259]
DVR videos display as "live" without a seek bar.
Why is that?

I use the grindr demo for a video

**Comment by DannyZB** [comment]
if you want to enable seeking in live stream with Grindplayer, you need to set your stream type to DVR
refer to http://osmfhls.kutu.ru/docs/grind/

this will enable DVR on live playlists:
https://github.com/mangui/flashls/blob/dev/src/org/mangui/osmf/plugins/HLSMediaElement.as#L150-L155

I assume this answers this question.
if it does then please make it clearer in the README (:

p.s. If it doesn't would like to know

**Comment by mangui** [comment]
@DannyZB any PR welcomed to improve the README
tks
Mangui
