### ISSUE TITLE
404 for all internal segments spins forever, no error

### ISSUE THREAD

**Issue by dtniland** [mangui/flashls#262]
In the course of our testing we tried copying an m3u8 file to our local file system but didn't also move over all of the segments.  Here is the file:

http://delivery.support.theplatform.com/pdk_qa/PDK_AUTOMATION/m3u8/bipbop_16x9_variant.m3u8
(Let me know if this file isn't accessible).

The media is not expected to work; we are hoping to see an error at some point.  Unfortunately, not only is there no error, the process seems to spin forever, retrying the same segment url over an over, even after a new media has been loaded in.  If we hit the same m3u8 file again, it seems to just makes a new process that also spins forever so that now you have two processes spinning.

**Comment by mangui** [comment]
@dtniland it should be related to the fact that fragmentLoadMaxRetry is set to an insane value : 
https://github.com/mangui/flashls/blob/dev/src/org/mangui/hls/HLSSettings.as#L86

i will reduce it to 3...

**Comment by mangui** [comment]
closing, plz reopen if still happening, even with max retry set to 3
