### ISSUE TITLE
Issue with  short links

### ISSUE THREAD

**Issue by imdummyhelpme** [mangui/flashls#263]
when I use short links for streams then  error of "no computable source found error" is there any way to fix this I'm trying to use like goo.gl tinurl.com tiny.cc any help will be appreciated thanks

**Comment by mangui** [comment]
@imdummyhelpme which player are you using ?
some players are expecting m3u extension as per HLS spec:
http://tools.ietf.org/html/draft-pantos-http-live-streaming-14#section-4

OSMF : 
OSMF: https://github.com/mangui/flashls/blob/dev/src/org/mangui/osmf/plugins/loader/HLSLoaderBase.as#L46

**Comment by imdummyhelpme** [comment]
I tried almost all of the players using the examples at flash.org do you know which one might do the trick? Thanks in advance

**Comment by mangui** [comment]
chromeless player is not checking the url extension
