### ISSUE TITLE
Encrypted HLS mutually exclusive audio/video

### ISSUE THREAD

**Issue by towerz** [mangui/flashls#266]
While working on some issues on Clappr, we got an strange behavior when loading an encrypted HLS stream, related to issue clappr/clappr#425. The video loads normally, with no error messages on flashls log, and either the video or the audio plays correctly, never both at the same time. This still happens using the flashls chromeless player in the latest flashls/dev branch.

You can also reproduce this in the test page (http://flashls.org/latest/examples/chromeless/). Just load the stream url https://sslhls.m6tv.cdn.sfr.net/hls-live/livepkgr/_definst_/m6_hls_aes/m6_hls_aes_856.m3u8 as @irongomme reported in the aforementioned issue. Reloading the source (or the page) always get me the same result (either it plays the audio displaying a black frame or it plays the video without sound).

**Comment by towerz** [comment]
I can reproduce this error on OSX (10.10.3) in either Chrome, Firefox and Safari (latest versions). 

There were also reports for Chrome on Windows 7 and Linux.

I tested the same stream loading with a <video> tag on Safari and it works normally.

**Comment by towerz** [comment]
There were another report of this issue, and it seems that the problem only occurs when serving playlist and ts files over HTTPS. Without SSL, everything works fine.

What do you think about this?

**Comment by mangui** [comment]
@towerz from debug logs I could see that no audio PID is referenced in the PMT.
```
"DEBUG:TS: PAT found.PMT PID:256" chromeless
"DEBUG:TS: PMT found" chromeless
"DEBUG:TS: Selected video PID: 257" chromeless
"DEBUG:TS: no audio selected"
```

hence no audio will be parsed.

I checked the PMT : 

```
474100100002b0120001c10000fffff0001be101f000c083ed67ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
```

and it does not reference any audio PID. 
i added some logs to check the PIDs available and I can see that there are some data available on PID 258. it might be audio data (as I can hear some audio while testing this URL on Safari) but strangely this PID is not referenced ( if it was we should see 102 somewhere in the dump above)

**Comment by towerz** [comment]
@mangui Thanks, I'll check why this is happening. I'll keep you updated on this.

**Comment by mangui** [comment]
@towerz any update on this one ?

**Comment by towerz** [comment]
@mangui sorry, haven't tested it yet. I didn't have the opportunity to finish my own test setup to isolate the problem, but I believe I'll have it by tomorrow. I was relying on external HLS streams that I cannot guarantee they are 100% compliant and could not reach a conclusion.

**Comment by towerz** [comment]
Seems like v0.4.1.0 fixed this behavior even with missing PIDs. Thanks @mangui!

**Comment by mangui** [comment]
yes, PMT will be reparsed if any unknown PID is found in between, this helps recovering such cases.
