### ISSUE TITLE
FlashLS crashes compiled GrindPlayer

### ISSUE THREAD

**Issue by DannyZB** [mangui/flashls#268]
Even though the plugin works with your included version of grind player , 
when trying to use a version i compiled here ( from the newest source ) the player just doesn't load whenever I include the plugin.

1.) Is there an issue ?
2.) How did you build the grind player included here ?

( The built swf is larger than the one included in the examples - which works )

**Comment by DannyZB** [comment]
https://www.seedr.co.il/dev/grind/examples/osmf/GrindPlayer.html?src=http%3A%2F%2F184.72.239.149%2Fvod%2Fsmil%3ABigBuckBunny.smil%2Fplaylist.m3u8#

**Comment by mangui** [comment]
looks like there are some missing classes with your recompiled player.
check with flash debug, it is obvious
VerifyError: Error #1014: cannot find org.osmf.media::PluginInfo class

**Comment by DannyZB** [comment]
Grind was build per their instructions and loads everything else properly,
there were no build errors either

How did you compile it ?

**Comment by mangui** [comment]
RTFM
https://github.com/mangui/flashls#building

**Comment by DannyZB** [comment]
of course i read the FM !
Those are instructions for building FlashLS, not how you compiled GrindPlayer

Anyway , when i find the cause i'll write here , maybe make specific instructions for the docs

**Comment by mangui** [comment]
sorry I was not clear about that.
I didn't recompile GrindPlayer, i took it off the shelves.

**Comment by DannyZB** [comment]
apparently there is a version mismatch there with osmf.swc .. not sure how i fixed it yet , will make it clear when i have a clue why recompiling flashls with flash 10.2 target worked ( maybe grind player has incorrect build instructions )

Is there any advantage of newer flash targets in regards to video quality/playback ? ( as far as you know )

**Comment by mangui** [comment]
no, I doubt you will see any advantages by targeting a new flash release.
