### ISSUE TITLE
Google Cloud Storage Cross Domain Policy Access.

### ISSUE THREAD

**Issue by JanSunavec** [mangui/flashls#274]
Hi all

Can someone create videojs flashls version and allow domain?
Security.allowDomain(storage.googleapis.com);

Because it's not possible put crossdomain.xml in root directory.
I just don't know how to do that by my self. I'll really appreciate it. Thanks.

  Jan

**Comment by mangui** [comment]
sorry, we don't do personalization work. you should consider compiling videojs-swf by yourself, it is pretty straightforward, 2 commands needed
https://github.com/mangui/video-js-swf#installation
