### ISSUE TITLE
Ignore any video PID when loading an alternate audio track

### ISSUE THREAD

**Issue by alanra** [mangui/flashls#275]
I've moved this request from issue #256 to be tracked separately.

We do dynamic ad insertion for HLS, and sometimes we have a content HLS with alternate audio tracks that needs to be combined with ads that don't have alternate audio.

In this case, we'll stick the lowest video bitrate of the ad into the appropriate alternate audio track. Here's a simple example:

http://demo.theplatform.com/dev/m3u8/flashls/case2/master.m3u8

However, If you load this into http://www.flashls.org/latest/examples/chromeless/ it doesn't play.

Mangui added a note on #256 for this:

"This would require some changes in DemuxHelper and TSDemuxer to tell TS demuxer to ignore video PID if loading an alternate audio track. a couple of hours to develop and test."

I could ask my developers to look at this: but I'd think you'd have a surer hand at these changes. Is there a chance you could make this change yourself to get it into the core distribution? I can give you as many test cases and samples as you need...

**Comment by mangui** [comment]
@alanra , plz recheck with latest flashls/dev, it should work now

**Comment by mangui** [comment]
your altaudio playlist is using discontinuity, this was not supported ... now it is. 
http://demo.theplatform.com/dev/m3u8/flashls/case2/master.m3u8 is now playing as expected with flashls/dev

**Comment by alanra** [comment]
You're a prince among men, Mangui. Thanks so much.
