### ISSUE TITLE
JSLoader resoureLoadingError _timer not instansiated.

### ISSUE THREAD

**Issue by shaharmor** [mangui/flashls#276]
Hi,

When using the JSLoader, if a download is aborted for any reason and we want to notify the player we have to use the same resourceLoadingError callback, but this function have a call to `_timer.stop()` which may not be running or declared at this point.

We should either wrap the `.stop()` call with a check that `_timer` exists and is running or introduce a different callback for abort errors.

[code link](https://github.com/mangui/flashls/blob/dev/src/org/mangui/hls/utils/JSURLStream.as#L120)

**Comment by mangui** [comment]
@shaharmor plz recheck with latest flashls/dev
