### ISSUE TITLE
startFromLevel not working in chromeless player

### ISSUE THREAD

**Issue by griley** [mangui/flashls#284]
I've been attempting to integrate the HLS playback engine into my organization's own player and noticed that I could not get the it to honor any setting of `startFromLevel` (https://github.com/mangui/flashls/blob/dev/src/org/mangui/hls/HLSSettings.as#L137).  

No matter what setting was used (e.g. -1, .5) the player always started with the first level.

I noticed that the [Chromeless player example](http://www.flashls.org/latest/examples/chromeless/) was not exhibiting this issue and started fiddling with it.  I discovered that if I comment out the `hls.play` call [in the manifest load callback](https://github.com/mangui/flashls/blob/dev/examples/chromeless/index.html#L393) then the sample also fails to honor any setting of `startFromLevel` and begins playback at the lowest quality when the play button is pushed.

**Comment by mangui** [comment]
I modify HLSSettings and put startFromLevel to 0.5 and i cannot reproduce, with latest chromeless/dev.
(in the meantime i fixed a couple of JS exception on metrics), but i don't think it should affect,
could you provide a log or post your metrics permalink ?

**Comment by griley** [comment]
Hi @mangui - I've uploaded a test case [here](http://georgeriley.net/ted/test/flashls/examples/chromeless/) after pulling from the latest from the dev branch.  

The only modification in my test case above was to comment out [this line](https://github.com/mangui/flashls/blob/e0f57cae8d3927ed3c4b534b72d394aea8da9681/examples/chromeless/index.html#L396), effectively disabling the autoplay behavior.

To see the issue, click the "Load" button to load the .m3u8 and then click the "Play" button to begin playback.  You'll see that the player immediately begins to stream from the lowest level, not from level matching download bandwidth.

**Comment by mangui** [comment]
my bad ... there was a state machine issue (pending for a while) in FragmentLoader....
thanks for finding it !
please recheck with latest flashls/dev

**Comment by griley** [comment]
That seems to have solved the issue.  Thanks for the quick turnaround (and your work on this project).
