### ISSUE TITLE
Don't fast skip last fragment

### ISSUE THREAD

**Issue by shaharmor** [mangui/flashls#285]
Hi,

When playing HLS and reaching the end of a live stream (the last TS availbable), if there is some error (404 for example) when fetching that TS, the player starts the exponential backoff retry for that TS until skipping it when fragmentLoadMaxRetry is reached.

If there is no other TS available at this point, the timeout for the retry is not reset and thus causing the play to make a lot of requests for this TS again and again.

We should change it to work so if the current fragment is the last one available, once you reach the maximum retry timeout, stay on that timeout until the next fragment.

**Comment by mangui** [comment]
@shaharmor plz recheck with latest flashls/dev, this should do the trick
