### ISSUE TITLE
Loading with seek value frame goes to 0 th frame

### ISSUE THREAD

**Issue by dubhaskar** [mangui/flashls#289]
Hi I am using your plugin in my OSMF player, I have requirement of quality switch where I want load new URL with some seek value, but this plugin loads url from 0 frame and starts playing first and then moves to seek value . 

please help I am struck on this issue from days.

Regards

Uday

**Comment by mangui** [comment]
plz check OSMF API firstly. OSMF based player should be able to start playback at any position
