### ISSUE TITLE
can't get chromeless example to play

### ISSUE THREAD

**Issue by chovy** [mangui/flashls#290]
I tried both node `http-server` and `python -m SimpleHTTPServer 8000`

Neither will make the example work for me.

**Comment by mangui** [comment]
I always use python -m SimpleHTTPServer 8080 when working locally, and it is working fine ...

**Comment by vrehak** [comment]
The example at http://flashls.org/flashls-0.4.1.0/examples/chromeless/ has broken html structure. The following code is placed between head and body elements:

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

It works in Google Chrome and IE, but does not work in Firefox.

**Comment by mangui** [comment]
should be fixed
