### ISSUE TITLE
Crash when playing HLS with data uri on 0.4.1.0

### ISSUE THREAD

**Issue by remi-piro** [mangui/flashls#292]
In LevelLoader.load() the test DataUri.isDataUri(url) is true so it jumps in _parseManifest.
And inside _parseManifest it uses _metrics which is not created => exception

**Comment by mangui** [comment]
@remi-piro thanks for reporting
I committed a blind fix, that should work fine, plz close if ok for u
cheers,
Mangui

**Comment by remi-piro** [comment]
This is fixing the crash, thanks
