### ISSUE TITLE
HLSEvent.MEDIA_TIME don't pass correct program_date.

### ISSUE THREAD

**Issue by alf-ytakada** [mangui/flashls#293]
Hi @mangui !

I need to use program_date, but HLSEvent.MEDIA_TIME event's HLSPlayMetrics instance has wrong program_datetime.

I fixed below code.
https://github.com/mangui/flashls/blob/dev/src/org/mangui/hls/model/Fragment.as#L67-L68
like this.

            data.writeObject(this.duration);
            data.writeObject(1);  // added. 
            data.writeObject(this.program_date);

and now it works!

Please check it.

Regards,

**Comment by mangui** [comment]
@alf-ytakada thanks for reporting, your fix is fixing program date time but it will break other fields :-)
plz check with latest flashls/dev and let me know how it behaves now

**Comment by alf-ytakada** [comment]
@mangui Thanks for your response.
I merged dev branch and confirmed the issue has been fixed.

thanks!
