### ISSUE TITLE
not work when playing 64kbps mp3

### ISSUE THREAD

**Issue by wlxhhr** [mangui/flashls#297]
128kbps mp3 file works fine,but when I play the same mp3 use 64kbps, It doesn't work

**Comment by mangui** [comment]
plz share debug logs and a playlist if you are really willing to get some help ...

**Comment by wlxhhr** [comment]
It' frozen and I can't get any logs...

**Comment by mangui** [comment]
even if it freezes, a bunch of debug logs should be available before the freeze, assuming the only diff in your test scenario is the mp3 file (128 vs 64 kbps).
no log no help.
