### ISSUE TITLE
BitrateSwitchCompleted detection

### ISSUE THREAD

**Issue by suuhas** [mangui/flashls#302]
Hi @mangui 

We have HLSEvent  [ HLSEvent.LEVEL_SWITCH ] which handles level switch,but we do not have one such event which lets us know when the level switch is completed .

Can we have a event like HLSEvent.SWITCH_COMPLETED which gets dispatched  as soon as level switch is successful . 

Regards
Suhas

**Comment by mangui** [comment]
you can get current playback level in FRAGMENT_PLAYING event if this is what you are looking for.
then you should know exactly when level switch is effective.
https://github.com/mangui/flashls/blob/dev/src/org/mangui/hls/event/HLSPlayMetrics.as#L7

**Comment by mangui** [comment]
@suuhas could you close unless anything is pending ?
