### ISSUE TITLE
hls_manifestloadmaxretry counter is not reset after properly loaded LIVE playlist

### ISSUE THREAD

**Issue by fixedmachine** [mangui/flashls#308]
When the `hls_manifestloadmaxretry` is set to a finite value, let say:
`hls_manifestloadmaxretry = 3`

and we are dealing with live playlist, the counter is not reset after proper load of the playlist. So when we've got situation like that:

1. liveplaylist.m3u8 - 200
2. requests for *.ts files (...)
3. another request for liveplaylist.m3u8 with next *.ts fragments of the live show ended up with 404 (`#1`)
4. retry request for liveplaylist.m3u8 ended up with - 200
5.  next *.ts
6. request for liveplaylist.m3u8 -> 404 (`#2`)
7. request for liveplaylist.m3u8 -> 404 (`#3`)
8. request for liveplaylist.m3u8 -> 200 
9. *.ts
10. liveplaylist.m3u8 -> 404 (`#4`) 
11. and we end up with I/O error here and end of transmission

But with live playlist we should reset the retry counter every time there is proper answer from the server. So in step `#4` the counter should be reset, same with step `#8` and then in step `#10` even if we get 404 we should retry another 3 times to get the playlist and then and only then after 3 unsuccessful attempts throw an error.

**Comment by mangui** [comment]
@fixedmachine long time no see !
agree, the counter should be resetted...

**Comment by fixedmachine** [comment]
Yeah, but I'm still here :) 

I've just found out that behavior because of the problems with our CDNs.

**Comment by mangui** [comment]
in fact currently retryCounter is only resetted in LevelLoader._loadCompleteHandler() which is used for main manifest only

it should be resetted here as well
https://github.com/mangui/flashls/blob/13ab89a94a00eee6594a06cecd1b32890caa55a3/src/org/mangui/hls/loader/LevelLoader.as#L176

**Comment by mangui** [comment]
should be fixed, plz recheck with latest flashls/dev

**Comment by fixedmachine** [comment]
Yep, it's fixed. Thank you! :)
