### ISSUE TITLE
Retry mechanism for first load of main m3u8 playlist

### ISSUE THREAD

**Issue by fixedmachine** [mangui/flashls#312]
I think that the retry mechanism should be used for the first load of main m3u8 playlist also. Now when there is a problem with loading the main playlist the error is thrown immediately without retry.

What do you think @mangui? Maybe it could be just optional setting?

**Comment by mangui** [comment]
I added retry mechanism for main manifest by default. following same logic than other level retry mechanism. plz check
cheers,
Mangui

**Comment by rwlodkowski** [comment]
It's working fine now. Thank you @mangui :)
