### ISSUE TITLE
AMF3 objects not being included in live stream

### ISSUE THREAD

**Issue by myboynoy** [mangui/flashls#313]
When I dynamically inject AMF3 data objects as part of the live stream from the streaming server, the messages do not get delivered to Flowplayer on the onCuePoint event handler. AMF3 works for RTMP and the F4M Flowplayer plugins, but not on this HLS plugin.

**Comment by mangui** [comment]
@myboynoy 
do you know how your AMF3 objects are muxed in the TS fragments ?

**Comment by dhassoun** [comment]
@myboynoy <https://github.com/myboynoy> what media server are you using?
The gist is it doesn’t do it on its own – you will need to route the data
over differently either from the client or at the server. We are working on
a blog post for how we did it recently.

**Comment by myboynoy** [comment]
I am using Wowza. Here is a brief snippet of what I'm doing server-side:

	public void callDataInject(IClient client, RequestFunction function, AMFDataList params)
	{
		String streamname = params.getString(PARAM1);
		String meth = params.getString(PARAM2);
		String id = params.getString(PARAM3);
		
		IMediaStream stream = client.getAppInstance().getStreams().getStream(streamname);

		long timecode = Math.max(stream.getAudioTC(), stream.getVideoTC());

		AMFDataMixedArray data = new AMFDataMixedArray();
		data.put("time", new AMFDataItem(timecode));
		data.put("name", new AMFDataItem(name));
		data.put("id", new AMFDataItem(id));
		data.put("meth", new AMFDataItem(method));
		data.put("type", new AMFDataItem("actionscript"));
		
		stream.sendDirect("onCuepoint", data);
		((MediaStream)stream).processSendDirectMessages();
	}

**Comment by dhassoun** [comment]
Check this out:
http://www.wowza.com/forums/content.php?322-How-to-convert-onTextData-events-in-a-live-or-VOD-stream-to-timed-events-(ID3-tags)-in-an-Apple-HLS-stream





*From:* myboynoy [mailto:notifications@github.com]
*Sent:* Monday, June 15, 2015 3:43 PM
*To:* mangui/flashls
*Cc:* David Hassoun
*Subject:* Re: [flashls] AMF3 objects not being included in live stream
(#313)



I am using Wowza. Here is a brief snippet of what I'm doing server-side:

public void callDataInject(IClient client, RequestFunction function,
AMFDataList params)

{

    String streamname = params.getString(PARAM1);

    String meth = params.getString(PARAM2);

    String id = params.getString(PARAM3);



    IMediaStream stream =
client.getAppInstance().getStreams().getStream(streamname);



    long timecode = Math.max(stream.getAudioTC(), stream.getVideoTC());



    AMFDataMixedArray data = new AMFDataMixedArray();

    data.put("time", new AMFDataItem(timecode));

    data.put("name", new AMFDataItem(name));

    data.put("id", new AMFDataItem(id));

    data.put("meth", new AMFDataItem(method));

    data.put("type", new AMFDataItem("actionscript"));



    stream.sendDirect("onCuepoint", data);

    ((MediaStream)stream).processSendDirectMessages();

}

—
Reply to this email directly or view it on GitHub
<https://github.com/mangui/flashls/issues/313#issuecomment-112219606>.

**Comment by mangui** [comment]
@myboynoy is there anything pending on this ticket ?

**Comment by mangui** [comment]
closing, plz reopen if anything pending
