### ISSUE TITLE
Question : The content playing on fetching first.ts file

### ISSUE THREAD

**Issue by bharathsn0812** [mangui/flashls#315]
Hi Mangui,

We are using chromelesshls and have set startFromLevel(0) in dev build.
Like to know if the player starts playing only once fully load of 0.ts file or is any parameter to enable to initiate playing while the half of 0.ts file is loaded.
Achieving this is very vital for slow internet speed countries.

I am newbie to HLS :)
Please correct me if i am wrong on concept.

**Comment by mangui** [comment]
if startFromLevel is defined, then flashls will do progressive buffering and playback should be able to start before first fragment will be completely loaded.
but it is not guaranteed, as flashls will only start the playback if minBufferLength is enough to guarantee a smooth playback.
you can tweak this key as well: 
hls_minbufferlength (default -1) - Minimum buffer length in seconds that needs to be reached before playback can start (after seeking) or restart (in case of empty buffer)
    If set to -1 some heuristics based on past metrics are used to define an accurate value that should prevent buffer to stall

**Comment by bharathsn0812** [comment]
Thanks for reply, We appreciate your work.

We are planning to provide individual quality switch by 
*parsing m3u8 file and reconstruction every chunk into different URL.
*This creates delay because link has to load , wait for onManifest , then seek(to value where switched), It is Hard Switching.
*Like to know if we can provide similar functionality from manguiHls internal API by having reference to individual chunk links also knowing its BITrate , so smooth switching can be implemented with minimum delay.

**Comment by mangui** [comment]
@bharathsn0812 i am not clear about your latest question, which is anyway not related to the initial ticket question, closing this one. plz reopen another one if anything unclear related to flashls
thanks
