### ISSUE TITLE
How to get NetStreamInfo values in Live Stream

### ISSUE THREAD

**Issue by shivamg705** [mangui/flashls#317]
I am using following code to get NetStreamInfo

var nsLoadTrait:NetStreamLoadTrait = mediaElement.getTrait(MediaTraitType.LOAD) as NetStreamLoadTrait;
ns = nsLoadTrait.netStream;
trace("netStreamInfo "+JSON.stringify(ns.info));

in console i am getting following value which is not correct
{"audioBufferByteLength":54806,"uri":null,"videoBufferByteLength":426078,"dataBufferByteLength":0,"audioBufferLength":3.909,"videoBufferLength":3.743,
"dataBufferLength":0,"SRTT":0,"audioLossRate":0,"videoLossRate":0,"metaData":null,"xmpData":null,"currentBytesPerSecond":0,
"byteCount":0,"resourceName":null,"maxBytesPerSecond":0,"isLive":false,"audioBytesPerSecond":0,"audioByteCount":0,
"videoBytesPerSecond":0,"videoByteCount":0,"dataBytesPerSecond":0,"dataByteCount":0,"playbackBytesPerSecond":159510.0636942675,"droppedFrames":5}

so please tell me how to get correct NetStreamInfo values.
Thanks in advance

**Comment by kalimba** [comment]
I use basically like ->

Add a listener to media element in some where
````
	mediaElement.addEventListener(MediaElementEvent.TRAIT_ADD, _onTraitAdd);
````

Listener method

````
	private function _onTraitAdd(event:MediaElementEvent):void
	{	
		if(event.traitType == MediaTraitType.LOAD)
		{
			var netStreamLoadTrait:NetStreamLoadTrait = mediaElement.getTrait(MediaTraitType.LOAD) as NetStreamLoadTrait;
			
			netStreamLoadTrait.addEventListener(
				LoadEvent.LOAD_STATE_CHANGE,
				function():void
				{
					netStream = netStreamLoadTrait.netStream;
				}
			);
		}
	}
````

Use a time ticker to check netStream object

Start a ticker

	public function initQosPanelTimer():void
	{
		var mainTimer: Timer = new Timer (1000, 0);
		mainTimer.addEventListener (TimerEvent.TIMER, _onMainTimerTickHandler);
		mainTimer.start();
	}


Get the netstream information

	private function _onMainTimerTickHandler(event:TimerEvent = null):void
	{
		if (netStream)
		{
			netStream.currentFPS.toFixed(2)
			netStream.info.droppedFrames
			netStream.bufferLength.toFixed(2)
			.
			.
			.
		}
	}

**Comment by mangui** [comment]
I am not changing anything there, netStreamInfo is computed by Flash itself.
I don't know exactly what your expectations are ? 
flashls use NetStream in Data Generation mode, you won't be able to get all values filled.

**Comment by mangui** [comment]
feedback provided, closing, plz reopen if anything unclear, thanks
