### ISSUE TITLE
The latest build stop work with GrindPlayer

### ISSUE THREAD

**Issue by irazhnov** [mangui/flashls#319]
Hi
I update the latest binary flashlsOSMF.swf and my GrindPlayer stop work. Player get an error "Stream  not found", May be you know the problem and have a short answer. Thank you.

**Comment by mangui** [comment]
does it mean that it works with a previous release ? if yes plz let me know the latest working one.

**Comment by irazhnov** [comment]
HI again,
yes  GrindPlayer  work perfect with  old release of flashlsOSMF.swf. Sorry i don't know the  number of build i start support project recently. i can send you a working binary of  flashlsOSMF.swf.
https://drive.google.com/file/d/0B06TpFhX8NgvajBXRnU3Z2RRQm8/view?usp=sharing
Now i'm trying to find out as well What is the difference with latest implementation.

**Comment by irazhnov** [comment]
Hi  mangui I'm really sorry about my message i found a problem, our  lib work perfect, but t not my head. Really Sorry i waste your time. Good luck with you excellent project.
