### ISSUE TITLE
Too often up/down quality switches with unstable connection bandwidth

### ISSUE THREAD

**Issue by fixedmachine** [mangui/flashls#32]
@mangui there is an annoying issue with unlimited up/down quality switches when the network conditions are unstable and the stream chunks are relatively short (~2s). This causing unpleasant effect for the viewer. I'm thinking about solution similar to this in dash.js:
https://github.com/Dash-Industry-Forum/dash.js/blob/master/app/js/streaming/rules/LimitSwitchesRule.js

What do you think about that?

**Comment by mangui** [comment]
closing, as redundant with #8
