### ISSUE TITLE
How to activate switching mode

### ISSUE THREAD

**Issue by scan** [mangui/flashls#320]
In the Readme and in some Issues here there's a talk about new switching modes. We're especially interested in the Instant and Smooth Switching mode. However, the documentation does not mention with any word how to actually set the mode. There's no configuration option for it.

We're using Grind Player and would like to be able to use the alternate switching mode soon.

**Comment by mangui** [comment]
@scan ATM these switching modes are available through API call only.
you can check the functional behavior by playing with the buttons on http://www.flashls.org/latest/examples/chromeless/
it might be possible to create HLSSettings to handle them though.

**Comment by scan** [comment]
It would be nice to have them in the HLS settings, since the normal use case (I imagine) is to set them at the initialisation of the player. It makes less sense to let the user choose (mostly because Instand and Smooth are the ones that are more intuitive to the user anyway).

Is it possible to set the mode before the player starts? Or do I have to set it once the player has started the HLS playback?

**Comment by griley** [comment]
> Also, I looked at the chromeless player above but couldn't find the option to switch the mode.

Ditto. I looked at the Chromeless example and [the code](https://github.com/mangui/flashls/blob/dev/src/org/mangui/chromeless/ChromelessPlayer.as#L97) but was unable to see any method to set the switching mode.

**Comment by mangui** [comment]
@griley 
these are the new methods:
https://github.com/mangui/flashls/blob/dev/examples/chromeless/flashlsAPI.js#L36-L46

**Comment by scan** [comment]
@mangui 
Unfortunately they're a bit ambiguous in naming and it's not explained how to use them to get the desired effect for the switching mode. From the naming, I assumed they're merely to set the stream bandwidth.

**Comment by mangui** [comment]
@scan 
the underlying effects are explained here:
https://github.com/mangui/flashls/blob/dev/API.md#hlscurrentlevel
https://github.com/mangui/flashls/blob/dev/API.md#hlsnextlevel
https://github.com/mangui/flashls/blob/dev/API.md#hlsloadlevel

**Comment by griley** [comment]
@mangui - I guess I'm not understanding [the adaptive streaming features](https://github.com/mangui/flashls#features).  These api calls (`currentLevel`, `nextLevel`, `loadLevel`) seem useful for overriding the adaptive algorithm if I would want to, but how do I direct the player to use the "smooth switching" mode outlined in the features?

**Comment by mangui** [comment]
this smooth switching is available through API only
if you want to smooth switch to auto mode, you do 
hls.nextLevel=-1
if you want to smooth switch to level 3, 
hls.nextLevel=3
...
with Chromeless you can already smooth switch by clicking on next level buttons in the test page.
it would be feasible to use smooth switching  with FlowPlayer,OSMF (this could be enabled by a new  HLSSettings key for example)

**Comment by griley** [comment]
Thanks for the explanation @mangui - I'll give it a try.

**Comment by griley** [comment]
Here are some observations based upon some experimentation and monitoring the levels being loaded along with buffer levels.

I'm building a custom player that uses the flashls.swc directly, so I have full access to the API.  The only settings that I'm customizing are the following:

```
HLSSettings.seekMode = HLSSeekMode.ACCURATE_SEEK;
HLSSettings.capLevelToStage = true;
HLSSettings.maxLevelCappingMode = HLSMaxLevelCappingMode.UPSCALE
HLSSettings.manifestLoadMaxRetry = 0;
HLSSettings.maxBufferLength = 30;
```

With these settings, flashls automatically selects the video variant (i.e. level) based upon the user bandwidth and the dimensions of the stage.

If I resize the video player's stage, flashls begins to load the level appropriate for the stage size however I notice that the current playback level does not actually change until all previously loaded fragments have completed playback.  So it appears that the default mode of the player's adaptive switching is 'bandwidth conservative switching'

Here's my logging showing the loading and playing of fragments just prior to and after resizing the player's stage:

```
Tue Jul 7 2015 02:54:39 PM.487 [INFO]  loaded fragment level: 4 sequence: 7 duration: 9958 size: 7 bandwidth: 673416
Tue Jul 7 2015 02:54:49 PM.216 [INFO]  playing audio fragment level: 0 sequence: 5 duration: 10.0078
Tue Jul 7 2015 02:54:49 PM.281 [INFO]  playing video fragment level: 4 sequence: 5 duration: 10
Tue Jul 7 2015 02:54:49 PM.614 [INFO]  loaded fragment level: 4 sequence: 8 duration: 9958 size: 8 bandwidth: 1121232
Tue Jul 7 2015 02:54:57 PM.111 [INFO]  resizing: stage w/h = 960/540 : video w/h = 640/360 : rect = (x=0, y=0, w=960, h=540)
Tue Jul 7 2015 02:54:59 PM.231 [INFO]  playing audio fragment level: 0 sequence: 6 duration: 10.0078
Tue Jul 7 2015 02:54:59 PM.236 [INFO]  switching to level: 5
Tue Jul 7 2015 02:54:59 PM.291 [INFO]  playing video fragment level: 4 sequence: 6 duration: 10
Tue Jul 7 2015 02:54:59 PM.986 [INFO]  level 5 loaded for loader type: 1
Tue Jul 7 2015 02:55:00 PM.867 [INFO]  loaded fragment level: 5 sequence: 9 duration: 9958 size: 9 bandwidth: 970268
Tue Jul 7 2015 02:55:09 PM.230 [INFO]  playing audio fragment level: 0 sequence: 7 duration: 9.9846
Tue Jul 7 2015 02:55:09 PM.281 [INFO]  playing video fragment level: 4 sequence: 7 duration: 10
Tue Jul 7 2015 02:55:09 PM.597 [INFO]  loaded fragment level: 5 sequence: 10 duration: 9958 size: 10 bandwidth: 1245312
Tue Jul 7 2015 02:55:19 PM.212 [INFO]  playing audio fragment level: 0 sequence: 8 duration: 10.0078
Tue Jul 7 2015 02:55:19 PM.299 [INFO]  playing video fragment level: 4 sequence: 8 duration: 10
Tue Jul 7 2015 02:55:20 PM.004 [INFO]  loaded fragment level: 5 sequence: 11 duration: 9958 size: 11 bandwidth: 1041520
Tue Jul 7 2015 02:55:29 PM.232 [INFO]  playing audio fragment level: 0 sequence: 9 duration: 10.0078
Tue Jul 7 2015 02:55:29 PM.288 [INFO]  playing video fragment level: 5 sequence: 9 duration: 10
``` 

I attempted to force 'smooth switching' by listening for 'HLSEvent.LEVEL_SWITCH' events and then setting `hls.nextLevel=-1` per @mangui's recommendation above.  That allowed switches to take place much quicker, but seemed to cause some janky-ness during transitions from levels.  Not sure if this is the proper way to set/use this property, but it's the only one I could see.

**Comment by mangui** [comment]
@griley if I understand correctly, what you would like to do is : 
smooth level switch upon Stage resize (i.e if the player uses level capping in auto quality mode, and the user switches to fullscreen, (quality level was capped to a low res) then you would like to smoothly uncap quality level to high res, without waiting for the end of buffer to be reached.
in order to do so, you could do the following : 

``` js
onStageResize() {
   if (stage resize up) {
      _hls.nextLevel=-1;
   }
}
```

**Comment by griley** [comment]
@mangui 

I misunderstood how the "nextLevel" works - i.e. it is a transient value that I do not have to manage and just setting it to -1 basically just triggers the smooth switch.  

I used it like the example you cited above and it worked as advertised thanks.

**Comment by mangui** [comment]
great. closing the ticket

**Comment by notanewbie** [comment]
I'm having issues using this method. Despite using the API as described, currentLevel, nextLevel, and nextLoadLevel remain the same. Here's the relevant code:

`hls.currentLevel = LEVELS[0].i
 hls.nextLevel = LEVELS[0].I
hls.nextLoadLevel = LEVELS[0].I`

What's the appropriate way to set these values?

Here's my page: https://notanewbie.000webhostapp.com/toggletest.html?https://fnurtmp-f.akamaihd.net/i/FNRADIO_1@92141/master.m3u8
