### ISSUE TITLE
Possible issue with pause/play button in Grindplayer

### ISSUE THREAD

**Issue by zuzzurro** [mangui/flashls#326]
When I open this page:

http://www.flashls.org/latest/examples/osmf/GrindPlayer.html

The player start in play mode, but the play/pause button shows the wrong state (it still shows the play icon and not the pause icon). This means also that the first time I click on the button, the player tries to start again, and from that moment onward it shows the right state.

**Comment by mangui** [comment]
indeed, will check.
knowing when this regression has been introduced would speed up the investigation.

**Comment by zuzzurro** [comment]
OK, as it seemed like a simple enough issue to test, I tried bisecting it. Here is the answer:

% git bisect bad
20f771a126b504de4f721bf2d0342fcdd90cb200 is the first bad commit
commit 20f771a126b504de4f721bf2d0342fcdd90cb200
Author: mangui <g.du.pontavice@gmail.com>
Date:   Tue Mar 10 15:04:55 2015 +0100

    update swf/swc
    related to #204

:040000 040000 3653934b27572000e23b5d67c1b7ecbce223346b 65bd0a32f144f9e0c9ba35b3ba141729d369c473 M      bin

I tested it by realoading the page each time after having cleared the browser's cache and seeing whether the player would start playing immediately, still having the play button shown.

**Comment by mangui** [comment]
@zuzzurro thanks for bisecting, indeed the issue was related to this commit : https://github.com/mangui/flashls/commit/b2b47d1b1d8aae5e24a2d8a5129f4355e79a9823
i fixed it the right way, plz recheck with latest flashls/dev
cheers,
Mangui

**Comment by zuzzurro** [comment]
if all bugs were this easy :-)
Checked and it seems to work.

**Comment by mangui** [comment]
great ! closing then ...
