### ISSUE TITLE
Replicating Flowplayer's 'scaling' in the Chromeless Player

### ISSUE THREAD

**Issue by chriswiggins** [mangui/flashls#332]
Hi all,

Absolutely love this player and it really does work incredibly well! I'm adding some functionality into Clappr which very simply extends ChromelessPlayer.as.

I've added scaling support into the Clappr RTMP plugin, and I'm wanting to do the same with this (basically the same as Flowplayer's `scaling` config option). Just wondering if someone can point me in the right direction as to what object(s) in the player I need to apply layoutMetadata (or similar) to?

I haven't done anything with Flash video yet, just OSMF so trying to figure this one out. Help greatly appreciated!

I'll either submit a PR against here if people want it in the Chomeless example or otherwise will just add it to Clappr's extension of the ChromelessPlayer.

Chris

**Comment by mangui** [comment]
Hi @chriswiggins currently Chromeless scaling is handled here,
https://github.com/mangui/flashls/blob/dev/src/org/mangui/chromeless/ChromelessPlayer.as#L537

using the following logic : https://github.com/mangui/flashls/blob/dev/src/org/mangui/hls/utils/ScaleVideo.as

compared to http://www.sitepoint.com/scaling-flowplayer-video-clip/
ScaleVideo implements a scaling 'fit'

but you could eventually extend this class to support other scaling modes.
cheers,
Mangui

**Comment by chriswiggins** [comment]
Awesome thanks @mangui - I think I'll modify the ScaleVideo class so that we can specify string-based scale modes.

Will keep you posted!
