### ISSUE TITLE
onMetaData

### ISSUE THREAD

**Issue by NicolasSiver** [mangui/flashls#335]
Hello,

So, there is no any `onMetaData` callbacks in NetStream.client - https://github.com/mangui/flashls/blob/58f08b49415eef3079e1dd9ec380af9e4b79de81/src/org/mangui/hls/stream/HLSNetStream.as#L68?

**Comment by mangui** [comment]
@NicolasSiver 
flashls (for its own purpose) is using listeners on other callbacks, not ```onMetaData```
but you are free to add any callbacks to _hls.stream object.

**Comment by NicolasSiver** [comment]
I have added, but It looks like, this callback isn't triggered for such type of stream.

**Comment by mangui** [comment]
indeed, ```onMetaData``` is usually generated by Flash itself.
flashls could eventually generate such kind of events, by injecting special FLV metadata tags into the NetStream. 
do you have the spec of the object provided by ```onMetaData``` callback ?

**Comment by NicolasSiver** [comment]
I didn't see any strict spec for it, but most of the time, in most cases, it includes video metrics like: dimensions, frame rate, codecs, etc. And in most cases, fields in the payload object are the same across various CDNs, etc.

Fields like (example):

	audiocodecid = mp4a
	audiodatarate = 128
	height = 432
	framerate = 30
	videocodecid = avc1
	videodatarate = 550
	width = 768

Dimensions are most helpful.

**Comment by mangui** [comment]
ok, you can get most of these infos with FRAGMENT_PLAYING event. (see HLSPlayMetrics).

**Comment by NicolasSiver** [comment]
ok ;)
