### ISSUE TITLE
Get Duration of the Live stream

### ISSUE THREAD

**Issue by NicolasSiver** [mangui/flashls#336]
Hello,

How to get duration of the live stream?

Via `HLSEvent.MEDIA_TIME` - `event.mediatime.duration`, library provides only duration of the media playlist. Maybe we could calculate full duration of the live stream by multiplication:

    EXT-X-TARGETDURATION x EXT-X-MEDIA-SEQUENCE

**Comment by mangui** [comment]
if your live playlist is sliding, the only thing you could get is the duration of sliding live playlist. and the total playback duration. (event.mediatime.position+event.mediatime.live_sliding_main)
also you cannot assume that EXT-X-MEDIA-SEQUENCE starts at 0.

or you can put a custom tag in your playlist, and retrieve it by listening to FRAGMENT_PLAYING event. (HLSPlayMetrics.tag_list)

**Comment by NicolasSiver** [comment]
Thanks, It was helpful.
