### ISSUE TITLE
Get Bandwidth

### ISSUE THREAD

**Issue by NicolasSiver** [mangui/flashls#337]
Hello,

What is the best practice in getting current bandwidth? Use of `HLSEvent.FRAGMENT_LOADED` event?
Maybe it [could be added](https://github.com/mangui/flashls/blob/dev/src/org/mangui/hls/handler/StatsHandler.as#L61) to the [stats](https://github.com/mangui/flashls/blob/dev/API.md#hlsstats)?

**Comment by mangui** [comment]
current bw could be computed from ```HLSEvent.FRAGMENT_LOADED```, stats will contain overall bw stats.

**Comment by NicolasSiver** [comment]
@mangui what about idea to add bandwidth to `stats`? ;)

**Comment by mangui** [comment]
well you have bw related info in stats already
(ok there is a typo, it is bw not bitrate.)

  fragMinKbps : min fragment load bitrate
  fragMaxKbps : max fragment load bitrate
  fragAvgKbps : avg fragment load bitrate

**Comment by NicolasSiver** [comment]
Yes, they are fine, but what about _current_ bandwidth?
For example as a field: `fragKbps`

	var metrics : HLSLoadMetrics = event.loadMetrics;
	if(metrics.type == HLSLoaderTypes.FRAGMENT_MAIN) {
	 	_stats.fragKbps = metrics.bandwidth;
	}

P.S.
Also there is a small inconsistency:

Here you are calculating bandwidth with a _request_ time: https://github.com/mangui/flashls/blob/dev/src/org/mangui/hls/event/HLSLoadMetrics.as#L34

But here with a _loading_ time:
https://github.com/mangui/flashls/blob/dev/src/org/mangui/hls/event/HLSLoadMetrics.as#L34

Also bandwidth calculation from `HLSLoadMetrics.bandwidth` could be reused, just for better maintainability ;)

Also such round process will be much faster via type casting:

	public function get bandwidth() : int {
	    return size * 8000 / (parsing_end_time - loading_request_time);
	}

**Comment by mangui** [comment]
@NicolasSiver I will add a fragLastKbps in ```hls.stats```

**Comment by NicolasSiver** [comment]
:+1:
