### ISSUE TITLE
Interacting from JavaScript?

### ISSUE THREAD

**Issue by slhck** [mangui/flashls#338]
I am quite new to Flash development, so please bear with me.

1. Am I right assuming that there is currently no direct JavaScript API to FlasHLS?
2. If the answer to 1) is no, can I use/extend the JavaScript API from GrindPlayer to access FlasHLS-specific functions and variables? Or is it not possible to access the plugin's variables for security/encapsulation issues?

For example, let's assume that I want to play an HLS stream using FlasHLS and GrindPlayer, and after 10 seconds, through JavaScript, switch the quality. Is that currently possible, and if not, where would I have to start?

Thanks for a quick answer; your efforts into this project are much appreciated.

**Comment by mangui** [comment]
you should be able to control GrindPlayer through JS: http://osmfhls.kutu.ru/docs/grind/
but for level switching you will be limited to OSMF default switching mode: (instant quality switch in force mode, smooth quality switch when switching to auto mode)
you might use chromeless player for that:
it exposes a JS API 
https://github.com/mangui/flashls/blob/dev/examples/chromeless/flashlsAPI.js
there is no doc as such, but you can check the demo page

https://github.com/mangui/flashls/blob/58f08b49415eef3079e1dd9ec380af9e4b79de81/examples/chromeless/index.html#L366

then ```api.load(url)```...

```
api.setLoadLevel(3);
api.setLoadLevel(4);
```

**Comment by slhck** [comment]
That's very helpful, thanks.

**Comment by slhck** [comment]
Just a follow-up question: Can the actual FlasHLS OSMF plugin not be enhanced to offer its own JS API separate from GrindPlayer, or is that not possible at all?

The problem I see is that there's no user interface in the Chromeless player and it'd probably be more time consuming to program a nice-looking user interface than simply re-using GrindPlayer.
