### ISSUE TITLE
CDN url pass params error 

### ISSUE THREAD

**Issue by richard02110** [mangui/flashls#339]
Hi
sorry for bothering
I am trying to pass my m3u8 on CDN server, the url include two params.
this is my url sample
http://my.cdn.server.com/xxx/xxx.mp4/chunklist.m3u8?param1=fejwofejowf&param2=fjewojewjjf
but when I use grindplayer with flashls plugins they will cut the second one after the "&"
 
![screen shot 2015-07-16 at 15 53 21](https://cloud.githubusercontent.com/assets/4638474/8718059/7431b370-2bd3-11e5-97ba-b59fad5d3c2c.png)

sorry for bothering again, I'm not familiar with action script
hope somebody can give me some hints to solve the problem
thanks a lot

**Comment by NicolasSiver** [comment]
@richard02110  [encodeURIComponent](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent) should help you ;)

**Comment by richard02110** [comment]
Yes it works: )
@NicolasSiver thank you so much
