### ISSUE TITLE
Only a TS file is loaded with no load, help!!

### ISSUE THREAD

**Issue by ssvfdn** [mangui/flashls#341]
Warning: Domain 14.215.9.32 does not specify a meta-policy.  Applying default meta-policy 'master-only'.  This configuration is deprecated.  See http://www.adobe.com/go/strict_policy_files to fix this problem.

14.215.9.32  is cdn server

help!!!

**Comment by ssvfdn** [comment]
this m3u8 list

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:22
#EXT-X-PLAYLIST-TYPE:VOD 
#EXT-X-KEY:METHOD=AES-128,URI="http://url.com/video.key?hash=3b3b944e14182d1de5666462a1189209&KEY1=bf47f04ffb416cac0d5553b60271535c&KEY2=55b051eb",IV=0x0000000000000000

#EXTINF:12.929,
cWmPblG6QgkAAAAAGl7kklXWO_A229.mp4.ts?KEY1=bf47f04ffb416cac0d5553b60271535c&KEY2=55b051eb&hash=3b3b944e14182d1de5666462a1189209&start=0.000&end=12.929
#EXTINF:12.346,
cWmPblG6QgkAAAAAGl7kklXWO_A229.mp4.ts?KEY1=bf47f04ffb416cac0d5553b60271535c&KEY2=55b051eb&hash=3b3b944e14182d1de5666462a1189209&start=12.929&end=25.275
#EXTINF:10.844,
cWmPblG6QgkAAAAAGl7kklXWO_A229.mp4.ts?KEY1=bf47f04ffb416cac0d5553b60271535c&KEY2=55b051eb&hash=3b3b944e14182d1de5666462a1189209&start=25.275&end=36.119
#EXTINF:11.303,
cWmPblG6QgkAAAAAGl7kklXWO_A229.mp4.ts?KEY1=bf47f04ffb416cac0d5553b60271535c&KEY2=55b051eb&hash=3b3b944e14182d1de5666462a1189209&start=36.119&end=47.422

**Comment by mangui** [comment]
'a TS file is loaded with no load ?'
please report issues correctly if you are expecting any help.
