### ISSUE TITLE
Emergency switch down when fragment loading stalls

### ISSUE THREAD

**Issue by bharathsn0812** [mangui/flashls#342]
Hi Mangui

During Autolevel switch , when higher bit rate quality is being played. The player is not switching to lower quality if bandwith is decreased over the time/some other reason

from given log below we can see (From Google chrome)
media_w341986520_b480000_26.ts?token=8443926090	(failed)	video/mp2t	Other	5.9 KB	3.8 min	
26.ts have failed to load and took 3.8min to Load !

Was able to replicated same in chromelessplayer

Below is the netowork log this condition
Where the content play smoothly for sometime but all of a sudden on one fragment it takes more time to fetch

chunklist_w341986520_b336000.m3u8?token=8443926090	200	vnd.apple.mpegurl	Other	7.4 KB	296 ms	
chunklist_w341986520_b480000.m3u8?token=8443926090	200	vnd.apple.mpegurl	Other	7.4 KB	153 ms	
crossdomain.xml	200	text/xml	Other	448 B	116 ms	
media_w341986520_b336000_0.ts?token=8443926090	200	video/mp2t	Other	399 KB	5.32 s	
media_w341986520_b336000_1.ts?token=8443926090	200	video/mp2t	Other	464 KB	4.66 s	
media_w341986520_b336000_2.ts?token=8443926090	200	video/mp2t	Other	381 KB	4.27 s	
media_w341986520_b480000_0.ts?token=8443926090	200	video/mp2t	Other	547 KB	5.91 s
media_w341986520_b480000_3.ts?token=8443926090	200	video/mp2t	Other	522 KB	5.19 s	
media_w341986520_b480000_4.ts?token=8443926090	200	video/mp2t	Other	573 KB	5.36 s	
media_w341986520_b480000_5.ts?token=8443926090	200	video/mp2t	Other	603 KB	5.87 s	
media_w341986520_b480000_6.ts?token=8443926090	200	video/mp2t	Other	565 KB	5.37 s	
media_w341986520_b480000_7.ts?token=8443926090	200	video/mp2t	Other	723 KB	6.30 s	
media_w341986520_b480000_8.ts?token=8443926090	200	video/mp2t	Other	551 KB	6.16 s	
media_w341986520_b480000_9.ts?token=8443926090	200	video/mp2t	Other	499 KB	4.87 s		
media_w341986520_b480000_10.ts?token=8443926090	200	video/mp2t	Other	942 KB	8.29 s	
media_w341986520_b480000_11.ts?token=8443926090	200	video/mp2t	Other	553 KB	9.96 s	
media_w341986520_b480000_12.ts?token=8443926090	200	video/mp2t	Other	510 KB	3.66 s	
media_w341986520_b480000_13.ts?token=8443926090	200	video/mp2t	Other	617 KB	4.53 s	
media_w341986520_b480000_14.ts?token=8443926090	200	video/mp2t	Other	509 KB	5.01 s	
media_w341986520_b480000_15.ts?token=8443926090	200	video/mp2t	Other	618 KB	4.37 s	
media_w341986520_b480000_16.ts?token=8443926090	200	video/mp2t	Other	639 KB	5.43 s	
media_w341986520_b480000_17.ts?token=8443926090	200	video/mp2t	Other	775 KB	6.00 s								
media_w341986520_b480000_18.ts?token=8443926090	200	video/mp2t	Other	800 KB	5.79 s	
media_w341986520_b480000_19.ts?token=8443926090	200	video/mp2t	Other	549 KB	4.43 s	
media_w341986520_b480000_20.ts?token=8443926090	200	video/mp2t	Other	520 KB	4.53 s	
media_w341986520_b480000_21.ts?token=8443926090	200	video/mp2t	Other	710 KB	9.14 s	
media_w341986520_b480000_22.ts?token=8443926090	200	video/mp2t	Other	577 KB	5.81 s	
media_w341986520_b480000_23.ts?token=8443926090	200	video/mp2t	Other	561 KB	4.57 s	
media_w341986520_b480000_24.ts?token=8443926090	200	video/mp2t	Other	545 KB	3.99 s	
media_w341986520_b480000_25.ts?token=8443926090	200	video/mp2t	Other	558 KB	3.38 s	
media_w341986520_b480000_26.ts?token=8443926090	(failed)	video/mp2t	Other	5.9 KB	3.8 min	
media_w341986520_b480000_26.ts?token=8443926090	200	video/mp2t	Other	706 KB	8.88 s	

playlist.m3u8?token=8443926090	200	vnd.apple.mpegurl	Other	490 B	129 ms

**Comment by bharathsn0812** [comment]
This issues is consistent .

**Comment by mangui** [comment]
yes if the bandwidth suddenly drops while a fragment is being loaded, there is no emergency switch down.
a way to fix this could be to monitor the fragment loading, and if after a certain duration, loading is stalled, we should abort this fragment loading and force an emergency switch down.

this monitoring should be performed here : https://github.com/mangui/flashls/blob/dev/src/org/mangui/hls/loader/FragmentLoader.as#L151

**Comment by bharathsn0812** [comment]
Hi

I tested this issue with single quality URL

http://218.248.64.73:1935/vod/_definst_/smil:cds/187364_PC_Download.smil/chunklist_w2042544433_b336000.m3u8?token=8443926090

The issue is fragment load time taking.

But 3.8min consistent !! is there any paramter to limit fragment load time

media_w2042544433_b336000_35.ts?token=8443926090	200	video/mp2t	Other	468 KB	4.84 s	
media_w2042544433_b336000_36.ts?token=8443926090	200	video/mp2t	Other	381 KB	3.67 s	
media_w2042544433_b336000_37.ts?token=8443926090	(failed)	video/mp2t	Other	2.8 KB	3.8 min	
crossdomain.xml	200	xml	Other	542 B	539 ms	
a.png?0.45823744125664234	200	png	Other	3.2 KB	276 ms	
media_w2042544433_b336000_37.ts?token=8443926090	200	video/mp2t	Other	360 KB	6.12 s	
media_w2042544433_b336000_38.ts?token=8443926090	200	video/mp2t	Other	477 KB	5.76 s	
media_w2042544433_b336000_39.ts?token=8443926090	200	video/mp2t	Other	493 KB	5.56 s	
media_w2042544433_b336000_40.ts?token=8443926090	200	video/mp2t	Other	455 KB	5.21 s	
media_w2042544433_b336000_41.ts?token=8443926090	200	video/mp2t	Other	536 KB	6.39 s

**Comment by mangui** [comment]
no, not for the moment.

**Comment by bharathsn0812** [comment]
When TS file is loaded partially and made to reload same TS. This error is showed infinite time


WARN:TS: reparsing PMT, unknown PID found
VM103594:1 DEBUG:position/audio/video/NetStream bufferLength:608.20/0.00/0.00/0.08

**Comment by mangui** [comment]
should be working now, plz recheck on your hand

**Comment by bharathsn0812** [comment]
Working fine

**Comment by bharathsn0812** [comment]
Working fine when the content is in auto quality.
But when manually switch to highest bit-rate (hls_levels) and the network is capable of playing that speed
it stalls

Please check
Network logs Taken from chrome	
media_w855019756_b480000_16.ts?token=8443926090	200	video/mp2t	Other	639 KB	4.79 s	
media_w855019756_b480000_17.ts?token=8443926090	200	video/mp2t	Other	3.1 KB	33.53 s	
chunklist_w855019756_b1464000.m3u8?token=8443926090	200	vnd.apple.mpegurl	Other	7.8 KB	470 ms	
media_w855019756_b1464000_10.ts?token=8443926090	200	video/mp2t	Other	368 KB	5.23 s	
media_w855019756_b1464000_10.ts?token=8443926090	200	video/mp2t	Other	320 KB	5.23 s	
media_w855019756_b1464000_10.ts?token=8443926090	200	video/mp2t	Other	318 KB	5.23 s	
media_w855019756_b1464000_10.ts?token=8443926090	200	video/mp2t	Other	272 KB	5.25 s	
media_w855019756_b1464000_10.ts?token=8443926090	200	video/mp2t	Other	396 KB	5.21 s	
media_w855019756_b1464000_10.ts?token=8443926090	200	video/mp2t	Other	290 KB	4.81 s	
media_w855019756_b1464000_11.ts?token=8443926090	200	video/mp2t	Other	251 KB	4.93 s	
media_w855019756_b1464000_11.ts?token=8443926090	200	video/mp2t	Other	314 KB	4.93 s	
media_w855019756_b1464000_11.ts?token=8443926090	200	video/mp2t	Other	295 KB	4.93 s	
media_w855019756_b1464000_11.ts?token=8443926090	200	video/mp2t	Other	266 KB	4.94 s	
media_w855019756_b1464000_11.ts?token=8443926090	200	video/mp2t	Other	294 KB	4.93 s

**Comment by mangui** [comment]
@bharathsn0812 plz recheck with latest flashls/dev
issue should be fixed
