### ISSUE TITLE
M3U8 Stream works on Mac OS, Windows, but not iPad

### ISSUE THREAD

**Issue by nathank1989** [mangui/flashls#346]
I am trying to get our live Wowza stream to work with the example template provided for flowplayer. The stream works on desktops, I don't have an android, but it's not working on iPad or iPhone. On iPad i get a black (not gray) screen, like it loaded a black frame of the video, with the Play button. But several clicks and nothing happens, but the data indicator wheel keeps spinning.
The iPad is also on WiFi.

EDIT: Additionally my VOD file (an SMIL) only plays audio and video on desktop, but only audio, and not video, on iphone/ipad despite only one bitrate being defined in the SMIL
I'm no coder, but I try to get by. If you could help me figure this out, that would be awesome. :)

link to the example page: http://ssdcougars.tv/flashls-0.4.2.1/examples/flowplayer/

Cheers

**Comment by mangui** [comment]
flashls is integrated with flowplayer flash. Flash is not supported on IOS.
please refer to FlowPlayer docs
