### ISSUE TITLE
Stalling or artifacting on level switch when segments do not start with I-frame

### ISSUE THREAD

**Issue by hparra** [mangui/flashls#347]
On level switch, if the segment does not start with an I-frame, then video playback quality suffers. When using `Video` this translates into a still frame. When using `StageVideo` there is major artifacting. I've confirmed this with certain encodings and segmentation using Apple's _mediafilesegmenter_ tool and its `-start-segments-with-iframe`. Hardware-based playback, e.g. iOS and Roku, do not exhibit this problem.

The artifacting was observed with my [pivotshare/video-js-swf](https://github.com/pivotshare/video-js-swf/), which includes the FlasHLS v0.4.1.2 SWC and changes to always use `StageVideo`. The stalling was observed in lastest [mangui/video-js-swf](https://github.com/mangui/video-js-swf). Stock FlasHLS chromeless performs worse with same streams, but this may be due to some regression, as older versions perform better.

I suspect that FlasHLS plays next segment immediately from start, whether or not there is an I-frame at beginning of segment. Hardware-based players may be pre-checking segment and switching mid-segment at I-frame. I cannot confirm as I have no expertise in MPEG-TS, but if you could point me in a direction I can take a better look.

Please email me (check profile) if you would like test streams. Thanks. HGPA

**Comment by hparra** [comment]
I forgot to mention this only occurs with _auto switching_. Explicit level switching does not exhibit this behavior. See https://github.com/pivotshare/videojs-levels, which includes pivotshare/video-js-swf as dev requirement.

**Comment by hparra** [comment]
This is first seen in 9e3b56357a0ea4a2dd5c8d844e40e56c46a18c2b. Older commits play video as desired. Investigating.

**Comment by mangui** [comment]
@hparra could you share a playlist with segment no starting with an I-Frame ?

**Comment by hparra** [comment]
The following is a time-sensitive manifest. It should 200 for next 6-24 hours.

```
http://pivotshare5-vod.dcp.adaptive.level3.net/pivotshare-vod/CID-1427/manifest.m3u8?tlm=hls&streams=bbfe5a2d0c0e06323064488936134ea0_360.mp4.m3u8:879,bbfe5a2d0c0e06323064488936134ea0_480.mp4.m3u8:1579,bbfe5a2d0c0e06323064488936134ea0_720.mp4.m3u8:3179,bbfe5a2d0c0e06323064488936134ea0_1080.mp4.m3u8:5080&nva=20150817210806&token=0d28cf9bdf35f28270ea6
```

Best way to test is to set both `hls_startfromlevel` and `hls_seekfromlevel` to 0.

[Here is a reference player for pivotshare/video-js-swf](http://pivotshare-player-test.s3-website-us-east-1.amazonaws.com/) with the same manifest. I've set the above and turned on both debugs.

(The commit mentioned previous is not the problem, but it did stop exhibiting the problem for a few types of stream.)

**Comment by hparra** [comment]
Here is another playlist without starting I-frames  (not time sensitive)

```
http://pivotshare-public-vod.hls.adaptive.level3.net/tests/sklz-hls-apple-noiframestart/variant.m3u8
```

The reference VideoJS player in previous comment now plays this by default.

**Comment by mangui** [comment]
@hparra just curious you said that you cannot repro before https://github.com/mangui/flashls/commit/9e3b56357a0ea4a2dd5c8d844e40e56c46a18c2b but I can also reproduce with older release, for example
http://flashls.org/flashls-0.3.2/examples/chromeless/ 
i can still see video artifacts when auto switching.

**Comment by mangui** [comment]
anyway in case we switch to a new level and fragment does not start with an I-Frame, flashls would need to discard the frames in between, as anyway we cannot do anything with them.

**Comment by mangui** [comment]
@hparra you might recheck with latest flashls/dev it should reduce the nb of video artifacts on auto quality switch
instead you should see freezed frame until next keyframe is found.

**Comment by mangui** [comment]
closing as fixed

**Comment by hparra** [comment]
I created a complete fix for this at https://github.com/pivotshare/flashls/commits/rework-fragmentloader. Quite a bit of refactored/new code was required. It can be improved in several ways, but it is already in production. Let me know if you are interested in any sort of PR. Comments welcomed. I could not get it working with progressive buffering.

If the AES decryption can be refactored to use workers and/or become decoupled from the FRAME event, then things could possibly be more performant. Some tweaks to level control may also need to be made to improve performance when this sort of fixing is consistent. The current algorithm is too optimistic with level up at times.
