### ISSUE TITLE
Getting error when content is playing (Question) 

### ISSUE THREAD

**Issue by bharathsn0812** [mangui/flashls#348]
Hi Mangui

Sometime i will get error like
[.PPAPIContext]GL ERROR :GL_INVALID_VALUE : glTexSubImage2D: bad dimensions. 
when this occur, the audio will play seamlessly , but video will hang for few seconds
I use chromeless flash swf file

As i am not action script guy , i just like to know if this is my browser error?
Our team is using manguihls library to make player

Thanks and Regards
BHARATH

**Comment by mangui** [comment]
this error is reported by the browser itself, I cannot do anything about it
