### ISSUE TITLE
hls_usehardwarevideodecoder option and GPU usage

### ISSUE THREAD

**Issue by Hiroshi-p** [mangui/flashls#350]
@mangui,
I noticed flashls has hls_usehardwarevideodecoder option now and I have a few, hopefully very quick, questions about it.
1. Is this option related to decoding, but NOT for rendering?
2. Does this option work for video.js integration?
3. Am I correct that flahsls worked as if hlf_usehardwarevideodecoder=true before this option was introduced?

The reason I am asking these questions is that I encounter an issue that flahsls playback quality is not good enough with the combination of low-spec MacBook + our 60fps HLS content. The same machine may play back 60fps YouTube MP4 content with flash player mode much better. I have vague suspect that flash GPU acceleration (for rendering) is disabled with some reason when combined with flashls.

**Comment by hparra** [comment]
The `hls_usehardwarevideodecoder` is passed to NetStream. This is for decoding. The video-js-swf fork _does not_ use hardware rendering, as it does not use StageVideo. You may be interested in my fork for that: https://github.com/pivotshare/video-js-swf

**Comment by Hiroshi-p** [comment]
@hparra,
Thank you for the info. That is very helpful.
I am going to look at your project.

**Comment by Hiroshi-p** [comment]
@hparra,
Do you by any chance have a test site of of your binary like this one: http://www.flashls.org/videojs/flash_demo.html
I understand that I need to do more by myself in the end, but I wonder if I can try it quickly as the beginning.

**Comment by hparra** [comment]
@Hiroshi-p I don't. You can clone https://github.com/pivotshare/videojs-levels and `npm install` to get it as a dev dep. See README.

**Comment by Hiroshi-p** [comment]
@hparra - Thanks.
