### ISSUE TITLE
V0.4.2.1 version can not play pure video and pure audio

### ISSUE THREAD

**Issue by Lirui072037** [mangui/flashls#353]
Hi,
You five days ago to update the v0.4.2.1 version of the player, you can not play pure video and pure audio HLS address. For example: "http://1043.lssplay.aodianyun.com/myfm1015/1234.m3u8" this is pure audio HLS address, in your player can not broadcast.
Thank you

Lirui

**Comment by mangui** [comment]
@Lirui072037 I was able to repro the issue with your stream but for some reason it is not accessible anymore. could you re-enable it or share another one ? thanks in advance
cheers,
Mangui

**Comment by mangui** [comment]
@Lirui072037 please recheck with latest flashls/dev, it could help in case your stream signaling was broken.

**Comment by mangui** [comment]
closing as fixed
