### ISSUE TITLE
Question: How do I configure the "switching mode"?

### ISSUE THREAD

**Issue by tommyh** [mangui/flashls#359]
Sorry if this isn't the best place for this question.  It appears github is the main source of discussion for flashls, so I'll put it here but I'm more than happy to close it and take up the discussion somewhere else if needed.

The documentation refers the [3 "switching modes"](https://github.com/mangui/flashls/blame/dev/README.md#L19) which are possible:
* instant switching
* smooth switching
* bandwidth conservative switching

When I examine the [Configuration Options](https://github.com/mangui/flashls/blame/dev/README.md#L56) I don't see anything with the 3 switching modes.  I did a quick scan of the codebase too and an undocumented option didn't jump out at me.  Is there a way to set "INSTANT" vs "SMOOTH" vs "BANDWIDTH"?

Note: I do see a configuration option for `hls_smoothautoswitchonfpsdrop` which is a boolean.  If this is set to true it appears "smooth switching" will be used.  But there are 2 reasons my original question remains even with the presence of the `hls_smoothautoswitchonfpsdrop` property.
* If `hls_smoothautoswitchonfpsdrop`=false, what is the switching mode which gets used?  Instant or Bandwidth?
* `hls_smoothautoswitchonfpsdrop` can only be set to true/false, so how would I choose the 3rd switching mode option?

**Comment by griley** [comment]
It probably won't answer your questions, but I was discussing this topic as well in issue #320

**Comment by tommyh** [comment]
@griley - yes, that completely answers my question!  agreed than an HLSSetting would be very helpful, that way I wouldn't need to fork mangui/video-js.swf to get the "instant" mode feature.

thanks.  closing out the question.
