### ISSUE TITLE
A audio M3U8 can't play.

### ISSUE THREAD

**Issue by Jimmysh** [mangui/flashls#362]
link: http://lms.csytv.com/Live/118/live/livestream.m3u8

It can play in demo:
http://www.flashls.org/mediaelement/demo/mediaelementplayer-hls.html
http://www.flashls.org/videojs/flash_demo.html

but can't play in http://www.flashls.org/latest/examples/chromeless/

**Comment by mangui** [comment]
I checked your playlist, indeed it is audio-only, but a video PID is referenced in the PMT. hence it is reconsidered as being an audio/video playlist, and flashls is waiting for video frames to start appending data into the NetStream ... as there is no video packet at all in your playlist, playback is not working
I am suspecting the same happens with https://github.com/mangui/flashls/issues/353

**Comment by mangui** [comment]
@Jimmysh your stream should now be playable. but playback would start quicker by fixing your stream PMT and remove video signalling
