### ISSUE TITLE
MP3 HLS - Not working with JSLoader

### ISSUE THREAD

**Issue by shaharmor** [mangui/flashls#363]
Hi,

When using Flashls on a mp3 HLS stream with the JSLoader turned on, the player is stuck on:
`DEBUG: no ADTS header found, probing...`

When using native flash download, it works.

Any ideas?

**Comment by mangui** [comment]
@shaharmor 
that is quite odd, 
is it 100% reproducible ?
could you share debug/debug2 logs ?

**Comment by shaharmor** [comment]
Its 100% reproducible in the chromeless examples using this stream:
http://airtime1.febchk.org:8081/729ly/729ly/playlist.m3u8

here is log:
[Mon Aug 17 2015 18:42:35 GMT+0300 (IDT)] onHLSReady()
VM100:1 INFO:HLSNetStream:close
VM101:1 DEBUG:StreamBuffer flushed
VM102:1 INFO:HLSNetStream:close
VM103:1 DEBUG:StreamBuffer flushed
VM104:1 DEBUG:add callback textLoaded, id:0
VM105:1 DEBUG:cancel any manifest load in progress
VM107:1 DEBUG:JSURLLoader.load:http://airtime1.febchk.org:8081/729ly/729ly/playlist.m3u8
(index):343 [Mon Aug 17 2015 18:42:43 GMT+0300 (IDT)] load URL http://airtime1.febchk.org:8081/729ly/729ly/playlist.m3u8
VM109:1 DEBUG:resourceLoaded
VM110:1 DEBUG:adaptive playlist:
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=48162
chunks.m3u8?nimblesessionid=72

VM111:1 DEBUG:switch to level 0
VM112:1 DEBUG:(re)load Playlist
VM114:1 DEBUG:add callback textLoaded, id:1
VM115:1 DEBUG:JSURLLoader.load:http://airtime1.febchk.org:8081/729ly/729ly/chunks.m3u8?nimblesessionid=72
VM117:1 DEBUG:resourceLoaded
VM118:1 DEBUG:level 0 playlist:
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-ALLOW-CACHE:NO
#EXT-X-TARGETDURATION:7
#EXT-X-MEDIA-SEQUENCE:104756
#EXTINF:6.008,
l_79_56645204120_104756.mp3?nimblesessionid=72
#EXTINF:6.008,
l_79_56645744855_104757.mp3?nimblesessionid=72
#EXTINF:6.008,
l_79_56646285590_104758.mp3?nimblesessionid=72
#EXTINF:6.008,
l_79_56646826324_104759.mp3?nimblesessionid=72

VM119:1 DEBUG:updateFragments: unknown PTS info for this level
VM120:1 DEBUG:Level 0 Live Playlist parsing finished: reload in 5382 ms
VM121:1 DEBUG:first level filled with at least 1 fragment, notify event
(index):343 [Mon Aug 17 2015 18:42:44 GMT+0300 (IDT)] new track list
(index):343 [Mon Aug 17 2015 18:42:44 GMT+0300 (IDT)] manifest loaded, playlist duration:24.03
VM134:1 INFO:HLSNetStream:play(-1)
VM135:1 INFO:HLSNetStream:seek(-1)
VM136:1 DEBUG:seek : requested position:-1.00,seek position:6.01,min/max buffer position:Infinity/-Infinity
VM137:1 DEBUG:StreamBuffer flushed
VM138:1 DEBUG:[SEEK_STATE] from IDLE to SEEKING
VM140:1 DEBUG:[PLAYBACK_STATE] from IDLE to PAUSED_BUFFERING
VM141:1 DEBUG:FPSController:playback stopped, stop monitoring FPS
VM143:1 DEBUG:[PLAYBACK_STATE] from PAUSED_BUFFERING to PLAYING_BUFFERING
VM144:1 DEBUG:FPSController:playback stopped, stop monitoring FPS
VM147:1 DEBUG:loadfirstfragment(6.007999999999999)
VM148:1 DEBUG:Loading       104756 of [104756,104759],level 0
VM149:1 DEBUG:add callback resourceLoaded, id:0
VM150:1 DEBUG:add callback resourceLoaded, id:1
VM151:1 DEBUG:loading fragment:http://airtime1.febchk.org:8081/729ly/729ly/l_79_56645204120_104756.mp3?nimblesessionid=72
VM152:1 DEBUG:JSURLStream.load:http://airtime1.febchk.org:8081/729ly/729ly/l_79_56645204120_104756.mp3?nimblesessionid=72
5VM155:1 DEBUG:position/total/audio/video/NetStream bufferLength:6.01/0.00/0.00/0.00/0.00
VM164:1 DEBUG:resourceLoaded
JSLoaderFragment.js:43 encoding/toFlash:9/2
JSLoaderFragment.js:44 encoding speed/toFlash:4014kB/s/24082kB/s
VM165:1 DEBUG:probe fragment type
VM166:1 DEBUG:ID3 tag found, size/end pos:63/73
VM167:1 DEBUG:ID3 tag id:PRIV
VM168:1 DEBUG:ID3 timestamp found:56728851
VM169:1 DEBUG:ID3 len:73
VM170:1 DEBUG:ID3 tag found, size/end pos:63/73
VM171:1 DEBUG:ID3 tag id:PRIV
VM172:1 DEBUG:ID3 timestamp found:56728851
VM173:1 DEBUG:ID3 len:73
VM174:1 DEBUG:AAC/MP3/TS match:true/true/false
VM175:1 DEBUG:resourceLoaded and decoded
VM176:1 DEBUG:loading completed
VM177:1 DEBUG:Loading       duration/RTT/length/speed:672/653/36122/420 kb/s
VM178:1 DEBUG:AAC: extracting AAC tags
VM179:1 DEBUG:ID3 tag found, size/end pos:63/73
VM180:1 DEBUG:ID3 tag id:PRIV
VM181:1 DEBUG:ID3 timestamp found:56728851
VM182:1 DEBUG:ID3 len:73
9077VM183:1 DEBUG:no ADTS header found, probing...

**Comment by mangui** [comment]
@shaharmor you might recheck with latest flashls/dev, issue should be fixed now

**Comment by mangui** [comment]
closing as fixed
