### ISSUE TITLE
HLS Live - manifest isn't requests again if first one fails

### ISSUE THREAD

**Issue by shaharmor** [mangui/flashls#366]
Hi,

When using the JSLoader (Maybe even when using flash loader), if the first request for the manifest file fails, the player doesn't requests the manifest again (Should follow the default logic for failed requests).

**Comment by mangui** [comment]
Hi @shaharmor, are you talking about the main manifest or on level playlist ?

**Comment by shaharmor** [comment]
I only checked it with main one

**Comment by rwlodkowski** [comment]
@mangui I think that this is the same issue I've noticed in #312.

**Comment by mangui** [comment]
@fixedmachine you're right, let's stick to #312  as this one is a duplicate, closing it
