### ISSUE TITLE
Issue with Fragment Failures in Failover Streams

### ISSUE THREAD

**Issue by alanra** [mangui/flashls#375]
Hi. I was looking at the fixes for issues #14 and #170. What I've found is failover works great if there's an error fetching the variant playlist, but if there's an error fetching an individual chunk, there's no failover to the alternate playlist.

To repro:

try opening up http://demo.theplatform.com/dev/m3u8/willoween/sample_bad_variant.m3u8 in flashls chromeless

This master looks like the following:
# EXTM3U
# EXT-X-VERSION:3
# EXT-X-STREAM-INF:BANDWIDTH=279464,CODECS="avc1.66.30,mp4a.40.2",RESOLUTION=416x234

About_a_Will_o_ween_28219090_m3u8_video_416x234_168000_primary_audio_1_i_dont_exist.m3u8
# EXT-X-STREAM-INF:BANDWIDTH=279464,CODECS="avc1.66.30,mp4a.40.2",RESOLUTION=416x234

About_a_Will_o_ween_28219090_m3u8_video_416x234_168000_backup_audio_1.m3u8

The first stream doesn't exist. If you play this, flashls will correctly fail over to the second stream.

now try opening up http://demo.theplatform.com/dev/m3u8/willoween/sample_bad_chunk.m3u8 in flashls chromeless

observed: failure on the second chunk

in this case, the master looks like:
# EXTM3U
# EXT-X-VERSION:3
# EXT-X-STREAM-INF:BANDWIDTH=279464,CODECS="avc1.66.30,mp4a.40.2",RESOLUTION=416x234

About_a_Will_o_ween_28219090_m3u8_video_416x234_168000_primary_audio_1.m3u8
# EXT-X-STREAM-INF:BANDWIDTH=279464,CODECS="avc1.66.30,mp4a.40.2",RESOLUTION=416x234

About_a_Will_o_ween_28219090_m3u8_video_416x234_168000_backup_audio_1.m3u8

and both of these exist. but then in the primary playlist, you have this:
# EXTM3U
# EXT-X-VERSION:3
# EXT-X-TARGETDURATION:11
# EXT-X-MEDIA-SEQUENCE:1
# EXT-X-PLAYLIST-TYPE:VOD
# EXTINF:10.010,

About_a_Will_o_ween_28219090_m3u8_video_416x234_168000_primary_audio_1_00001.ts
# EXTINF:10.010,

About_a_Will_o_ween_28219090_m3u8_video_416x234_168000_primary_audio_1_00002_i_dont_exist.ts
# EXTINF:10.010,

About_a_Will_o_ween_28219090_m3u8_video_416x234_168000_primary_audio_1_00003.ts
# EXTINF:10.010,

About_a_Will_o_ween_28219090_m3u8_video_416x234_168000_primary_audio_1_00004.ts
# EXTINF:10.010,

About_a_Will_o_ween_28219090_m3u8_video_416x234_168000_primary_audio_1_00005.ts
# EXT-X-ENDLIST

the second segment will give a 404, which should trigger a switch to the backup variant: but that doesn't happen.

**Comment by mangui** [comment]
@leandromoreira tks for reporting, switching to redundant stream was not always working properly in this case... plz recheck with flashls/dev, issue should be fixed

**Comment by mangui** [comment]
related to #14

**Comment by mangui** [comment]
closing as fixed
