### ISSUE TITLE
m3u8 link not play

### ISSUE THREAD

**Issue by Josepdal** [mangui/flashls#377]
http://iphonelive.rtve.es/LA1_LV3_IPH/LA1_LV3_IPH.m3u8

Can you solve that?

**Comment by mangui** [comment]
this stream works providing that you have a crossdomain.xml setup properly
http://www.adobe.com/devnet/adobe-media-server/articles/cross-domain-xml-for-streaming.html
this file shall be hosted on http://iphonelive.rtve.es
