### ISSUE TITLE
How play HSL url while using wowza loadbalancer

### ISSUE THREAD

**Issue by shivamg705** [mangui/flashls#379]
I want to play this hls url http://192.168.2.97:1935/redirect/live-4684-e3635a0/stream_500k?scheme=m3u8 but i get GET http://192.168.2.97:1935/redirect/live-4684-e3635a0/chunklist_w537375126.m3u8 403 (Forbidden)  error.

can you tell me how can i play above url in our osmf based custom player.

**Comment by mangui** [comment]
I can't access your URL either. (URL not reachable) .
if you are able to access it and you still got a 403, then check your web server setup. 
and once your server is setup correctly, ensure that you also set a crossdomain.xml on this server as well for Flash Player to be able to access to the stream:
http://www.adobe.com/devnet/adobe-media-server/articles/cross-domain-xml-for-streaming.html
