### ISSUE TITLE
NetStream stepping

### ISSUE THREAD

**Issue by jfairley** [mangui/flashls#382]
I would like to expose `NetStream.step()` through this plugin, so that I can use it in [Clappr](https://github.com/clappr/clappr). I have experience working with `NetStream`, but primarily consuming RTMP.

Before I get started:
- When I'm done, what branch should I PR into?
- Is there any reason that I should not try this?
  - Maybe someone has already verified that stepping and HLS are oil and water.
  - Maybe you consciously decided _not_ to expose a `step()` function. If so, I'd love to know more.

Thanks!

**Comment by mangui** [comment]
hi @jfairley unfortunately NetStream.step() is not working in Data Generation mode 😢

**Comment by jfairley** [comment]
@mangui I'm not familiar with "Data Generation" mode. What is that?

**Comment by jfairley** [comment]
I'm curious about the specifics of how it does not work. Could you elaborate?

I ask, because in the player we've built here, and use for RTMP, when stepping, we understand that one can only step through the already-loaded buffer. If the user tries to step beyond the buffer, we play games (play, pause, seek back) to load more buffer.

**Comment by mangui** [comment]
NetStream in Data generation mode means that NetStream is used with FLV tags generated from memory. using [NetStream.appendBytes()](http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/net/NetStream.html#appendBytes%28%29)
this is the case in HLS, as FLV tags are generated in memory by transmuxing TS fragments.

stepping is following the same logic than seeking, 
plz refer to http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/net/NetStream.html#seek%28%29

When you call seek() on a NetStream in Data Generation Mode, all bytes passed to appendBytes() are discarded (not placed in the buffer, accumulated in the partial message FIFO, or parsed for seek points) until you call appendBytesAction(NetStreamAppendBytesAction.RESET_BEGIN) or appendBytesAction(NetStreamAppendBytesAction.RESET_SEEK) to reset the parser.
