### ISSUE TITLE
Levels: zero based?

### ISSUE THREAD

**Issue by NicolasSiver** [mangui/flashls#388]
I'm receiving `2` level (_HLSEvent.LEVEL_SWITCH_) from stream with 2 qualities/renditions.
I'm using `HLSSettings.startFromBitrate` feature.
Is it a bug, or levels are not zero based?
Thanks

**Comment by stevemayhew** [comment]
Levels are 0 based.

**Comment by NicolasSiver** [comment]
What I have in logs so:

```
DEBUG:adaptive playlist:
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=678000,RESOLUTION=768x432,CODECS="avc1.77.30, mp4a.40.2"
http://some.net/i/index_678_av-p.m3u8?sd=10&dw=100&rebase=on
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=198000,RESOLUTION=480x270,CODECS="avc1.66.30, mp4a.40.2"
http://some.net/i/index_198_av-p.m3u8?sd=10&dw=100&rebase=on
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=48000,CODECS="mp4a.40.2"
http://some.net/i/index_198_a-p.m3u8?sd=10&dw=100&rebase=on

DEBUG:start level :2
DEBUG:switch to level 2
```

**Comment by NicolasSiver** [comment]
Is there any setting or technic in library, to exclude only audio streams?

**Comment by mangui** [comment]
@NicolasSiver not clear what you are trying to achieve ? filter out audio only level so that they won't appear in hls.levels ?
FYI `HLSSettings.startFromBitrate`will use the level with the nearest bitrate, no matter it is a audio only level or not.
https://github.com/mangui/flashls/blob/dev/src/org/mangui/hls/controller/LevelController.as#L341

**Comment by NicolasSiver** [comment]
Yes, I thought about PR to add feature to the library: accept main manifest as a String.
But I think I will find workaround on another level ;)
Thanks for response.

**Comment by mangui** [comment]
you can eventually consider DataUri for manifest as a String ...
https://github.com/mangui/flashls/search?utf8=%E2%9C%93&q=DataUri
