### ISSUE TITLE
Segment Number by Date(ms)

### ISSUE THREAD

**Issue by NicolasSiver** [mangui/flashls#405]
Is this correct?

https://github.com/mangui/flashls/blob/dev/src/org/mangui/hls/model/Level.as#L104

Maybe:

```
if (fragments[i].data.valid && fragments[i].program_date >= program_date && fragments[i].program_date + 1000 * fragments[i].duration < program_date) {
     return (start_seqnum + i);
}
```

Also first check for this method can include case when program_date is higher that allowed to omit unnecessary iteration. If it's a case ;)

**Comment by mangui** [comment]
mmm doesn't look correct !
PR with test stream welcome

**Comment by mangui** [comment]
the test made is correct. now it will not iterate if program date is higher than highest program date
