### ISSUE TITLE
Endless chunk reloading without lowering bitrate

### ISSUE THREAD

**Issue by MixMasterMitch** [mangui/flashls#407]
I am experiencing an issue with the same chunk being reloaded endlessly after I significantly drop my connection speed. Specifically, these were my steps:
- Load the stream with a solid internet connection.
- Wait for the stream to be upgraded to the highest bitrate index
- Seek further into the video to induce buffering, then drop the connection down to 750KB/s.
- Observe the high quality chunk is attempted to be loaded over and over again but is cancelled and restarted each time after 4.5 seconds.
- Un-throttle internet connection
- Observe that a strange selection of high bitrate chunks are loaded (or canceled)
- Observe that lower bitrate chunks are loaded and video playback is restored.

I have had a hard time reproducing this issue, but captured a partial video of it, available here: https://www.dropbox.com/s/we9mf5x5eihdp8f/flashls%20bug.mov?dl=0

I think it is also worth noting that my cache was disabled.

My browser version: http://whatsmybrowser.org/b/JBYO0S4
flashls version: 0.4.3.4

**Comment by mangui** [comment]
Hi, that's interesting,
do you have a debug log to share ?
there might be a flow in the emergency switch down algorithm: 
https://github.com/mangui/flashls/blob/dev/src/org/mangui/hls/loader/FragmentLoader.as#L153-L195

if the bw suddendly drops, frag loading will be cancelled, and flashls will switch to a lower level.
this switch is achieved here : https://github.com/mangui/flashls/blob/dev/src/org/mangui/hls/loader/FragmentLoader.as#L185-L191
we fill load metrics value and dispatch a FRAGMENT_LOAD_EMERGENCY_ABORTED event
this event is catched by https://github.com/mangui/flashls/blob/dev/src/org/mangui/hls/controller/LevelController.as#L50
new level to be used for next fragment loading is then retrieved from here :
https://github.com/mangui/flashls/blob/dev/src/org/mangui/hls/loader/FragmentLoader.as#L191

maybe this level is too high in your case ... at least it would make sense to ensure that this new level is less than current level, just for sake of sanity. this would avoid that loop of errors

**Comment by mangui** [comment]
I would advise you to retry with the latest changes from flashls/dev and let me know if you still observe this behavior

**Comment by MixMasterMitch** [comment]
I have not been able to reliably reproduce this issue, but I will try several times and see if I can observe it abort a chunk load and drop down the level.

**Comment by MixMasterMitch** [comment]
I cannot 100% confirm that your change fixed the issue, but after following my procedure about 10 times, I had no issue. There was one instance where it seemed to abort a chunk load and quickly downgraded levels instead of getting stuck at the high level.
