### ISSUE TITLE
Event for playing quality level switch?

### ISSUE THREAD

**Issue by MixMasterMitch** [mangui/flashls#409]
Is there an event to detect when the quality level of the currently playing chunk changes? If I monitor the level loading, loaded, and switch events, I see that LEVEL_SWITCH events do not fire when I expect them to based on the documentation. If I play a video with good bandwidth, I load chunks at level 5, but the LEVEL_SWITCH only reports that I made it to level 5. Here is a video:

https://www.dropbox.com/s/axz8mh74vul11x6/LEVEL_SWITCH%20not%20accurate.mov?dl=0

**Comment by MixMasterMitch** [comment]
I have a temporary workaround of polling the stats object to get the autoLastLevel which works, but a dedicated PLAYING_LEVEL_SWITCH event would be preferred.

**Comment by mangui** [comment]
this is already provided by monitoring FRAGMENT_PLAYING event.
level info is retrievable from HLSPlayMetrics, https://github.com/mangui/flashls/blob/dev/src/org/mangui/hls/event/HLSEvent.as#L147

**Comment by MixMasterMitch** [comment]
Somehow I missed that! Thanks!
