### ISSUE TITLE
Video resize during chunk change

### ISSUE THREAD

**Issue by MixMasterMitch** [mangui/flashls#410]
When the video playback undergoes a level upgrade, the video has a noticeable resize to it. This video exemplifies it best:

https://www.dropbox.com/s/dm47vr4jjdctaet/Encoding%20resize.mov?dl=0

I am 90% confident that this is not encoding related, because I cannot notice the resize in Safari.

**Comment by mangui** [comment]
@MixMasterMitch 
it is up to your player to adjust to video width, height, or aspect ratio change.
you should listen to `EVENT.RESIZE`
https://github.com/mangui/flashls/blob/dev/src/org/mangui/chromeless/ChromelessPlayer.as#L542

**Comment by MixMasterMitch** [comment]
I will look into this more tomorrow, but in our player we always scale the video to fill the container. So a quality change should not cause the actual video to change size. And all of the playlists have the same aspect ratio, so aspect ratio shouldn't be the problem.

**Comment by MixMasterMitch** [comment]
Related to https://github.com/mangui/flashls/issues/418

This is no longer an issue. Was there a change in the last month that would explain why this is now resolved?

**Comment by mangui** [comment]
no
