### ISSUE TITLE
Issue: too many level manifest requests

### ISSUE THREAD

**Issue by NicolasSiver** [mangui/flashls#412]
I have discovered that library creates enormously many requests to level manifest, in case if it starts with retries.

At first, master manifest isn't available (segments also):

<img width="361" alt="screen shot 2015-10-19 at 5 26 31 pm" src="https://cloud.githubusercontent.com/assets/135263/10591940/f2ecd62e-7686-11e5-8e30-f849ad61bcc4.png">

**Comment by mangui** [comment]
is it live or VoD ?
having timestamps displayed would help as well

**Comment by NicolasSiver** [comment]
It's Live.
Manifest and segments isn't available ASAP, because stream just starts up.

**Comment by mangui** [comment]
logic is here
https://github.com/mangui/flashls/blob/dev/src/org/mangui/hls/loader/LevelLoader.as#L218-L228

if your playback position is close to the edge, the reload frequency will increase

**Comment by NicolasSiver** [comment]
Also, `HLSSettings.startFromBitrate` isn't honored in such case.
After some time, it starts switch process. (`index_678` -> `index_198`)

**Comment by NicolasSiver** [comment]
@mangui as you can see Reloads much more than it should be.

**Comment by mangui** [comment]
I can't tell, i don't have timings info

**Comment by NicolasSiver** [comment]
> DEBUG:Level 0 Live Playlist parsing finished: reload in 500 ms

**Comment by NicolasSiver** [comment]
Maybe minimal value should be `targetDuration / 2` or exact duration of first available segment in level manifest, not a 500 ms?
Because now, It's spamming ;)

**Comment by NicolasSiver** [comment]
@mangui I mean, your strategy works ok, but it creates many manifest requests, when streams starts.

After a small test:
https://github.com/mangui/flashls/blob/dev/src/org/mangui/hls/loader/LevelLoader.as#L223
`(_levels[level].duration - _hls.position)/2` -> ~ 0.58
`averageDuration` -> 1.161 (#EXTINF:1.161)

What do you think about this:
- Introduce Live start strategy
- Reload at average duration rate
- Start playback **only when manifest starts to grow** (more than 1 segment in level playlist)

**Comment by mangui** [comment]
@NicolasSiver , do  you mean you are using 1s fragment ?
that's a really small duration ... that is only valuable if you are targeting reduced latency.
in that case reloading often is the expected behaviour to ensure latency will be minimal ...
otherwise increasing fragment duration would be an option.

**Comment by NicolasSiver** [comment]
@mangui It's packaged in such way. It's hard to predict, how it could be packaged.
Anyway, very first segment, in most cases, **will be smaller than target duration**.

My main idea. Library shouldn't play level, until Level consists of 2 segments at least (I think it should work well).

**Comment by mangui** [comment]
ok. then using target duration instead if average duration should work in your case right?

**Comment by NicolasSiver** [comment]
Your latest change with average duration for initial playback check works Ok.
