### ISSUE TITLE
PLAYBACK_COMPLETE event not firing after seek near end

### ISSUE THREAD

**Issue by MixMasterMitch** [mangui/flashls#413]
If I start a video, and seek to the last couple of seconds, the PLAYBACK_COMPLETE event does not appear to fire.

Here is a video of the PLAYBACK_COMPLETE event firing when I seek to the last 20 seconds and then the PLAYBACK_COMPLETE event not firing when I refresh and see to the last 2 seconds:
https://www.dropbox.com/s/vcadu9750e9q560/PLAYBACK_COMPLETE%20bug.mov?dl=0

**Comment by MixMasterMitch** [comment]
I can repro this 100% of the time for some video urls, and not at all for other video urls. Therefore, I suspect the last chunk size could be a factor.

**Comment by mangui** [comment]
weird.
could you share a playlist ?

**Comment by MixMasterMitch** [comment]
This one will expire at some point, but should work for now: https://d1y6jrbzotnyjg.cloudfront.net/va/hls/playlist.m3u8?playlist=VEVOA%2FB00K9TD4IW%2FV22%2F93571c1a3e3a4fd3815f2e71268f270c%2Fmaster-playlist.m3u8&asin=B00K9TD4IW&source=cf&Expires=1445970324&Signature=VP9a-lXwIU8FMpKmzetWcoNDBUmyOTDabosAFawlmOuJExc7CdYQvyGnFhqcQfb9E3eOWmqd8Llku3f-GdJmHDZeMYA1MRKCQNgGKGxh0HeFxIqDhk~LUwnUGJoHlupEtxAuvJlMv8a0kUwHTzbFpSWJR6jtc8yj2vmmsSe1K2Y_&Key-Pair-Id=APKAJ62XWKZ35EOVO4XA

**Comment by mangui** [comment]
it is already expired

**Comment by MixMasterMitch** [comment]
I took it from this page on Amazon: http://www.amazon.com/gp/product/B00K9TD4IW

**Comment by MixMasterMitch** [comment]
If that isn't enough I can upload the full encoding (manifest, playlists, chunks) to dropbox

**Comment by mangui** [comment]
yes plz

**Comment by MixMasterMitch** [comment]
This should contain everything with the correct relative paths:
https://www.dropbox.com/s/8xjlhy8c5dwvjzo/purity-ring-fineshrine.zip?dl=0

**Comment by mangui** [comment]
@MixMasterMitch , plz check it should work fine now.

**Comment by MixMasterMitch** [comment]
The video ends correctly now, but it doesn't always start properly. About 50% of the time that I reload the player, I see the first frame of the video, but playback doesn't start. If I seek ahead, it plays from the new location without issue.

I am happy to dive deeper here to get a more detailed of view of what is happening (or not happening) if needed.

**Comment by mangui** [comment]
strange. could you share debug/debug2 logs ,

**Comment by MixMasterMitch** [comment]
I am new to flash development. How do I view the debug/debug 2 logs?

I did discover that every time it fails, the last chunk is loaded early on:
<img width="1680" alt="failedload" src="https://cloud.githubusercontent.com/assets/120892/10650575/0f60934e-77ff-11e5-93eb-8dd11b3a13aa.png">

Here is a load that works properly for reference:
<img width="1680" alt="correctload" src="https://cloud.githubusercontent.com/assets/120892/10650596/25b8780a-77ff-11e5-89a7-0712ba1adedc.png">

**Comment by mangui** [comment]
HLSSettings.logDebug=true
HLSSettings.logDebug2=true

**Comment by mangui** [comment]
after rethinking about it, i don't see how the recent code changes could affect your video not auto-playing at startup ?
unless you are calling `hls.stream.play()` before the manifest and first quality level has been retrieved - parsed ?
in that case the following commit https://github.com/mangui/flashls/commit/fe1c1ec93170e94b3f1cf39158647fd3a6308691 might break this, as it is expecting playlist duration to be available
I will add some robustness here, so that `seek()` will not fail if called while startup quality level is not retrieved yet.

**Comment by MixMasterMitch** [comment]
In regards to logging: What is your recommended approach for viewing the flash trace? The tools I see online are very outdated.

In regards to calling `hls.stream.play()`: The network logs in the picture above are both taken before I even hit play (and autoplay is disabled). In other words, something went wrong before I even started playback.

**Comment by mangui** [comment]
just turn 
HLSSettings.logDebug=true
HLSSettings.logDebug2=true

then you should see logs in your browser console

**Comment by MixMasterMitch** [comment]
Your latest change seems to have fixed the issue. Thanks!

We have player configuration around enabling the flashls debug logs, but I found that it was not properly setting to true. I fixed it and I can see the logs now, but I will not upload them unless you still want them.
