### ISSUE TITLE
V4.3.4 - Playback suddenly stops at mid stream

### ISSUE THREAD

**Issue by shaharmor** [mangui/flashls#415]
Hi,

We're having new issues with flashls V4.3.4 with streams that used to work flawlessly.

What we're experiencing is that sometimes (Not always), the stream simply stops in the middle of the playback.
The player starts making many requests to the playlist even though that every few requests it makes the playlist updates.

If we pause and play again the stream continues.

Debug log:
https://gist.githubusercontent.com/shaharmor/b1bca5536a77f4913f16/raw/dba7c437fc637155628688e14d7cbfead2a69a0c/flashls-debug.log

**Comment by shaharmor** [comment]
Also, sometimes it does make requests to new segments but does not continue playback.

**Comment by mangui** [comment]
what was the previous release you were using ?

**Comment by mangui** [comment]
plz recheck with latest flashls/dev and repost debug/debug2 logs, that should help understanding what is going on.
most probably there is something wrong in the sliding computation, as I can see some negative buffer length in your logs

**Comment by mangui** [comment]
closing as issue should be fixed
