### ISSUE TITLE
Live: initial number of segments needed for continuos playback

### ISSUE THREAD

**Issue by NicolasSiver** [mangui/flashls#420]
@mangui What do you think about setting like `initialManifestSize`? For example, playback will start only if level manifest is bigger or equal to specified amount of segments (default value could be 2 or 3)?

When live stream starts it always starts from small single segment for bootstrapping 

I think, it will be even healthier for segment fetching logic.

**Comment by mangui** [comment]
you need to replace this line
https://github.com/mangui/flashls/blob/dev/src/org/mangui/hls/loader/LevelLoader.as#L235
`_canStart = (_levels[level].fragments.length > 0);`
by
`_canStart = (_levels[level].fragments.length >= HLSSettings.liveManifestMinNbFragments);`

PR welcome
