### ISSUE TITLE
Playback not working in latest dev version

### ISSUE THREAD

**Issue by shaharmor** [mangui/flashls#422]
Hi,

After commit https://github.com/mangui/flashls/commit/4147ac4b5a3c0036b557ba4fd3675a44c01bf2fe all playback stopped working.

Streams are being downloaded but not played.

**Comment by mangui** [comment]
should be fixed by https://github.com/mangui/flashls/commit/51c44b70795f9367b2d29e6391a8d9302ac67ba6
