### ISSUE TITLE
loading icon in flowplayer does not dissapear after pause

### ISSUE THREAD

**Issue by joseluismg** [mangui/flashls#423]
Dear all,

any of you have experience this issue: It seems that when I play a  live HLS stream (we are using wowza  as the video server) everything works nice, but If I pause the video then it plays again but the loading icon (the rotating icon) does not dissapear. 
This only happens if I pause during some time, some seconds (or even minutes), not if I play it again quickly.

I tried the hls_lowbufferlength settings but it does not seem to have any effect in this issue.
Obviously I can disable the whole icon if I use the buffering:false property of the flowplayer, but it would be nice to have loading icon working.

thanks in advance!

**Comment by phloxic** [comment]
Try to limit `hls_maxbufferlength` instead like in our example: http://flash.flowplayer.org/plugins/streaming/flashls.html#live-stream-example - play around with a few values.

**Comment by joseluismg** [comment]
I used hls_maxbufferlength:15 and that made the trick!
thanks!
