### ISSUE TITLE
Stream stitching algorithm questoin

### ISSUE THREAD

**Issue by JayVeeHLS** [mangui/flashls#440]
One of the big streaming performance considerations is to show the right resolution of video for screen size.

This is critical for stable streaming performance when users are not watching in full screen. Some adaptive streaming players switch the stream to lower resolution or set a cap on resolution to not exceed client screen size.

Especially for interactive video streaming applications, most users are expected to only stream in a smaller default window while VPAID ads or other content on the page is shown related to video.

Does flashls control stream stitching based on client screen size? If not, can that be implemented?

JW Player already has this feature and other players are expected to do this as well.

**Comment by mangui** [comment]
RTFM

**Comment by JayVeeHLS** [comment]
I had read the manual. It was not obvious at first that I have to enable hls_capleveltostage to true to use this feature.

The link for documentation: http://www.cs.tut.fi/~moncef/publications/rate-adaptation-IC-2011.pdf
does not work. Can you please replace with a working link?

hls_capleveltostage (default false) : limit levels usable in auto-quality by the stage dimensions (width and height)
true : level width and height (defined in m3u8 playlist) will be compared with the player width and height (stage.stageWidth and stage.stageHeight). Max level will be set depending on the hls_maxlevelcappingmode option. Note: this setting is ignored in manual mode so all the levels could be selected manually.
false : levels will not be limited. All available levels could be used in auto-quality mode taking only bandwidth into consideration.
hls_maxlevelcappingmode (default downscale) : defines the max level capping mode to the one available in HLSMaxLevelCappingMode:
"downscale" - max capped level should be the one with the dimensions equal or greater than the stage dimensions (so the video will be downscaled)
"upscale" - max capped level should be the one with the dimensions equal or lower than the stage dimensions (so the video will be upscaled)
