### ISSUE TITLE
Can you fix documentation link from the main page of flashls?

### ISSUE THREAD

**Issue by JayVeeHLS** [mangui/flashls#441]
The link for documentation: http://www.cs.tut.fi/~moncef/publications/rate-adaptation-IC-2011.pdf
does not work. Can you please replace with a working link?

**Comment by mangui** [comment]
mmm, indeed ...
it should be this one
http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.300.5957&rep=rep1&type=pdf
