### ISSUE TITLE
capLevelToStage on retina displays

### ISSUE THREAD

**Issue by MixMasterMitch** [mangui/flashls#443]
When I set capLevelToStage to true, the capping is based on the reported size of the window, but not the actual resolution of the window. In particular, if I have a 480p video window on a non-retina display it will be properly capped at level 4, but then if I move the window to a retina display, the window will still report as being 480p and stay at level 4, but in reality the window will be 960 pixels tall (480x2) and should be at level 8. In other words, flashls appears to be capping using the Device Independent Pixel Size (dips), not the actual pixel size.

Would it be possible to have the capping logic use the actual pixel size instead of the dips?

More info: 
https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio
http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/display/Stage.html#contentsScaleFactor

**Comment by mangui** [comment]
that would make sense indeed, i will look into it.

**Comment by mangui** [comment]
merged, thanks for the PR
