### ISSUE TITLE
GL ERROR :GL_INVALID_ENUM with wmode='direct'

### ISSUE THREAD

**Issue by MixMasterMitch** [mangui/flashls#451]
When I set `wmode=direct` in the flash params, I consistently get the following error:

```
[.PPAPIContext]GL ERROR :GL_INVALID_ENUM : glTexImage2D: target was GL_TEXTURE_RECTANGLE_ARB
```

Specifically, it appears that every time I change levels, 5 of these errors occur and occasionally, the video flickers red or green.

A video demonstrating the errors and an example of the video color flicker can be viewed here: https://www.dropbox.com/s/tv2ynw4px4t2mdk/GL_ERROR.mov?dl=0

Any ideas on how to fix this or what could be the root cause?

**Comment by MixMasterMitch** [comment]
I realized that I get these errors even with `wmode=opaque` but then I don't get the color flicker. Although it would be nice not to have the console errors, the color flicker is what ultimately affects video playback.

**Comment by me-vlad** [comment]
Hello,
I see periodical GL ERROR messages in Chrome 47.0.2526.73 (64-bit) 
[.PPAPIContext]GL ERROR :GL_INVALID_VALUE : glTexSubImage2D: bad dimensions.

hls_usehardwarevideodecoder parameter is set to false

**Comment by mangui** [comment]
well, this issue seems to be recurrent with Chrome ... and not flashls specific.
we can't do anything from flashls perspective I am afraid

**Comment by MixMasterMitch** [comment]
Ok. That's a bummer.
