### ISSUE TITLE
Repeated fragment playback after seek to the live position with OSMF player

### ISSUE THREAD

**Issue by rwlodkowski** [mangui/flashls#453]
Hey @mangui,

there is an issue with live DVR streams playing with OSMF players. It's mostly visible and reproducible with GrindPlayer but it occurs with SMP also. After you seek with the seekbar to the end of the timeline to get the live position, the player starts to stutter with the last loaded fragment, playing it back most of times just a 2-4 times in a row, but there are cases when it's happen in the infinite loop.

Here's the test case:
http://flashls.wlodkowski.net/osmf/GrindPlayer_dvrtest1.html

If you can't load stream because of the geo-blocking just use some proxy. If it's impossible then I'll send you debug logs and video capture to present you what's going on.

**Comment by mangui** [comment]
plz recheck with latest flashls/dev, issue should be fixed

**Comment by rwlodkowski** [comment]
Ok. Everything fine with v0.4.4.16. Closing.
