### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by zuzzurro** [mangui/flashls#465]
Hi
I am seeing a memory leak that (by bisecting it) seem to be caused by the 95d4473372e1976a6c3151069629bbc4e02be2e7 commit (this is just a recompilation so it may be one of the commits between this update of swf/swc and the previous).
I'm not fluent in actionscript at all sorry I can't do more than bisecting and reporting :-(

**Comment by mangui** [comment]
ok so basically according to your analysis, you observe memleak with https://github.com/mangui/flashls/releases/tag/v0.4.4.11 but not with https://github.com/mangui/flashls/releases/tag/v0.4.4.10 right ?

diff here:
https://github.com/mangui/flashls/compare/v0.4.4.10...v0.4.4.11

**Comment by zuzzurro** [comment]
As the previous update happened with the commit of v.0.4.4.9, yes, I would say so.
I used grindplayer and its statistics window to determine that in the "good" state, by playing the first few minutes of the vide and watching the first GC cycles, the memory would stay at around 110MB max. In the "bad" state it would start at 110 but quickly go to 150 and more, with each GC cycle failing to bring the memory down to where it started. It seems actually quite easy to spot.

**Comment by mangui** [comment]
@zuzzurro found why
backbuffer was not clipped properly ...
should be fixed now, on flashls/dev

**Comment by zuzzurro** [comment]
Yeah, it seems to have fixed it. Now memory stays between 107 and 129 MB (checked for about 7 GC cycles). Thanks a lot. I really love git bisect, it's a really powerful tool, especially when you couple it with the experience of the code owner, of course :-)

**Comment by mangui** [comment]
great ! closing
