### ISSUE TITLE
2 HTTP requests to get flashlsOSMF.swf

### ISSUE THREAD

**Issue by arnaudleyder** [mangui/flashls#479]
I am using an OSMF based player with your amazing plugin. What I am seeing in Chrome 47 with Flash 20 (or in Firefox for that matter) is that 2 HTTP requests are made to get the same flashlsOSMF.swf (using OSMF plugin) component. 
This can be reproduced on http://www.flashls.org/latest/examples/osmf/GrindPlayer.html or http://www.flashls.org/latest/examples/osmf/StrobeMediaPlayback.html. Just open your browser console and see it in the network tab when page loads. 
To the best of my knowledge this seems to happen with debug and release versions of the flashls plugin. 
Is there any reason for these 2 identical HTTP requests to get the swf plugin? Is it something that can be configured so that only one HTTP request is made?

Thanks
Arnaud

**Comment by mangui** [comment]
Hi @arnaudleyder indeed I can repro with both Chrome an FF.
I am not really clear about the handling of the dynamic loading of OSMF Plugin.
whether it is handled by the player itself, or by OSMF ?
how many init logs do you see ?
https://github.com/mangui/flashls/blob/dev/src/org/mangui/osmf/plugins/HLSPlugin.as#L35

**Comment by rwlodkowski** [comment]
@mangui as I know it happens for every single dynamic plugin, so it's OSMF/SMP issue not flashls issue.

**Comment by arnaudleyder** [comment]
ok thanks for your anwsers. I will have a look at the OSMF/player code plugin loader. If it is not related to the flashls plugin this can be closed. If I find something I will post here.
