### ISSUE TITLE
m3u8 link not play when use video.js

### ISSUE THREAD

**Issue by caomulaodao** [mangui/flashls#481]
https://ydisks.duapp.com/m3u8/url/?path=2416218904/dianying/%E4%BB%8E%E5%A4%A9%E5%84%BF%E9%99%8D.mp4.m3u8

show FLASH: srcnotfound

**Comment by mangui** [comment]
Hi @caomulaodao 
which release are you using ?
could you also enable debug logs and share them ?

**Comment by caomulaodao** [comment]
sorry， @mangui  
i found this is caused by what reason  of Server Policy。
but，i found a lot  report of  “FLASH: srcnotfound”  when i use various kinds m3u8 address from 
third party。
 so ，i hope will have a more friendly report。
thanks。

**Comment by ghost** [comment]
Videojs works only on firefox safari and microsoft edge, also onmobile browsers but not on google chrome. Say that not playable sorces are find , belive this problem with cors in chrome. Have anyone this probs with cors on localhost and on sever. I Use xamp on localhost and ubuntu apache on server.

**Comment by caomulaodao** [comment]
@PuN1SheR47 
add  crossdomain.xml in web root
content is:
`<?xml version="1.0" encoding="UTF-8"?>
<cross-domain-policy>
    <allow-access-from domain="*"/>
</cross-domain-policy>`

**Comment by ghost** [comment]
@caomulaodao 
thanks for response but it doesn't work. any idea? i dont know i try almost everything i miss some little thing and its freaking me out

**Comment by me-vlad** [comment]
@PuN1SheR47 please provide a link to test page with your player setup
