### ISSUE TITLE
Can't play VODs from twitch? (Grind Player)

### ISSUE THREAD

**Issue by Kasher** [mangui/flashls#494]
Hi,

I'm trying to play a video from twitch (VOD, not live), but I keep getting an error (Stream not found).
The stream I try to play is
http://usher.twitch.tv/vod/47458673?nauth=%7B%22user_id%22%3Anull%2C%22vod_id%22%3A47458673%2C%22expires%22%3A1456222623%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22privileged%22%3Afalse%7D&player=twitchweb&nauthsig=8aa70f0668771a4e1c7e531e438bd8ab94384798&allow_source=true&allow_spectre=true

I use the latest version of Grind player.
I'll add that live streams in twitch and VODs from other sites work well for me, the only error is when I try to play a recorded video from twitch.
Another addition - my crossdomain.xml is valid, and it allows my domain to access the m3u8 file.

One last thing - I can play this stream using VLC, so I guess it should be playable and probably I'm doing something wrong.

I'll appreciate any help, as I've tried to load this video for a few hours now, with no luck.

Thanks!
Roee.

**Comment by mangui** [comment]
working with chromeless player with Charles Proxy spoofing crossdomain.xml
my bet is that your URI does not pass this test ...
https://github.com/mangui/flashls/blob/dev/src/org/mangui/osmf/plugins/loader/HLSLoaderBase.as#L46

**Comment by Kasher** [comment]
Wow. What a strange test.
If I get this right, that means that if the link doesn't contain the string "m3u", it won't be played.

Thank you very much. Is there a quick solution that you can think of for this issue?

Thanks again!! :+1:

**Comment by mangui** [comment]
Removing the test :-)

**Comment by mangui** [comment]
In fact it is part of HLS spec. Either m3u/m3u8 extension or correct content type. The issue is that Flash has restrictions that prevents content type to be read...

**Comment by Kasher** [comment]
I see. Thank you so much! You've helped me a lot :+1: :+1: :+1:
