### ISSUE TITLE
I cant see the video 

### ISSUE THREAD

**Issue by aliaburas80** [mangui/flashls#498]
HI, 
I start test your chromeless player HLS plugin but I cant see the video on stage.
Can you please check the attached file.
Thanks 
[http://competition.mbc.net/ali/HLSPlayer.rar](url)

**Comment by aliaburas80** [comment]
http://competition.mbc.net/ali/HLSPlayer.rar

**Comment by mangui** [comment]
I can debug a stream but not a player integration sorry
