### ISSUE TITLE
AES-128 key rotation support?

### ISSUE THREAD

**Issue by arnaudleyder** [mangui/flashls#500]
Quick question. 
I can see from [here](https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/StreamingMediaGuide/UsingHTTPLiveStreaming/UsingHTTPLiveStreaming.html#//apple_ref/doc/uid/TP40008332-CH102-SW15) that HLS content protection is available in 3 modes. I am interested in mode 3:

> The third mode instructs the segmenter to generate a new random key file every n media segments, save it in a specified location, and reference it in the index file. This mode is referred to as key rotation. Each group of n files is encrypted using a different key.

Does Flash HLS support decrypting this mode as well?
Thanks

**Comment by mangui** [comment]
yes, you can use multiple keys per playlists, as long as the keys URL are referenced in the playlist

**Comment by arnaudleyder** [comment]
ok thanks for the prompt answer.
