### ISSUE TITLE
Live hls stream can not play

### ISSUE THREAD

**Issue by blitheinsz** [mangui/flashls#508]
url:   http://113.106.87.5:5080/live/XBWX71mY.m3u8
this.url can not play,can you help me? thanks

![z0uxtipambzulp p hw 5r](https://cloud.githubusercontent.com/assets/13517048/14338302/8d7b1910-fca8-11e5-90ce-53fbc115829f.png)

**Comment by mangui** [comment]
your playlist seems down ?
for such kind of issues, plz share debug/debug2 logs

**Comment by blitheinsz** [comment]
thanks!
I find the problem,my ts Is not very standard. so can not play.
