### ISSUE TITLE
Video.js and MediaElement.js quality select

### ISSUE THREAD

**Issue by ntadej** [mangui/flashls#51]
There is a documentation missing if quality selection is available on video.js and/or mediaelement.js. If it is, how can it be done?

**Comment by steverandy** [comment]
@mangui is there a method exposed to videojs to get levels?

**Comment by mangui** [comment]
https://github.com/mangui/video-js-swf exposes quality level to JS, plz check this PR for details: https://github.com/mangui/video-js-swf/pull/3/
