### ISSUE TITLE
If buffer < 0.1 HLSNetstream not paused if in PLAYING_BUFFERING

### ISSUE THREAD

**Issue by shanekerr** [mangui/flashls#511]
In _checkBuffer on the HLSNetStream the stream is only paused in the event of an empty buffer if the playback state is PLAYING, however in previous buffer checks we will switch to a state of PLAYING_BUFFERING if buffer < _bufferThresholdController.lowBufferLength. 

When we have a low bandwidth situation we can find that the netstream is not paused, and so the stream will playback minute bits of buffer as they come in.  This can be seen in the chromeless example player by throttling your connection to a very slow speed.

**Comment by mangui** [comment]
Hi @shanekerr  if you can have any fix, a PR would be welcomed

**Comment by shanekerr** [comment]
Hi @mangui, I have added a PR of the fix I am using as requested.

**Comment by jlacivita** [comment]
FYI, I ran into this, too. It's only comes up with bad network conditions or inconsistent live variants (one variant is behind another, so "now" isn't available causing starvation)

I did a local fix that was just a one liner, and seemed to fix it, but wasn't sure it was the right solution.
