### ISSUE TITLE
hls.stream.time don't work?

### ISSUE THREAD

**Issue by gor60** [mangui/flashls#515]
When playing http://hls1.addictradio.net/addictalternative_aac_hls/playlist.m3u8
 values hls.stream.time, hls.watched changed to 9 seconds and all! 
hls.position varies from 10 to 19 and also all! What to do? 
( Thank you! )

**Comment by gor60** [comment]
hls.stream.time, hls.watched not work properly if  id3_tags != null, otherwise everything works fine

**Comment by gor60** [comment]
hls.stream.time, hls.watched not work properly if id3_tags != null, otherwise everything works fine

**Comment by mangui** [comment]
looks like there is no ID3 PRIV tag with any timestamp in your stream ?
such tag is mandatory if you use AAC ES
https://github.com/mangui/flashls/blob/3988b57ecdda98b2c57f0ab8d79931eafb3da6b2/src/org/mangui/hls/demux/ID3.as#L86-L103

**Comment by gor60** [comment]
Hello, Mangui. Thank you for your desire to help.
![1_aac](https://cloud.githubusercontent.com/assets/18560614/15220674/fb62009a-1870-11e6-9b36-223800c385a2.jpg)
![2_mp3](https://cloud.githubusercontent.com/assets/18560614/15220679/004a4608-1871-11e6-9a6b-f99b526a99ea.jpg)
![3_aac](https://cloud.githubusercontent.com/assets/18560614/15220681/03fa70b6-1871-11e6-9121-a3fff9f5206d.jpg)

The situation is similar for Mp3 stream, for example, http://hls1.addictradio.net/addictstar_hls/playlist.m3u8
It screens both streams (in the hex-editor). What's wrong with them?
hls.watched works correctly in the third stream (http://stream.scahw.com.au/live/4gld.stream/playlist.m3u8, third photo from top)

**Comment by mangui** [comment]
I checked http://hls1.addictradio.net/addictstar_hls/playlist.m3u8 and indeed there are ID3 timestamps, but they look wrong.

below is the timestamp extracted from consecutive fragments.
as you can see the delta is either 0 or less than 200ms

2016-05-12 17:56:35.810  VM693:1 DEBUG:ID3 timestamp found:30884814
2016-05-12 17:56:35.828  VM706:1 DEBUG:ID3 timestamp found:30884814
2016-05-12 17:56:35.951  VM761:1 DEBUG:ID3 timestamp found:30884925
2016-05-12 17:56:36.012  VM793:1 DEBUG:ID3 timestamp found:30885036
2016-05-12 17:56:46.248 VM1026:1 DEBUG:ID3 timestamp found:30885147
2016-05-12 17:56:53.033 VM1152:1 DEBUG:ID3 timestamp found:30885257
2016-05-12 17:56:53.728 VM1189:1 DEBUG:ID3 timestamp found:30885368
2016-05-12 17:57:01.848 VM1339:1 DEBUG:ID3 timestamp found:30885479
2016-05-12 17:57:12.351 VM1534:1 DEBUG:ID3 timestamp found:30885590

there should be 10000 ms between timestamp (as your frag are 10s long)

it is the case with http://stream.scahw.com.au/live/4gld.stream/playlist.m3u8
which plays fine and in which you can seek accurately
VM7535:1 DEBUG:ID3 timestamp found:38195393
VM7701:1 DEBUG:ID3 timestamp found:38205285

38205285-38195393=9892

**Comment by gor60** [comment]
I realized, this is a feature stream
Thank you
