### ISSUE TITLE
DEBUG:TS: unknown PID

### ISSUE THREAD

**Issue by blitheinsz** [mangui/flashls#518]
my url:  http://115.231.182.113:5080/hls/timeshift/y3q7b7vf_1461154473000_1461154528000.m3u8

on a mobile phone can play;
safari  can play;

but, i use flashls plugin on the desktop ,can not play.

DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4352
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4352
DEBUG:TS: unknown PID:4352
DEBUG:TS: unknown PID:4352
DEBUG:TS: unknown PID:4352
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4352
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4352
DEBUG:TS: unknown PID:4352
DEBUG:TS: unknown PID:4352
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4352
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4352
DEBUG:TS: unknown PID:4352
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4352
DEBUG:TS: unknown PID:4352
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4352
DEBUG:TS: unknown PID:4352
DEBUG:TS: unknown PID:256
WARN:TS: reparsing PMT, unknown PID found
WARN:TS: lost sync between offsets:1028/1204
DEBUG:TS: lost sync dump:5c9c41fa1bc9036bfd77409e15d065ea2e5c7739d6c8d50a2f78ce5372fc4114688d175bf047e7694b33c0e483a9b8253cbaa557c263706ba0670e39b734565331810aa5a442fd08af624f07a94b0de925db140b0f0a42aab5d52a4e5b1110ab937d5b7a106a12cd94747444d1d66d1297ea03d881a360eec5536270a6fe77cfaacf340f71cc1fb265377bb26eb0549eacae2d187310111916266357eb774e3dacd16da2eb1db1e3e6a1742100e41810
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4352
DEBUG:TS: unknown PID:4352
DEBUG:TS: unknown PID:4352
DEBUG:TS: unknown PID:4352
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4352
DEBUG:TS: unknown PID:4352
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4352
DEBUG:TS: unknown PID:4352
DEBUG:TS: unknown PID:4352
DEBUG:TS: unknown PID:4352
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4352
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4352
DEBUG:TS: unknown PID:4352
DEBUG:TS: unknown PID:4352
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4352
DEBUG:TS: unknown PID:4352
DEBUG:TS: unknown PID:4352
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4352
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4352
DEBUG:TS: unknown PID:4352
DEBUG:TS: unknown PID:4352
DEBUG:TS: unknown PID:256
WARN:TS: reparsing PMT, unknown PID found
WARN:TS: lost sync between offsets:7660/7836
DEBUG:TS: lost sync dump:87bcb0253b32265063ebd27811c486bdf4d6dd18c548b08067361e5d57f96c7753332c1859811d32a422db396ebf7bdef9b27876b6a7bdce0ed82ad8f8f29244c7e487b0eff9155ab06ef6f618b0c081f1e545408c2bf1fae2db664198981cd0425f907ca6dade63316901b671db7c8608f064de1c500672ce8e3d6c54b80b7a976f34100eb79aefe83ff277f31377a92a3e37cba5f497ca485116b975cb75571ab0f3e95ebc0aded2c3aefad2d86830
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:TS: unknown PID:4113
DEBUG:position/duration/buffer/backBuffer/audio/video/NetStream bufferLength/audioExpected/videoExpected:0.00/30.53/0.00/0.00/0.00/0.00/0.00/false/false

**Comment by blitheinsz** [comment]
i find osmf can play

**Comment by mangui** [comment]
this URL is empty
