### ISSUE TITLE
For https request

### ISSUE THREAD

**Issue by christinaxu** [mangui/flashls#532]
I have encrypted the .ts  with AES-128. To secure the key file, I set the URI in the .m3u8 with a https request, for example," #EXT-X-KEY:METHOD=AES-128,URI="https://www.test.dev/api/downFile.action". The player cannot play now. Does it not support the https request? How to solve it?

**Comment by nhjm449** [comment]
Make sure that https://www.test.dev/crossdomain.xml exists and contains the appropriate XML. (crossdomain.xml lets Flash know that it's allowed to access content from that particular hostname.)

Also check the Network tab in your browser's Dev Tools to verify that the player is able to retrieve downFile.action.

**Comment by mangui** [comment]
Hi @christinaxu anything pending on this ticket ?
as stated by @nhjm449 it looks like a crossdomain setup issue

**Comment by Boxie5** [comment]
@nhjm449 is right. I've just met this issue too,  and I make it by setting crossdomain.xml with secure="false" to enable swf requesting https content from a http environment.

I think this ticket can be closed.
