### ISSUE TITLE
flash hls over https

### ISSUE THREAD

**Issue by ale-grosselle** [mangui/flashls#536]
Hi @mangui,
I am using your great library into a https page:
[Example](https://thron-player-andreabisellothron.c9users.io/poci/flash-hls/examples/chromeless/?src=https%3A%2F%2Fthronqa-view.thron.com%2Fapi%2Fxpublisher%2Fresources%2Fweebopublisher%2FgetContentDescriptor.m3u8%3FclientId%3Dthronqa%26contentId%3Defaab1e4-a10e-4ba1-b271-4aaace27714c%26channelType%3DSTREAMHTTPIOS%26v%3D6)

All work fine but single ts request are requested using http protocol and this cause some warning:

![image](https://cloud.githubusercontent.com/assets/6173088/16338082/90673f82-3a1a-11e6-8a29-b2b18df5f27c.png)

Many thanks, 
Alessandro

**Comment by mangui** [comment]
Hi @ale-grosselle this warning is thrown by the web browser ... basically the swf is served using HTTPS whereas the stream is served using HTTP.

best is to remain consistent.

**Comment by ale-grosselle** [comment]
Hi @mangui, You're right!
I assumed that the protocol followed the descriptor stream... I'm sorry if I made you waste time :(.
