### ISSUE TITLE
Flashls + HLSJS + Secure AES Encrypt Key ( HLS Crypt )

### ISSUE THREAD

**Issue by N0WayH0me** [mangui/flashls#543]
Hi.

I use your plugin and it's working fine on computer.
Thanks for your works.

But i want to update my code and want to use HLSJS + HLS Crypt

https://blacktrash-org.prossl.de/fpssl/hls-crypt.php

HLS crypt use Flowplayer 6 and Flowplayer function change .

i wonder if it's possible to have your works working with FP 6 + HLSJS + HLS Crypt

thanks

**Comment by phloxic** [comment]
The demo does use hlsjs and an integrated version of flashls with Flowplayer. As described and referenced on the demo page.

**Comment by N0WayH0me** [comment]
Ohh !!

I made several test with hls-crypt and failed to use it with my stream for Flash hls browser  .. but success with flashls.org script ..

i will try again and perhaps ask your help so to understand where i failed .

Does the method to segment mp4 file in TS could affect it ?

I use ffmepg on ubuntu.

Thanks for your quick answer

**Comment by phloxic** [comment]
The demos allows you to simulate the situation where neither hlsjs nor generic hls playback is supported: Check https://blacktrash-org.prossl.de/fpssl/hls-crypt.php?hlsjs=false in any desktop browser except Mac Safari.

Segmenting could affect it. Best try your stream un-encrypted first to exclude a glitch in encryption or your key protection mechanism.

**Comment by N0WayH0me** [comment]
Hi .

I send you ( email ) the 2 page.

One use FlasHLS.org code and works on FF / IE 11 / Chrome
One use blacktrash hls-crypt code , works on FF / Chrome but fail on IE 11

error flash: Video file not found

I try several edit but cannot found why.

Thanks for your help

**Comment by phloxic** [comment]
As per your email the unencrypted stream works with Flash HLS, so you have a problem with your stream encryption - or the exact setup of it.
Let's keep this in email, until we are certain that there is actually a bug.
