### ISSUE TITLE
HLS stream plays in chromeless but not in OSMF-based players or videojs

### ISSUE THREAD

**Issue by radiantmediaplayer** [mangui/flashls#553]
The HLS URL to test is:
`https://v39-a.sdn.szn.cz/v_39/vmd_ko_58010d820332e60a8b91ba5f/1476465952?fl=mdk,2192dc05|hls,3,0,https,VOD,0`

This HLS URL works in: 
http://www.flashls.org/latest/examples/chromeless
But it fails to play on: 
http://www.flashls.org/latest/examples/osmf/GrindPlayer.html
http://www.flashls.org/latest/examples/osmf/StrobeMediaPlayback.html
http://www.flashls.org/videojs/flash_demo.html

Each time when it fails it spits a "stream not found" (OSMF) or "src not found" (videojs) error. I am guessing maybe it has something to do with how the manifest is presented to the Flash plugin as it uses
query strings to obtain the m3u8 playlist.

Any hints as to what could be the underlying issue?
Thanks

**Comment by mangui** [comment]
this line
https://github.com/mangui/flashls/blob/dev/src/org/mangui/osmf/plugins/loader/HLSLoaderBase.as#L46

**Comment by radiantmediaplayer** [comment]
Yes but the HLS feed has a Content-Type: application/vnd.apple.mpegurl response header which should be catched by https://github.com/mangui/flashls/blob/dev/src/org/mangui/osmf/plugins/loader/HLSLoaderBase.as#L50?

**Comment by mangui** [comment]
yes but content-type (and any HTTP headers) can only be read by Adobe Air, not by Flash Player, because of obscure security restrictions.

**Comment by radiantmediaplayer** [comment]
This URL https://v39-a.sdn.szn.cz/v_39/vmd_ko_58010d820332e60a8b91ba5f/1476465952?fl=mdk,2192dc05|hls,3,0,https,VOD,0&type=m3u8 actually works in our player. 

Would it be bad to remove this check (as in unwanted side effects) and just return true each time (we do not do AIR)?

```
if (urlResource.url.search(/(https?|file)\:\/\/.*?\m3u(\?.*)?/i) !== -1) {
  return true;
}
```

**Comment by mangui** [comment]
if you are dealing with an OSMF based player with multiple source providers (HLS and DASH for example), it might be problematic, as OSMF won't be able  to know which provider to use before fetching the manifest.

**Comment by radiantmediaplayer** [comment]
ok thanks for the detailed info. I will review what is the best course of actions for our player.
