### ISSUE TITLE
Switching level before end can prevent finishing VOD

### ISSUE THREAD

**Issue by phloxic** [mangui/flashls#563]
http://www.flashls.org/latest/examples/chromeless/?src=http%3A%2F%2Fedge.flowplayer.org%2Fnight1.m3u8

- When on high level try switching to low level towards end during playback
- page can be reloaded, so it starts with a higher level immediately, to ease replication

-> playback stops before end
- probably before last very short segment

**Comment by phloxic** [comment]
This is where it stops:
<img width="816" alt="screen shot 2016-12-12 at 3 06 17 pm" src="https://cloud.githubusercontent.com/assets/168338/21104049/f56111d6-c07c-11e6-9893-22330ae7fce3.png">

**Comment by phloxic** [comment]
The underlying problem is:
1. level 0 and 1 are avc baseline w/o b-frames, all other levels feature a profile with b-frames
2. last segment contains either 2 frames (baseline) or 1 frame: 0.04 secs difference in duration at "segment border" (25 fps)

Baseline streams are almost always slightly longer than others - other "random" example: http://www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8 (but 2. does not apply, haven't double checked though) - where the difference in duration is even higher:
- http://www.streambox.fr/playlists/x36xhzz/url_2/193039199_mp4_h264_aac_ld_7.m3u8 - 634.634000 - baseline
- http://www.streambox.fr/playlists/x36xhzz/url_1/193039199_mp4_h264_aac_hd_7.m3u8 - 634.584000 - high

**Comment by phloxic** [comment]
@mangui - fyi, this is not of high priority for us. Can be solved in a pragmatic fashion.

**Comment by mangui** [comment]
good, i was not looking into it :)

**Comment by phloxic** [comment]
so don't start  ;-)
