### ISSUE TITLE
VOD playback issue after seeking

### ISSUE THREAD

**Issue by indiestream** [mangui/flashls#568]
I'm having an issue with playback after seeking. When a user seeks I pause playback upon mouse down then seek upon mouse up. The screen updates after seeking but when I call resume after buffering is complete, sometimes the PLAYING playback state event is thrown but playback is frozen. The bug doesn't always occur. Sometimes seeking and playing again works fine. Hitting pause/play during playback works perfectly but if it's frozen after seeking it's broken. Sometimes re-seeking to a different spot fixes the bug.

Here's a copy of the console log and description of flow.

VideoPlayer::hlsPlaybackState::PAUSED_BUFFERING <-- Initial Manifest Loading
VideoPlayer::hlsPlaybackState::PLAYING_BUFFERING
VideoPlayer::hlsPlaybackState::PLAYING
VideoPlayer::controlPlayer:control_pause <-- User clicks down on the scrub bar
VideoPlayer::hlsPlaybackState::PAUSED
VideoPlayer::controlPlayer:control_seek <-- User releases the mouse on the scrub bar
VideoPlayer::controlPlayer::seek::5086.848000000061 0.41 <-- NetStream is told to seek to position.
VideoPlayer::hlsPlaybackState::PAUSED_BUFFERING
VideoPlayer::hlsPlaybackState::PAUSED <-- Stream has finished seeking
ControlBar:_onMousePlayPause::PAUSED <-- Telling the stream to resume playback.
VideoPlayer::controlPlayer:control_play
VideoPlayer::hlsPlaybackState::PLAYING <-- Playing event is thrown but playback doesn't actually resume.

**Comment by indiestream** [comment]
Just to update. I've noticed this issue occur's on load as well. Sometimes the PLAYING event is thrown but the stream doesn't actually play.

**Comment by mangui** [comment]
that is weird, could you provide flashls debug logs ?

**Comment by indiestream** [comment]
I've tracked down the cause of why it was occasionally stalling but not the reason. In my code after I create an instance of HLS I set the bufferTime to 5 seconds. When I comment that out everything seems to work normally. My purpose here is set the load buffer to 5 seconds and after the playback has started I change it to 10 seconds. I've been doing that for years and this player is an older one I've modified to add HLS to it. After reviewing your source for your other players I realized that maybe the issue and commented it out. The player works for Live/VOD now.

Clip of the code
`	
	this._hls = new HLS();

	if(this.stage)
		this._hls.stage = this.stage;
			
	//this._hls.stream.bufferTime = Constants.BUFFER_TIME_LOAD; <-- Causes occasionally stalling
	this._hls.stream.inBufferSeek = true;
`



P.S. I'm not sure how to turn on verbose logging when using the source directly. I've changed the LOGGING compiler config to true and got this outputted in both instances where the stream starts fine and when it stalls after loading. 

`
	INFO:HLSNetStream:close  growhouse.tv
	INFO:HLSNetStream:play(-2)  growhouse.tv
	INFO:HLSNetStream:seek(-2)  growhouse.tv
	INFO:Setting audio track to 0  growhouse.tv
`

**Comment by mangui** [comment]
ok you should not use  `NetStream.bufferTime`, as the logic of handling minBuffer is handled completely by `HLSNetStream`.
if you want to hardcode min buffer length you need to use [`HLSSettings.minBufferLength`](https://github.com/mangui/flashls/blob/dev/src/org/mangui/hls/HLSSettings.as#L47-L59)
but you can also let flashls handle this min buffer value dynamically: the logic is handled here
https://github.com/mangui/flashls/blob/dev/src/org/mangui/hls/controller/BufferThresholdController.as
