### ISSUE TITLE
Some m3u8 streams have Error #2032

### ISSUE THREAD

**Issue by beautylix** [mangui/flashls#575]
Hello,

I downloaded codes from here, and used the example code of grindplayer, some works well, but some has Error #2032, for example, the radio stream url: `http://ngcdn001.cnr.cn/live/zgzs/index.m3u8`

I tested on your demo page, it did not work either, the url is : http://www.flashls.org/latest/examples/osmf/GrindPlayer.html?src=http%3A%2F%2Fngcdn001.cnr.cn%2Flive%2Fzgzs%2Findex.m3u8

However, I found a website using the same codes, but it works well, the website is` https://www.hlsplayer.net/`

I do not know how to fix, please help me out. thanks a lot

**Comment by mangui** [comment]
there is a crossdomain restriction, refer to http://www.adobe.com/devnet/adobe-media-server/articles/cross-domain-xml-for-streaming.html

it might work on HTML5 player but in that case you might have CORS restriction as well...
