### ISSUE TITLE
setting new AudioTrack

### ISSUE THREAD

**Issue by ghost** [mangui/flashls#593]
Hi ,
Is there any example that shows how an audioTrack can be set for flashhls  player via an external JS function?

I see setAudioTrack() can be exposed to the interface via ExternalInterface.addCallback(...). Is there any other way?

Thanks,
Hamid Porasl

**Comment by porasl** [comment]
I implemented my feature using ExternalInterface.addCallback(...). to expose setAudioTrack() to external JS. But I wonder if there is a better way to do that.

**Comment by ghost** [comment]
It was an old ticket
