### ISSUE TITLE
Audio Track switch in FlashHls

### ISSUE THREAD

**Issue by ghost** [mangui/flashls#594]
Hi 
I am using flashls-0.4.4.24, released May-2017
I added following method and exposed it to be invoked via JS:
1) in HLS.as
ExternalInterface.addCallback("setAudioTrack", setAudioTrack);

2. In Hls.as I added following method
public function setAudioTrack(locale : String) : void {
			var i:int=0;       
			for each (var altAudioTrack:AltAudioTrack in this.altAudioTracks){
				if((altAudioTrack.lang == locale) && (altAudioTrack.url != null)){
					_audioTrackController.audioTrack=i;
					var ev : HLSEvent = new HLSEvent(HLSEvent.AUDIO_TRACK_SWITCH);
					ev.audioTrack = i;
					dispatchEvent(ev);
				}
                          i++;
			}	
	    };
It seems triggering HLSEvent.AUDIO_TRACK_SWITCH event isn't needed since audioTrackController.audioTrack=i; will do the job, but I get audio track change faster in this way (Anyways it take about 8 to 15 seconds to change an Audio track).  I have several issues. 
1) When I select a new audio track then audio switches back and forward (it seems it uses data in its buffers) before it stabilizes on the selected track. 
2) When I select a new  audio track video freezes and stays so
3) When once audio has changed the track and it plays correctly I can change audio tracks successfully after that. Anyways the audio track change has an overhead (waiting time between 8 to 15 sec). Setting the default audio track in audioTrackContrller._audioTracksMerge() to '1' instead of '0' eliminates described issue in point (1) 

Please see the attached playlist. Do you see any issue there. Please let me know if what I am doing is correct or not. Do I have to take more steps if I want to make an audio track change in flashHls

Any direction here will be very helpful.
@mangui @jlacivita @kfeinUI @neilrackett

Thanks,
Hamid Porasl

[master.txt](https://github.com/mangui/flashls/files/1849089/master.txt)

**Comment by neilrackett** [comment]
We experienced alt audio switching issues when we were using Flashls some time ago, so you're welcome to take a look at [my fork](https://github.com/neilrackett/flashls/tree/prod) to see if there's anything in there that might be useful to you.

The solution I came up with causes the video to pause briefly when the audio track is switched; it's not ideal, but is close to 100% reliable and removes the ~10 second delay.

**Comment by ghost** [comment]
Thanks Neil,

I would be pleased if you comment on my way to invoke the Audio Track Switch :
1. In HLS.as I expose a method e.g. setAudioTrack()
ExternalInterface.addCallback("setAudioTrack", setAudioTrack);

2.in HLS.as
 I define a new method
     public function setAudioTrack(locale : String) : void {
 var i:int=0;
 for each (var altAudioTrack:AltAudioTrack in this.altAudioTracks){
 if((altAudioTrack.lang == locale) && (altAudioTrack.url != null)){
 _audioTrackController.audioTrack=i;
  }
 i++;
 }
 };

3. in my JS file I invoke
  player.setAudioTrack(locale);

Is that a correct way to invoke setAudioTrack in the player?

**Comment by ghost** [comment]
Hi Neil,
I am using your fork now and after invoking of  setAudioTrack(int) I get following message in the console:

"seek : need to load alt audio track" 
"Alt audio switch taking too long: 84.084 / 3134 ***"

it seems the HLSEvent.AUDIO_TRACK_SWITCH in the AudioTrackController.setAudioTrack () isn't fired. Do you have any client code that works with this forked version? I am trying to follow the way ChromelessPlayer is using the HLS api. It seems it should be a call to load() after setting the track and the seek()

Any direction here will be very helpful.
@mangui @jlacivita @kfeinUI @neilrackett

Thanks,
 Hamid Porasl

**Comment by neilrackett** [comment]
The changes I made were focused on integration with OSMF, which might explain why you're seeing a different outcome with ChomelessPlayer.

It's been a long time since I worked with Flashls, but I'll try to have a quick look through tomorrow to see if I'm able to offer up anything useful.

**Comment by ghost** [comment]
Hi Neil,

I fixed the issue. I had also to add startLoad() to my exposed method after seek(). It works fine. As you mentioned there is a minor stop/delay during audio track change and that shouldn't be big issue, since people aren't changing audio track often.  

Next I will integrate my Inband event support (ID3 tags) and also Subtitle from the older version of my FlashHls. I see you have already an implementation in place. 

Thanks,
Hamid Porasl

**Comment by ghost** [comment]
Hi Neil,
I am using your fork. Multi Audio works fine. But when I want to watch Bloomberg's LIVE which isn't Multi-Audio. Then player doesn't show anything. In Browser's console log I see:
Setting audio track to 0
VM128738:1 [object FragmentLoader] enough download bandwidth, adjust start level from 0 to 3
VM128739:1 [object FragmentLoader] _checkLoading : playlist not received for level:3

and Noting after that.
Any direction here will be very helpful.
 @neilrackett

**Comment by neilrackett** [comment]
Try setting `HLSSettings.altAudioSwitchMode` to `HLSAltAudioSwitchMode.LEGACY` to revert to original Flashls method of audio switching for that stream.

**Comment by ghost** [comment]
Hi Neil,
Where is HLSSettings.altAudioSwitchMode? can I set it from external JS file? How can I do this dynamically in my env I am using same flasHls code for VOD/Live/ multi Audio and ... 

And another question is about subtitle. I see in your fork you have implemented support for SubTitle. Does it work? In this case I can start to integrate it with the latest release.

Any direction here will be very helpful.
@neilrackett

Thanks,
Hamid

**Comment by ghost** [comment]
Hi Neil,
Could you please be more specific when you write:
"Try setting HLSSettings.altAudioSwitchMode to HLSAltAudioSwitchMode.LEGACY to revert to original Flashls method of audio switching for that stream."   Do you mean in StreamBuffer.as?  I am not setting any audio Track in this case. Since in this case I have a live stream with no multi-Audio track.
 
My test cases are:
1. Live: Stream+multi Audio play list.  It works fine and I can switch audio tracks
2. VOD: no multi audio play list. it works fine
3. VOD: multi audio play list it works fine and I can switch audio tracks
4. Live: no multi audio playlist and it fails . Among others I see followings in the Browser console:

Setting audio track to 0
VM56353:1 [object FragmentLoader] enough download bandwidth, adjust start level from 0 to 3
VM56354:1 [object FragmentLoader] _checkLoading : playlist not received for level:3
[object StreamBuffer] StreamBuffer.flushLastFragment, clip end of StreamBuffer
 [object FragmentLoader] _checkLoading : loading too slow, abort fragment loading

I wonder what is specific for non-multi-Audio +LIVE in your fork branch. This test case works when I use flashls from main release.

I couldn't get what you mean when you say  set HLSSettings.altAudioSwitchMode to HLSAltAudioSwitchMode.LEGACY. in HLS.as where there is  the method setAudioTrack(i) or in streamBuffer.as?  Is this property is exposed and I can set it via an external JS script?

In my test I am using bloomberg's LIVE stream.

Any direction here will be very helpful.
@neilrackett

Thanks,
Hamid

**Comment by neilrackett** [comment]
`HLSSettings` is the static class containing all of the settings for Flashls.

My modifications were designed for a specific scenario where all streams have multiple audio tracks and never intended for wider use, so if the Bloomberg stream works with the unmodified Flashls, you could try using the following lines of AS3 code before you load a stream (HLS manifest) to enable/disable my audio switch modifications:

- `HLSSettings.altAudioSwitchMode = HLSAltAudioSwitchMode.LEGACY;` to disable it (Bloomberg, etc)
- `HLSSettings.altAudioSwitchMode = HLSAltAudioSwitchMode.ACTIVE;` to enable it

**Comment by porasl** [comment]
Hi Neil,

I added HLSSettings.altAudioSwitchMode = HLSAltAudioSwitchMode.LEGACY;
to  loadPlaylist() method inm manidest.as and still it doesn't play. In Browser console log I see 

[object HLSPlayTrait] HLSPlayTrait:playStateChangeStart:playing
VM6961:1 [object HLSNetStream] HLSNetStream:play(-1)
VM6962:1 [object HLSNetStream] HLSNetStream:seek2(-1, false)
VM6963:1 [object StreamBuffer] seek : requested position:-1.00, seek position:84.08,min/max buffer position:Infinity/-Infinity
VM6964:1 [object StreamBuffer] StreamBuffer flushed
VM6979:1 Setting audio track to 0
VM6980:1 [object StreamBuffer] StreamBuffer : audio track changed, using LEGACY method to switch to 0
VM6981:1 [object FragmentLoader] enough download bandwidth, adjust start level from 0 to 3
VM6986:1 [object FragmentLoader] _checkLoading : playlist not received for level:3
And nothing after. 

I have tried to set HLSAltAudioSwitchMode to LEGACY anywhere I see any reference to check HLSAltAudioSwitchMode.ACTIVE but it doesn't help.

Any direction here will be very helpful.
@neilrackett

Thanks,
Hamid

**Comment by neilrackett** [comment]
You should only need to set it once (before loading the initial M3U8 manifest file), so it may simply be that that particular stream doesn't work with my version of Flashls.

**Comment by ghost** [comment]
Ok I got it. It works now. Actually it seems to be related to Subtitle. With those profiles that I have captions I have this issue. I tested with 2 profiles without captions and it works in all cases, with multi-audio or without that. So I will remove my unrelated comments. Now next step is to focus on the captions. I see you have also implementation about subtitles.  I will focus to see where/when it fails.  So I continue my test with your default settings. Since I have already seen an issue related captions I will be pleased to hear from you about any issue I have to consider.
 
Any direction here will be very helpful.
@neilrackett
Thanks,
Hamid

**Comment by porasl** [comment]
Hi Neil,
I am using your  implementation for subttile in your fork. It is somehow different with my old fix. In JS side I am listening to 'jssubtitles_callbackFunction' that is associated to my falshObject and my expectation is to get 
 notified when subtitles are available, but I don't get any notification in my JS. In your code I see  Subtitle.toSubtitle(data) is attached to HLSEvent.SUBTITLES_CHANGE and I see you set it as 'subtitle' In the HLSEvent. I guess in HLS dispatcher I can catch it. But I am missing the next step. How can I expose the subtitle to my listener in JS? As mentioned I am expecting a notification via a JS method that I have 
 assigned to 'jssubtitles_callbackFunction.  I am also looking for some methods as enable/disable subtitles. 

Any direction here will be very helpful.
@neilrackett
Thanks,
Hamid

**Comment by ghost** [comment]
Hi Neil.

I was getting a null pointer when my LIVE program had subtitle. Nullpointer is in the SubtitleFragmentLoader line 167.

Now I am reading subtitles. I am looking for a way to expose Subtitles. Is there any other way than ExternalInterface callback?

Any direction here will be very helpful.
@neilrackett
Thanks,
Hamid
[black_screen.log](https://github.com/mangui/flashls/files/1923261/black_screen.log)

**Comment by neilrackett** [comment]
My suggestion would be to create a subtitle renderer overlay that listens for `HLSEvent.SUBTITLES_CHANGE`, for example:

```actionscript
function subtitlesChangeHandler(event:HLSEvent):void
{
    myTextField.text = event.subtitle.text;
}
```

Alternatively, you can use the `onTextData` callback on the `NetStream` object, see https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/net/NetStream.html.

**Comment by ghost** [comment]
Thanks Neil, I fixed it.

**Comment by ghost** [comment]
Thanks Neil, I fixed it.
