### ISSUE TITLE
What is relation between releases?

### ISSUE THREAD

**Issue by ghost** [mangui/flashls#596]
Hi,

I used latest release v0.4.4.24. But for audio track change I encountered video buffering and other issues. I opened an issue and Neil responded to check out his fork.(https://github.com/neilrackett/flashls/tree/prod) and that was useful and with small modification I could expose my method setAudioTrack() that can set the audio track, do Seek and then Load the stream. It works fine now. I wonder what is relation between an official FlashHls release and fork releases as Neil's fork. Are you planning to merge his modification to the main branch? 

As I see there are different releases:
https://github.com/neilrackett/flashls/releases
https://github.com/mangui/flashls/releases

Are these releases parallel threads or somewhere we have a main and official release.

Any direction here will be very helpful.
@mangui @jlacivita @kfeinUI @neilrackett

**Comment by kfeinUI** [comment]
You were pointed to a personal fork to demonstrate some customizations
made. It's not part of the main repo. The usual GitHub process of
submitting a PR with changes appropriate for all is certainly welcome.

**Comment by porasl** [comment]
Hi,

I am using the latest release now, i.e. flashls-0.4.4.24, released May-2017. I set the Audio Track from external JS. After track change video freezes.  Please check following method and please let me know in I am doing anything wrong.

protected function _setAudioTrack(locale : String) : void {
			var i:int=0;
			for each (var altAudioTrack:AltAudioTrack in this.altAudioTracks){
				if((altAudioTrack.lang == locale) && (altAudioTrack.url != null)){
					if (i == this.audioTrack) return;
					this.audioTrack = i;
					break;
				}
				i++;
			}
			if (!isNaN(this.position)) {
				this.stream.seek(this.position);
			}
			this.startLoad();
		}

Any direction here will be very helpful.
@mangui @jlacivita @kfeinUI @neilrackett

**Comment by ghost** [comment]
Thanks
