### ISSUE TITLE
alternate audio track support

### ISSUE THREAD

**Issue by mangui** [mangui/flashls#6]
test streams:
http://chkhu.connectmedia.hu/6094/index.m3u8
Duna Word HD (1280x720)
http://service02-live.connectmedia.hu/6176/index.m3u8
Euronews 704x396
http://service02-live.connectmedia.hu/6119/index.m3u8

http://encode1.hk1.tvb.com/stream/silver/playlist.m3u8

**Comment by mangui** [comment]
should come soon, stay tuned

**Comment by scan** [comment]
Staying tuned!

**Comment by mangui** [comment]
#196 has been merged in dev branch

**Comment by mangui** [comment]
you can now check with latest swf/swc

**Comment by yverbin** [comment]
I have  a problem with playing a live hls streams with an alternative audiotracks. Chunks both audio and video stored in ts format, these streams are normally played on ipad, iphone and using OSMF HLS Plugin. 
During playback, sometimes the values of audioBufferLength and videoBufferLength are close to zero, which leads to video/audio freezes.

**Comment by mangui** [comment]
Hi @yverbin i never had the opportunity to test alt-audio with live streams... so i cannot guarantee the results. could you provide debug/debug2 logs of your issue ?
then eventually i would need an access to your streams as well,
cheers,
Mangui

**Comment by mangui** [comment]
i rethinked about it and definitely there is a potential flaw in the design for live streams with altaudio tracks.
there is only one variable to track audio and  video live playlist sliding.

the issue is that video and audio live playlists might not be synchronized, depending on the playlist reloading timing, meaning that relative position in the live audio and video playlists might not link to the same timestamps.

https://github.com/mangui/flashls/blob/dev/src/org/mangui/hls/stream/StreamBuffer.as#L150

_time_sliding variable would need to be adjusted here so that same timestamps would refer to same absolute position.
this means that there should be two playlists slidings variable defined : 
_audio_time_sliding and _video_time_sliding

this will need some rework in StreamBuffer.as each time _time_sliding variable is used.  i will check how this could be handled.

Cheers,
Mangui

**Comment by yverbin** [comment]
Please tell me when you need the test live streams. And, how i can send it to you ?

**Comment by mangui** [comment]
curl https://api.github.com/users/mangui/events/public | grep email

**Comment by MTYannick** [comment]
I'm up for some extra testing as well!

**Comment by jlacivita** [comment]
hello.  I'm testing 0.4.0.4 w/ Apple's advanced HLS test stream:
http://devimages.apple.com.edgekey.net/streaming/examples/bipbop_16x9/bipbop_16x9_variant.m3u8

using flashlsOSMF

And I see getAlternativeAudioItemAt() working (although info.language isn't set, only info.title) I'm not hearing the tracks switch when i call switchAlternativeAudioIndex. I'm just getting silence after calling it.

Does 0.4.0.4 actually support alternate audio, or are we waiting for another update based on your comments above?

**Comment by mangui** [comment]
Hi @jlacivita there are some identified issues with live alt/audio, but VoD alt/audio should work with flashls/dev (some issues have been fixed in /dev since 0.4.0.4)
I didn't recheck with this 'complex' apple stream. could you check whether you also observe the issue with Chromeless Player / dev ? (just to nail down the pb)
Cheers,
Mangui

**Comment by jlacivita** [comment]
Hi,

It works in Chromeless fine, as well as Grind.

I'll keep digging.

**Comment by jlacivita** [comment]
The only thing i noticed was that language is set to null. not sure if that's because it's missing from Apple's HLS file, or if we need a table to translate from HLS language names to OSMF names. It'd be nice to have in there if the data is available.

**Comment by mangui** [comment]
@yverbin @MTYannick i did some changes to support altaudio live playlists, these are blind changes as I don't have any live altaudio playlist in hands. could you check @ your hand with flashls/dev ? and report any issue(s) ?
thanks
Cheers,
Mangui

**Comment by yverbin** [comment]
i have try to play live stream without success - player is hung with message "initialization".

**Comment by yverbin** [comment]
Sorry, fixed in 427f2733230d90619db1a04cf33b5dcb5028ed8e

**Comment by yverbin** [comment]
problem is still here, but reproduced much less

**Comment by mangui** [comment]
ok , i rechecked with your stream and it is working fine. plz check with latest flashls/dev i did some other fixes. if you still observe some issues let me know

**Comment by yverbin** [comment]
the problem appears even less, but still here.

**Comment by jlacivita** [comment]
One thing I'm seeing in OSMF: the MediaPlayer.hasAlternativeAudio isn't set to true until right after the MediaPlayerStateChangeEvent is fired with MediaPlayerState.PLAYING

This is problematic, because that's when we typical check for all the attributes of a Media.

Is there anyway to get this set slightly earlier?

**Comment by mangui** [comment]
@jlacivita , strange.
this event should be fired when the AlternativeAudioTrait is created.

https://github.com/willwh/osmf/blob/fac113c5fb7d6724992247be39106e1caa00fcfa/framework/OSMF/org/osmf/media/MediaPlayer.as#L1723

https://github.com/willwh/osmf/blob/fac113c5fb7d6724992247be39106e1caa00fcfa/framework/OSMF/org/osmf/media/MediaPlayer.as#L1607

could you dump the backtrace when this state is changing ?

**Comment by dtniland** [comment]
Hello mangui, I work with jlacivita and am working with the alternativeAudio in your hls plugin.  Your code has been great to work with so far, so thanks.  jlacivita's comment was about some work I've been doing.  The issue is that we're keying off of MediaPlayerState.PLAYING to tell the rest of our app that alternative audio is present, but when we look at hasAlternativeAudio at that instant the value is false.  If we listen for: MediaPlayerCapabilityChangeEvent.HAS_ALTERNATIVE_AUDIO_CHANGE, it fires just miliseconds later, but by then it's too late: we've already told our app that there was no alternative audio.

Looking at the stack traces, the relevant spot seems to be at:

at org.osmf.media::MediaPlayer/updateTraitListeners()[/org/osmf/media/MediaPlayer.as:1502]
	at org.osmf.media::MediaPlayer/onTraitAdd()[/org/osmf/media/MediaPlayer.as:1469]
	at flash.events::EventDispatcher/dispatchEventFunction()
	at flash.events::EventDispatcher/dispatchEvent()
	at org.osmf.elements::ProxyElement/processTraitsChangeEvent()[/org/osmf/elements/ProxyElement.as:475]
	at org.osmf.elements::ProxyElement/onTraitAdd()[/org/osmf/elements/ProxyElement.as:436]
	at flash.events::EventDispatcher/dispatchEventFunction()
	at flash.events::EventDispatcher/dispatchEvent()
	at org.osmf.media::MediaElement/setLocalTrait()[/org/osmf/media/MediaElement.as:647]
	at org.osmf.media::MediaElement/addTrait()[/org/osmf/media/MediaElement.as:424]
	at org.mangui.osmf.plugins::HLSMediaElement/initTraits()

After that, the path that leads to the PLAYING state change event is: at org.osmf.media::MediaPlayer/play()
while the path that leads to the HAS_ALTERNATIVE_AUDIO_CHANGE is: at org.osmf.media::MediaPlayer/updateCapabilityForTrait()

It seems to be a simple matter of order -- the play trait is hit first.  I'm not intimately familiar with the inner workings of OSMF so I don't know how hard it would be, but is there anything you can do to affect that sequence so that the .hasAlternativeAudio is already set to true when the PLAYING state is fired?  I realize that there may be parse order issues that are special to what you're trying to do, but the f4m files that we use seem to handle this in the order we need.

Thanks dtniland

**Comment by mangui** [comment]
Hi @dtniland plz recheck with flashls/dev. 
after this change, SMP and GrindPlayer are still working as expected... but it might improve your case.

**Comment by dtniland** [comment]
@mangui yes thank you, the trait order change worked.  The hasAlternativeAudio property is now set correctly.  I've noticed another issue, however.  When we set mediaPlayer.switchAlternativeAudioIndex(0) to get the alternate audio, the switch works correctly (if we seek to the currentPosition at the same time) but the mediaPlayer.currentAlternativeAudioStreamIndex gets set to -2 and will stay there no matter what we do afterwards.  Looking through the call stack debugger, it seems like there's an internal variable: _activeTransitionIndex that is doing the real works of switching, but the variables _lastTransitionIndex and _indexToSwitchTo somehow stay stuck at -2, and these are surfaced to the mediaPlayer.

Sorry to continue this but there is another issue: the switching property of the AlternativeAudioEvent.AUDIO_SWITCHING_CHANGE event is always false, both the first time it is called and the second.  One would assume the first time the event fires, the property would be true.

We can work around all of these issues by keeping the state ourselves outside of your event structure, but that can lead to complications of state, especially when mixed with hitting alternative audio from an f4m file that gets handled by OSMF itself.

**Comment by mangui** [comment]
@dtniland  you might recheck your first issue with latest flashls/dev
there was indeed something wrong with _lastTransitionIndex
for the second issue, i m not sure as this event is fired by OSMF itself, but i would suggest to recheck if this issue is still there after my changes
cheers,
mangui

**Comment by dtniland** [comment]
Thanks, the stream index is fixed!  The switching is still always false, but it's not as serious an issue...

**Comment by mangui** [comment]
closing, alt-audio tracks are now supported

**Comment by jlacivita** [comment]
yay!

**Comment by Prendo93** [comment]
What is the behaviour when there is audio muxed into the video stream AND alternate audio is provided?

Testing that here shows that it will not play:
http://www.flashls.org/latest/examples/chromeless/?src=http%3A%2F%2Fvideo.spalk.co%2Fhls%2Ftest-stream%2Fmaster.m3u8

This stream plays correctly on Safari and iOS clients, and has been validated by the apple mediastreamvalidator.

**Comment by mangui** [comment]
Hi @Prendo93 using latest flashls/dev you should now be able to play the two alternate audio tracks.
However the main track (muxed with video) is not playable since my fix, as it is not signaled in the variant manifest.

**Comment by Prendo93** [comment]
Thanks @mangui. I missed the whitespace. I have amended the variant manifest and all works as expected.

**Comment by Prendo93** [comment]
Sorry to keep coming back to this one, but as far as I can tell this should work.

Switching audio tracks works in the native Safari on iOS, Safari and quicktime players, and the stream is validated by mediastreamvalidator but the audio tracks aren't even picked up by the flashls player.

http://www.flashls.org/latest/examples/chromeless/?src=http%3A%2F%2Fdev-media.spalk.co%2Fhls-sync%2F119%2F62%2Fmaster.m3u8

The audio tracks are exact copies of each other, with 1:22 of silence at the beginning, and then the original clip audio, approximately 1s ahead of the video.
