### ISSUE TITLE
Handling of missing TS segment

### ISSUE THREAD

**Issue by Hiroshi-p** [mangui/flashls#65]
I observe a different behavior between flashls and Apple player implementation (QuickTime running on Safari browser of iOS 7) when a TS segment specified by index file is missing on the server and 404 (not found) is returned.
flashls - continue to retry until the file becomes available. playback is stuck when buffer is exhausted.
Apple player - skip forward to the time point where TS segment becomes available.

I know it's not clearly defined by HLS spec, but Apple player's implementation is preferable for our broadcast scenario. Assuming broadcast sender has some network disconnection for a few minutes, for example, and server does not have actual TS segment (audio/video data) for that duration. When the connection is resumed and the following segments come in, we may want to emit index file which has missing segments with appropriate duration but the actual TS do not exist. With such index file, the player may still seek to the right time point even the data in the middle do not exit.

Could you consider to change flashls's behavior about it?

I don't have external facing sample content at this moment. I guess it is very easy to create on your side by just dropping one TS from existing example.

**Comment by vladsd** [comment]
We have found the same problem and posted the issue:
https://github.com/mangui/flashls/issues/214

Reload entire m3u8 would skip a lot more or will contain missing frame.

A better solution maybe is to skip that frame that failed to load? anyone fixed this issue and can share the code?

Thanks.

**Comment by mangui** [comment]
Hi @vladsd 
the solution would be to add another HLSSettings
HLSSettings.FragmentLoadSkipAfterMaxRetry = true/false;
and add a condition check here:
https://github.com/mangui/flashls/blob/dev/src/org/mangui/hls/loader/FragmentLoader.as#L357-L358
if this condition is set, do the following :

_frag_previous = _frag_current;
_loading_state = LOADING_IDLE;

Cheers,
Mangui

**Comment by mangui** [comment]
@vladsd plz recheck with latest flashls/dev

**Comment by vladsd** [comment]
Thanks, will test shortly

**Comment by vladsd** [comment]
it works better but player still stops. here is a link to test:
http://test.viaway.com/view/32118734/direct/9935540b-788f-488e-9314-394243d02b5c

even so hls_fragmentloadmaxretry:0 - it still retries load of missing segments
then when it fails to many time it should not stop but continue.

Please advise.

**Comment by mangui** [comment]
strange, could you share debug logs ?

**Comment by vladsd** [comment]
we put debug version of player, try 
http://test.viaway.com/view/32118734/direct/9935540b-788f-488e-9314-394243d02b5c

my direct email is vlad at viaway.com

**Comment by vladsd** [comment]
here is another stream, this time its m3u8 which times out and it fails to reload over and over. We have a lot of good test cases for you.
test.viaway.com/view/33450507/direct/ac108633-d252-431d-b300-28db59bd7409

it fails one m3u8 and stops? here is a log:
 INFO:onConfig()
VM32346:1 INFO:onLoad()
VM32347:1 INFO:HLSSettings.logDebug = false
VM32348:1 INFO:HLSSettings.fragmentLoadMaxRetry = 0
VM32349:1 INFO:HLSSettings.fragmentLoadSkipAfterMaxRetry = true
VM32350:1 INFO:HLSSettings.logDebug2 = false
VM32362:1 INFO:load()http://live.viaway.com/dvr2/ac108633-d252-431d-b300-28db59bd7409/stream.m3u…OEY5lJle4XS6-ND6KEjMwWs0SSiOiiqXqjCB2ApE_&Key-Pair-Id=APKAIKLC7OLZQU7AR5JQ
VM32363:1 INFO:HLSNetStream:close
VM32367:1 INFO:HLSNetStream:play(-1)
VM32368:1 INFO:HLSNetStream:seek(-1)
VM32394:1 INFO:Setting audio track to 0
VM32400:1 INFO:video size changed to 640/360
VM32446:1 INFO:stop()
VM32447:1 INFO:HLSNetStream:close

**Comment by jsardas** [comment]
Hi @cmelendez ,

Would you mind sharing how you are reloading the stream? I actually prefer this approach instead of trying to skip a segment since it reloads the playlist and helps deal with situations where the player may have gone completely out of the sliding window for live streams.

However I can't seem to find how to reload the playlist directly from ActionScript, because I have no reference to a variable holding the playlist URL accessible outside of ManifestLoader.as.

I had to implement it by first dispatching an event which is received by an external JS API, which then in turn reloads the playlist and starts playing the stream again. But perhaps there is a better way of doing it directly from ActionScript.

Thanks.

**Comment by jsardas** [comment]
Shouldn't the order of _frag_current = _frag_previous be the opposite at
https://github.com/mangui/flashls/blob/dev/src/org/mangui/hls/loader/FragmentLoader.as#L361 ?

It works as expected if I change the current order (_frag_previous = _frag_current), and it also matches @mangui 's original answer at
https://github.com/mangui/flashls/issues/65#issuecomment-77744583

**Comment by mangui** [comment]
@jsardas  indeed ...

**Comment by mangui** [comment]
implemented
